import { sortAllEquations } from '../search/sort'
import { GainType } from './constants'
import { type BlessingEquation, BlessingEquationEr, BuffType } from './types'

const equations: Array<BlessingEquation> = sortAllEquations([
  {
    _id: 670010,
    path: 120,
    rarity: 4,
    name: '城市复原师',
    desc: "行动序列上出现【彗核】：每次行动时，吸收我方全体的护盾至1点并变为自身的护盾值，并对敌方全体造成该值<color style='color:#f29e38;'> 2500% </color>+<color style='color:#f29e38;'> 1000% </color><u class='infou'>基础伤害</u>的物理属性伤害，有<color style='color:#f29e38;'> 100% </color>基础概率使敌方目标陷入持续<color style='color:#f29e38;'> 1 </color>回合的冻结状态。角色受到伤害时优先消耗【彗核】的护盾值，且造成【<u class='infou'>反震</u>】伤害时，【彗核】<color style='color:#f29e38;'> 80% </color>的护盾值会被视为角色护盾。",
    effects: [61000500, 70000102],
    need: {
      '120': 8,
      '121': 4,
    },
    er: 8,
    rel: [GainType.Shield, GainType.Freeze],
    type: BuffType.Equation,
  },
  {
    _id: 670140,
    path: 121,
    rarity: 4,
    name: '沉默猎手',
    desc: "敌方目标进入战斗时，有<color style='color:#f29e38;'> 100% </color>的基础概率陷入持续<color style='color:#f29e38;'> 1 </color>回合的【<u class='infou'>离神</u>】状态。【<u class='infou'>离神</u>】状态下的敌方目标抵抗所有伤害，并记录所有受到的暴击伤害与击破伤害，解除时，额外对敌方全体造成等同于记录值<color style='color:#f29e38;'> 150% </color>的固定数值的暴击伤害。当记录值达到目标生命上限的<color style='color:#f29e38;'> 50% </color>时【<u class='infou'>离神</u>】会立刻解除。",
    effects: [60000002],
    need: {
      '121': 7,
      '124': 5,
    },
    er: 8,
    rel: [
      GainType.DissociationDmg,
      GainType.Freeze,
      GainType.CRITDMG,
      GainType.BreakDmg,
      GainType.SuperBreakDmg,
    ],
    type: BuffType.Equation,
  },
  {
    _id: 670280,
    path: 122,
    rarity: 4,
    name: '自证学社',
    desc: "【<u class='infou'>怀疑</u>】达到<color style='color:#f29e38;'> 99 </color>层后会被消耗并变为1层【自我否定】：攻击者对其造成的持续伤害提高<color style='color:#f29e38;'> 70% </color>，每层额外提高<color style='color:#f29e38;'> 10% </color>，最多叠加<color style='color:#f29e38;'> 50 </color>层。敌方目标回合开始时受到<color style='color:#f29e38;'> 135% </color><u class='infou'>基础伤害</u>的雷属性持续伤害，并使相邻目标受到原伤害倍率<color style='color:#f29e38;'> 20% </color>的雷属性持续伤害。大于等于<color style='color:#f29e38;'> 2 </color>层：回合开始时恢复随机1名角色<color style='color:#f29e38;'> 20% </color>的【<u class='infou'>罐中脑</u>】，大于等于<color style='color:#f29e38;'> 3 </color>层：回合开始时恢复我方全体<color style='color:#f29e38;'> 10% </color>的【<u class='infou'>罐中脑</u>】。",
    effects: [60000012, 61000500, 61000044],
    need: {
      '122': 8,
      '128': 4,
    },
    er: 8,
    rel: [
      GainType.Suspicion,
      GainType.DoT_By_Char,
      GainType.DoT,
      GainType.Brain_in_a_Vat_Charge,
      GainType.MON_in_NEG_EFFECT,
    ],
    type: BuffType.Equation,
  },
  {
    _id: 670350,
    path: 123,
    rarity: 4,
    name: '步离人',
    desc: "行动序列上出现【断灭花】：【<u class='infou'>珠露</u>】破裂时会基于自身充能的<color style='color:#f29e38;'> 600% </color>为【断灭花】充能，行动时，对敌方全体造成充能值+<color style='color:#f29e38;'> 1200% </color><u class='infou'>基础伤害</u>的火属性伤害。我方全体每有1层【<u class='infou'>战意</u>】都会使该伤害额外提高<color style='color:#f29e38;'> 1.5% </color>。",
    effects: [60000013, 61000500, 60000005],
    need: {
      '123': 8,
      '125': 4,
    },
    er: 8,
    rel: [GainType.DewDropDmg, GainType.Grit],
    type: BuffType.Equation,
  },
  {
    _id: 670470,
    path: 124,
    rarity: 4,
    name: '熔火骑士',
    desc: "我方全体每获得<color style='color:#f29e38;'> 9 </color>层【<u class='infou'>会心</u>】或消灭敌方目标后，射出<color style='color:#f29e38;'> 10 </color>根光矢攻击随机敌方目标，每支光矢造成<color style='color:#f29e38;'> 400% </color><u class='infou'>基础伤害</u>的风属性伤害并对攻击目标添加<color style='color:#f29e38;'>1</color>个【<u class='infou'>孢子</u>】并造成1次【<u class='infou'>孢子</u>】爆裂的伤害，该效果期间【<u class='infou'>孢子</u>】层数上限变为<color style='color:#f29e38;'> 99 </color>。",
    effects: [60000004, 61000500, 60000017],
    need: {
      '124': 8,
      '127': 4,
    },
    er: 8,
    rel: [GainType.CriticalBoost, GainType.SporeDmg, GainType.SporeCnt],
    type: BuffType.Equation,
  },
  {
    _id: 670500,
    path: 125,
    rarity: 4,
    name: '远航监护员',
    desc: "角色造成击破伤害后，会在攻击后额外造成等同于原伤害<color style='color:#f29e38;'> 100% </color>固定数值的附加伤害。角色的【<u class='infou'>战意</u>】 大于<color style='color:#f29e38;'> 30 </color>层时，获得等同于自身最大生命值<color style='color:#f29e38;'> 50% </color>的护盾，持续<color style='color:#f29e38;'> 2 </color>回合，对敌方全体造成<color style='color:#f29e38;'> 1200% </color><u class='infou'>基础伤害</u>的伤害与<color style='color:#f29e38;'> 15 </color>点削韧，并消耗<color style='color:#f29e38;'> 20 </color>层 【<u class='infou'>战意</u>】。",
    effects: [60000005, 61000500],
    need: {
      '120': 5,
      '125': 7,
    },
    er: 8,
    rel: [
      GainType.BreakDmg,
      GainType.SuperBreakDmg,
      GainType.AdditionalDmg,
      GainType.Grit,
      GainType.Shield,
      GainType.CutToughness,
    ],
    type: BuffType.Equation,
  },
  {
    _id: 670630,
    path: 126,
    rarity: 4,
    name: '谏语医师',
    desc: "【<u class='infou'>珠露</u>】造成的伤害视为追加攻击伤害，角色发动追加攻击或攻击造成【<u class='infou'>珠露</u>】破裂后，有<color style='color:#f29e38;'> 16% </color>固定概率在攻击后触发效果：使【<u class='infou'>珠露</u>】充能其上限的<color style='color:#f29e38;'> 80% </color>，并以<color style='color:#f29e38;'> 10% </color>/<color style='color:#f29e38;'> 40% </color>/<color style='color:#f29e38;'> 40% </color>/<color style='color:#f29e38;'> 10% </color>的固定概率造成1/2/3/4倍【<u class='infou'>珠露</u>】充能值的伤害。",
    effects: [60000013],
    need: {
      '123': 4,
      '126': 8,
    },
    er: 8,
    rel: [
      GainType.DewDropDmg,
      GainType.FollowUpAtk,
      GainType.DewDropCharge,
      GainType.HEAL,
      GainType.Healing,
    ],
    type: BuffType.Equation,
  },
  {
    _id: 670720,
    path: 127,
    rarity: 4,
    name: '孕灾之子',
    desc: "敌方目标进入战斗时获得【蛀洞】：【蛀洞】会记录持有者获得的【<u class='infou'>孢子</u>】数量，达到<color style='color:#f29e38;'> 18 </color>个时，对敌方全体造成<color style='color:#f29e38;'> 2200% </color><u class='infou'>基础伤害</u>的量子属性伤害，每有1个负面状态，该伤害提高<color style='color:#f29e38;'> 10% </color>，最多提高<color style='color:#f29e38;'> 100% </color>，然后清空记录的数量。",
    effects: [60000017, 61000500],
    need: {
      '122': 5,
      '127': 7,
    },
    er: 8,
    rel: [GainType.SporeCnt, GainType.MON_in_NEG_EFFECT],
    type: BuffType.Equation,
  },
  {
    _id: 670860,
    path: 128,
    rarity: 4,
    name: '无用学者',
    desc: "我方全体在非【超频】状态下累计施放<color style='color:#f29e38;'> 6 </color>次终结技后，获得【超频】状态：施放终结技发动攻击后，对攻击目标造成<color style='color:#f29e38;'> 3 </color>次等同于攻击者<color style='color:#f29e38;'> 100% </color>攻击力的【<u class='infou'>回味</u>】伤害，施放终结技后退出该状态，编队中的第一位角色激活终结技并将【<u class='infou'>罐中脑</u>】充能至<color style='color:#f29e38;'> 200% </color>，且在施放<color style='color:#f29e38;'> 3 </color>次终结技后才退出该状态。",
    effects: [60000003, 61000044],
    need: {
      '126': 5,
      '128': 7,
    },
    er: 8,
    rel: [
      GainType.Brain_in_a_Vat_Charge,
      GainType.UltimateAtk,
      GainType.FollowUpAtk,
      GainType.Aftertaste,
    ],
    type: BuffType.Equation,
  },
  {
    _id: 670150,
    path: 121,
    rarity: 4,
    name: '伤痕冢',
    desc: "行动序列上出现【遗忘】：我方目标每造成 10 点实际削韧值，使其行动提前<color style='color:#f29e38;'> 3% </color>。行动时，对敌方全体造成<color style='color:#f29e38;'> 2000% </color><u class='infou'>基础伤害</u>的冰属性伤害与<color style='color:#f29e38;'> 20 </color>点削韧，有<color style='color:#f29e38;'> 150% </color>基础概率使目标陷入【<u class='infou'>离神</u>】状态，持续<color style='color:#f29e38;'> 1 </color>回合，受到的伤害提高<color style='color:#f29e38;'> 60% </color>，持续<color style='color:#f29e38;'> 2 </color>回合。",
    effects: [61000500, 60000002],
    need: {
      '121': 8,
      '125': 4,
    },
    er: 8,
    rel: [
      GainType.CutToughness,
      GainType.DissociationDmg,
      GainType.Freeze,
      GainType.MON_VUL_INC,
    ],
    type: BuffType.Equation,
  },
  {
    _id: 670430,
    path: 124,
    rarity: 4,
    name: '纺生救主',
    desc: "不存在持有【纤维】的敌方目标时，角色施放攻击后使随机攻击目标持有【纤维】。持有【纤维】的目标累计受到<color style='color:#f29e38;'> 8 </color>次攻击后或被消灭后，受到<color style='color:#f29e38;'> 4500% </color><u class='infou'>基础伤害</u>的雷属性伤害，相邻目标受到<color style='color:#f29e38;'> 3000% </color><u class='infou'>基础伤害</u>的伤害，并使我方全体生命上限提高<color style='color:#f29e38;'> 80% </color>，持续<color style='color:#f29e38;'> 3 </color>回合，若只攻击了1名敌方目标，则视为发动<color style='color:#f29e38;'> 2 </color>次攻击。",
    effects: [61000500],
    need: {
      '123': 4,
      '124': 8,
    },
    er: 8,
    rel: [GainType.SuccessiveAction, GainType.HEAL],
    type: BuffType.Equation,
  },
  {
    _id: 670580,
    path: 125,
    rarity: 4,
    name: '灭绝学人',
    desc: "角色受到攻击后获得<color style='color:#f29e38;'> 2 </color>个【灭绝式】，发动反击后获得<color style='color:#f29e38;'> 1 </color>个。拥有<color style='color:#f29e38;'> 6 </color>个【灭绝式】时，清空【灭绝式】，使造成的终结技伤害提高<color style='color:#f29e38;'> 150% </color>，持续<color style='color:#f29e38;'> 2 </color>回合，并对敌方全体造成等同于攻击力<color style='color:#f29e38;'> 650% </color>的附加伤害，该伤害视为终结技伤害。",
    effects: [],
    need: {
      '125': 7,
      '128': 5,
    },
    er: 8,
    rel: [GainType.BeHit, GainType.CounterAtk, GainType.UltimateAtk],
    type: BuffType.Equation,
  },
  {
    _id: 670640,
    path: 126,
    rarity: 4,
    name: '幻影怪盗',
    desc: "行动序列上出现【预告函】：角色发动追加攻击后，使其行动提前<color style='color:#f29e38;'> 5% </color>，行动时，编队中的第一位角色行动提前<color style='color:#f29e38;'> 100% </color>，施放攻击后造成<color style='color:#f29e38;'> 10 </color>次等同于角色攻击力<color style='color:#f29e38;'> 40% </color>的【<u class='infou'>回味</u>】伤害，最多生效<color style='color:#f29e38;'> 4 </color>次攻击，我方全体造成的【<u class='infou'>回味</u>】伤害倍率提高原倍率的<color style='color:#f29e38;'> 100% </color>，且行动序列上出现速度为<color style='color:#f29e38;'> 100 </color>的倒计时，效果持续至倒计时回合开始时。",
    effects: [60000003],
    need: {
      '124': 4,
      '126': 8,
    },
    er: 8,
    rel: [
      GainType.FollowUpAtk,
      GainType.Aftertaste,
      GainType.AdditionalDmg,
      GainType.SuccessiveAction,
    ],
    type: BuffType.Equation,
  },
  {
    _id: 670870,
    path: 128,
    rarity: 4,
    name: '聚合者',
    desc: "我方全体累计施放<color style='color:#f29e38;'> 2 </color>次终结技后，对随机敌方单体造成<color style='color:#f29e38;'> 2 </color>段等同于<color style='color:#f29e38;'> 400% </color><u class='infou'>基础伤害</u>的风属性伤害并附加<color style='color:#f29e38;'> 1 </color>个【<u class='infou'>孢子</u>】，该伤害会对相邻单位造成等同于原伤害<color style='color:#f29e38;'> 30% </color>的伤害。每次触发该效果，都会使伤害段数在本场战斗中增加1段，并使角色造成的终结技伤害提高<color style='color:#f29e38;'> 7% </color>，最多叠加<color style='color:#f29e38;'> 20 </color>次。",
    effects: [61000500, 60000017],
    need: {
      '127': 4,
      '128': 8,
    },
    er: 8,
    rel: [GainType.UltimateAtk, GainType.SporeDmg, GainType.SporeCnt],
    type: BuffType.Equation,
  },
  {
    _id: 670210,
    path: 122,
    rarity: 4,
    name: '相对描摹者',
    desc: "敌方目标陷入【<u class='infou'>怀疑</u>】、冻结和持续伤害状态时，有<color style='color:#f29e38;'> 150% </color>的基础概率将该效果扩散给相邻目标，无相邻目标时扩散给自身，单次行动内同一目标只能扩散1次相同效果。单个敌方目标每累计扩散<color style='color:#f29e38;'> 20 </color>次或被消灭，使该目标与相邻目标受到<color style='color:#f29e38;'> 1200% </color><u class='infou'>基础伤害</u>的冰属性伤害，并有<color style='color:#f29e38;'> 60% </color>的基础概率陷入冻结状态，持续<color style='color:#f29e38;'> 1 </color>回合。",
    effects: [60000012, 61000500],
    need: {
      '121': 5,
      '122': 7,
    },
    er: 8,
    type: BuffType.Equation,
    rel: [
      GainType.Suspicion,
      GainType.Freeze,
      GainType.DissociationDmg,
      GainType.DoT,
      GainType.DamageSpread,
      GainType.Kill,
    ],
  },
  {
    _id: 670700,
    path: 127,
    rarity: 4,
    name: '抟星蠕虫',
    desc: "敌方目标受到的普攻、战技伤害提高<color style='color:#f29e38;'> 100% </color>。行动序列上出现【虫嗣】：我方目标获得或消耗战技点时会增加1段其下次攻击的攻击段数，回合开始时，每段攻击段数对随机敌方单体造成等同于<color style='color:#f29e38;'> 500% </color><u class='infou'>基础伤害</u>的风属性伤害，并使我方全体获得等同于<color style='color:#f29e38;'> 3% </color>生命上限的护盾。【虫嗣】的攻击段数不低于<color style='color:#f29e38;'> 10 </color>段。",
    effects: [61000500],
    need: {
      '120': 4,
      '127': 8,
    },
    er: 8,
    type: BuffType.Equation,
    rel: [
      GainType.NomralAtk,
      GainType.SkillAtk,
      GainType.Point,
      GainType.AdditionalDmg,
      GainType.Shield,
    ],
  },
  {
    _id: 670060,
    path: 120,
    rarity: 4,
    name: '无心巨人',
    desc: "【<u class='infou'>反震</u>】伤害视为追加攻击伤害。角色发动追加攻击后，使我方全体获得1层【机心部件】，最多叠加<color style='color:#f29e38;'> 77 </color>层。持有护盾的角色受到攻击后，消耗自身全部【机心部件】，对攻击目标造成<color style='color:#f29e38;'> 7 </color>次随机属性等同于当前护盾量<color style='color:#f29e38;'> 177% </color>的【<u class='infou'>反震</u>】伤害，每消耗1层，使该伤害提高<color style='color:#f29e38;'> 7% </color>。",
    effects: [70000102],
    need: {
      '120': 8,
      '126': 4,
    },
    er: 8,
    type: BuffType.Equation,
    rel: [
      GainType.QuakeDmg,
      GainType.FollowUpAtk,
      GainType.Aftertaste,
      GainType.Shield,
      GainType.BeHit,
    ],
  },
  {
    _id: 671020,
    path: 120,
    rarity: 4,
    name: '无神论者',
    desc: "角色造成【<u class='infou'>反震</u>】伤害时，敌方目标每处于1种持续伤害状态类型，本次【<u class='infou'>反震</u>】的伤害倍率提高原倍率的<color style='color:#f29e38;'> 50% </color>。",
    effects: [70000102],
    need: {
      '120': 5,
      '122': 3,
    },
    er: 6,
    rel: [GainType.DoT, GainType.QuakeDmg, GainType.MON_in_NEG_EFFECT],
    type: BuffType.Equation,
  },
  {
    _id: 671030,
    path: 120,
    rarity: 4,
    name: '生态管理员',
    desc: "角色造成【<u class='infou'>反震</u>】伤害时，每有1名角色的当前生命值等于生命上限，本次【<u class='infou'>反震</u>】的伤害倍率提高原倍率的<color style='color:#f29e38;'> 35% </color>。",
    effects: [70000102],
    need: {
      '120': 5,
      '123': 3,
    },
    er: 6,
    rel: [GainType.QuakeDmg, GainType.HEAL],
    type: BuffType.Equation,
  },
  {
    _id: 671130,
    path: 121,
    rarity: 4,
    name: '记忆医生',
    desc: "【<u class='infou'>珠露</u>】的充能效率提高<color style='color:#f29e38;'> 50% </color>，角色施放攻击后，【<u class='infou'>珠露</u>】会对场上处于冻结状态下的敌方目标额外造成1次等同于【<u class='infou'>珠露</u>】原伤害倍率<color style='color:#f29e38;'> 250% </color>的【<u class='infou'>珠露</u>】伤害。",
    effects: [60000013],
    need: {
      '121': 4,
      '123': 4,
    },
    er: 6,
    rel: [GainType.DewDropDmg, GainType.Freeze, GainType.AdditionalDmg],
    type: BuffType.Equation,
  },
  {
    _id: 671180,
    path: 121,
    rarity: 4,
    name: '星体计算机',
    desc: "敌方目标解除冻结状态时，我方全体恢复<color style='color:#f29e38;'> 4 </color>点能量。解除【<u class='infou'>离神</u>】状态时，额外恢复<color style='color:#f29e38;'> 8 </color>点能量。",
    effects: [60000002],
    need: {
      '121': 5,
      '128': 3,
    },
    er: 6,
    rel: [GainType.Freeze, GainType.ENERGY_Charge],
    type: BuffType.Equation,
  },
  {
    _id: 671210,
    path: 122,
    rarity: 4,
    name: '激雷乐队',
    desc: "敌方目标陷入冻结状态时，使其当前承受的所有持续伤害立即产生相当于原伤害<color style='color:#f29e38;'> 180% </color>的伤害，每有1个持续伤害状态，陷入1层【<u class='infou'>怀疑</u>】效果。",
    effects: [60000012],
    need: {
      '121': 3,
      '122': 5,
    },
    er: 6,
    rel: [
      GainType.Freeze,
      GainType.DissociationDmg,
      GainType.HitFrozenUnit,
      GainType.DoT,
      GainType.Suspicion,
      GainType.DotDetonate,
      GainType.MON_in_NEG_EFFECT,
    ],
    type: BuffType.Equation,
  },
  {
    _id: 671260,
    path: 122,
    rarity: 4,
    name: '无我丑角',
    desc: "角色发动追加攻击后，有<color style='color:#f29e38;'> 150% </color>基础概率使攻击目标陷入1个随机负面效果，持续<color style='color:#f29e38;'> 2 </color>回合，随机负面效果包括：造成的伤害降低<color style='color:#f29e38;'> 15% </color>，防御力降低<color style='color:#f29e38;'> 30% </color>，速度降低<color style='color:#f29e38;'> 20% </color>。",
    effects: [],
    need: {
      '122': 4,
      '126': 4,
    },
    er: 6,
    rel: [
      GainType.FollowUpAtk,
      GainType.MON_in_NEG_EFFECT,
      GainType.MON_DMG_DEC,
      GainType.MON_DEF_DEC,
      GainType.MON_SPD_DEC,
    ],
    type: BuffType.Equation,
  },
  {
    _id: 671340,
    path: 123,
    rarity: 4,
    name: '长生陌客',
    desc: "【<u class='infou'>珠露</u>】充能时，角色每有1%的暴击率就有<color style='color:#f29e38;'> 1% </color>的固定概率使充能值提高，提高的比例等同于角色暴击伤害的<color style='color:#f29e38;'> 50% </color>。",
    effects: [60000013],
    need: {
      '123': 5,
      '124': 3,
    },
    er: 6,
    rel: [
      GainType.DewDropCharge,
      GainType.CRIT,
      GainType.CRITDMG,
      GainType.CriticalBoost,
    ],
    type: BuffType.Equation,
  },
  {
    _id: 671370,
    path: 123,
    rarity: 4,
    name: '视肉',
    desc: "【<u class='infou'>珠露</u>】上限提高<color style='color:#f29e38;'> 100% </color>，角色施放普攻使【<u class='infou'>珠露</u>】破裂时，返还该【<u class='infou'>珠露</u>】<color style='color:#f29e38;'> 35% </color>的充能值。",
    effects: [60000013],
    need: {
      '123': 5,
      '127': 3,
    },
    er: 6,
    rel: [GainType.DewDropCharge, GainType.DewDropDmg, GainType.NomralAtk],
    type: BuffType.Equation,
  },
  {
    _id: 671400,
    path: 124,
    rarity: 4,
    name: '天灾遏止机关',
    desc: "敌方目标施放攻击使角色护盾减少后，我方全体速度提高<color style='color:#f29e38;'> 35% </color>，持续<color style='color:#f29e38;'> 2 </color>回合，并获得<color style='color:#f29e38;'> 2 </color>层【<u class='infou'>会心</u>】 效果。",
    effects: [60000004],
    need: {
      '120': 3,
      '124': 5,
    },
    er: 6,
    rel: [
      GainType.Shield,
      GainType.SPD,
      GainType.CRIT,
      GainType.CRITDMG,
      GainType.CriticalBoost,
    ],
    type: BuffType.Equation,
  },
  {
    _id: 671460,
    path: 124,
    rarity: 4,
    name: '赏金猎人',
    desc: "角色施放攻击造成暴击伤害后，有<color style='color:#f29e38;'> 65% </color>固定概率额外造成<color style='color:#f29e38;'> 1 </color>次等同于原伤害1%~ 100% 固定数值的暴击伤害，本次伤害视为追加攻击伤害。",
    effects: [],
    need: {
      '124': 4,
      '126': 4,
    },
    er: 6,
    rel: [
      GainType.CRITDMG,
      GainType.CRIT,
      GainType.CriticalBoost,
      GainType.AdditionalDmg,
      GainType.FollowUpAtk,
    ],
    type: BuffType.Equation,
  },
  {
    _id: 671510,
    path: 125,
    rarity: 4,
    name: '窃忆者',
    desc: "角色施放攻击造成终结技伤害时，消耗等同于当前生命值<color style='color:#f29e38;'> 5% </color>的生命值，并在该次攻击后有<color style='color:#f29e38;'> 50% </color>基础概率使攻击目标陷入冻结状态，持续<color style='color:#f29e38;'> 1 </color>回合。每有1层【<u class='infou'>战意</u>】，角色效果命中提高<color style='color:#f29e38;'> 2% </color>。",
    effects: [60000005],
    need: {
      '121': 3,
      '125': 5,
    },
    er: 6,
    rel: [
      GainType.UltimateAtk,
      GainType.HEAL,
      GainType.Freeze,
      GainType.Grit,
      GainType.EFFECT_HIT_RATE,
    ],
    type: BuffType.Equation,
  },
  {
    _id: 671520,
    path: 125,
    rarity: 4,
    name: '废土客',
    desc: "角色攻击处于弱点击破状态下的敌方目标后，会将本次攻击的削韧值转化为1次<color style='color:#f29e38;'> 100% </color>的<u class='infou'>超击破伤害</u>。累计获得<color style='color:#f29e38;'> 30 </color>层【<u class='infou'>战意</u>】后，该效果额外造成<color style='color:#f29e38;'> 100% </color>的<u class='infou'>超击破伤害</u>。",
    effects: [10000015, 60000005],
    need: {
      '122': 4,
      '125': 4,
    },
    er: 6,
    rel: [
      GainType.SuperBreakDmg,
      GainType.HitWeak,
      GainType.CutToughness,
      GainType.Grit,
    ],
    type: BuffType.Equation,
  },
  {
    _id: 671650,
    path: 126,
    rarity: 4,
    name: '烟花大师',
    desc: "角色造成的追加攻击伤害提高<color style='color:#f29e38;'> 50% </color>，发动追加攻击后，对受到攻击的敌方目标造成1次等同于累计损失及治疗自身生命值<color style='color:#f29e38;'> 500% </color>的【<u class='infou'>回味</u>】伤害，并清空累计值，最多累计自身生命上限的<color style='color:#f29e38;'> 200% </color>。",
    effects: [60000003],
    need: {
      '125': 3,
      '126': 5,
    },
    er: 6,
    rel: [
      GainType.FollowUpAtk,
      GainType.HEAL,
      GainType.Healing,
      GainType.Aftertaste,
    ],
    type: BuffType.Equation,
  },
  {
    _id: 671670,
    path: 126,
    rarity: 4,
    name: '以太幽灵',
    desc: "【<u class='infou'>孢子</u>】上限提高<color style='color:#f29e38;'> 5 </color>个。角色发动追加攻击后，使攻击目标获得<color style='color:#f29e38;'> 3 </color>个【<u class='infou'>孢子</u>】。",
    effects: [60000017],
    need: {
      '126': 4,
      '127': 4,
    },
    er: 6,
    rel: [GainType.SporeCnt, GainType.FollowUpAtk],
    type: BuffType.Equation,
  },
  {
    _id: 671700,
    path: 127,
    rarity: 4,
    name: '孕灾蠧役',
    desc: "角色获得护盾时，使<color style='color:#f29e38;'> 2 </color>个随机敌方目标获得1个【<u class='infou'>孢子</u>】。【<u class='infou'>孢子</u>】伤害倍率提高原倍率的<color style='color:#f29e38;'> 75% </color>。",
    effects: [60000017],
    need: {
      '120': 3,
      '127': 5,
    },
    er: 6,
    rel: [GainType.Shield, GainType.SporeCnt, GainType.SporeDmg],
    type: BuffType.Equation,
  },
  {
    _id: 671780,
    path: 127,
    rarity: 4,
    name: '惑世蠧役',
    desc: "【<u class='infou'>孢子</u>】上限提高<color style='color:#f29e38;'> 3 </color>个。角色施放攻击造成终结技伤害后，若攻击目标持有的【<u class='infou'>孢子</u>】爆裂，则会额外对该目标造成等同于<color style='color:#f29e38;'> 250% </color>攻击力的终结技伤害，本次攻击每使1个【<u class='infou'>孢子</u>】爆裂，该伤害倍率提高<color style='color:#f29e38;'> 30% </color>。",
    effects: [60000017],
    need: {
      '127': 5,
      '128': 3,
    },
    er: 6,
    rel: [GainType.UltimateAtk, GainType.SporeDmg, GainType.AdditionalDmg],
    type: BuffType.Equation,
  },
  {
    _id: 671840,
    path: 128,
    rarity: 4,
    name: '银心护卫队',
    desc: "角色击破敌方目标弱点时，为【<u class='infou'>罐中脑</u>】充能 <color style='color:#f29e38;'> 25% </color>，并恢复等同于能量上限<color style='color:#f29e38;'> 10% </color>的能量，消灭敌方目标后，恢复等同于能量上限<color style='color:#f29e38;'> 60% </color>的能量。",
    effects: [61000044],
    need: {
      '124': 3,
      '128': 5,
    },
    er: 6,
    rel: [
      GainType.CutToughness,
      GainType.Break,
      GainType.Brain_in_a_Vat_Charge,
      GainType.ENERGY_Charge,
      GainType.Kill,
    ],
    type: BuffType.Equation,
  },
  {
    _id: 671850,
    path: 128,
    rarity: 4,
    name: '反有机杀手',
    desc: "角色施放终结技时，使我方全体消耗等同于当前生命值<color style='color:#f29e38;'> 5% </color>的生命值，且造成的伤害提高<color style='color:#f29e38;'> 30% </color>，最多叠加<color style='color:#f29e38;'> 4 </color>层，持续<color style='color:#f29e38;'> 2 </color>回合。",
    effects: [],
    need: {
      '125': 4,
      '128': 4,
    },
    er: 6,
    rel: [GainType.UltimateAtk, GainType.HEAL, GainType.DMG_Gain],
    type: BuffType.Equation,
  },
  {
    _id: 671080,
    path: 120,
    rarity: 4,
    name: '文明函授员',
    desc: "角色施放终结技时，获得能够抵消等同于生命上限<color style='color:#f29e38;'> 30% </color>伤害的护盾，持续<color style='color:#f29e38;'> 3 </color>回合。施放攻击造成终结技伤害后，对攻击目标造成等同于当前护盾量<color style='color:#f29e38;'> 600% </color>的【<u class='infou'>反震</u>】伤害。",
    effects: [70000102],
    need: {
      '120': 4,
      '128': 4,
    },
    er: 6,
    rel: [GainType.UltimateAtk, GainType.Shield, GainType.QuakeDmg],
    type: BuffType.Equation,
  },
  {
    _id: 671170,
    path: 121,
    rarity: 4,
    name: '悠游模因',
    desc: "角色造成的普攻伤害提高<color style='color:#f29e38;'> 200% </color>，施放普攻发动攻击时，会将处于弱点击破状态下的敌人，视为陷入冻结状态。",
    effects: [],
    need: {
      '121': 4,
      '127': 4,
    },
    er: 6,
    rel: [
      GainType.NomralAtk,
      GainType.HitWeak,
      GainType.Freeze,
      GainType.HitFrozenUnit,
    ],
    type: BuffType.Equation,
  },
  {
    _id: 671230,
    path: 122,
    rarity: 4,
    name: '拒死者',
    desc: "角色造成的持续伤害提高<color style='color:#f29e38;'> 160% </color>，对敌方目标施加负面状态后，生命上限提高<color style='color:#f29e38;'> 2% </color>，最多叠加<color style='color:#f29e38;'> 20 </color>层，持续<color style='color:#f29e38;'> 2 </color>回合。",
    effects: [],
    need: {
      '122': 5,
      '123': 3,
    },
    er: 6,
    rel: [GainType.DoT_By_Char, GainType.MON_in_NEG_EFFECT, GainType.HEAL],
    type: BuffType.Equation,
  },
  {
    _id: 671360,
    path: 123,
    rarity: 4,
    name: '向死狂人',
    desc: "角色生命上限提高<color style='color:#f29e38;'> 40% </color>，累计回复等同于生命上限<color style='color:#f29e38;'> 200% </color>的生命值后，造成的【<u class='infou'>回味</u>】伤害倍率提高原倍率的<color style='color:#f29e38;'> 100% </color>。",
    effects: [60000003],
    need: {
      '123': 4,
      '126': 4,
    },
    er: 6,
    rel: [
      GainType.HEAL,
      GainType.Healing,
      GainType.FollowUpAtk,
      GainType.Aftertaste,
      GainType.AdditionalDmg,
    ],
    type: BuffType.Equation,
  },
  {
    _id: 671450,
    path: 124,
    rarity: 4,
    name: '同态法庭',
    desc: "敌方目标攻击时，若有角色持有【<u class='infou'>会心</u>】，则使该敌方目标受到的伤害提高<color style='color:#f29e38;'> 40% </color>，持续<color style='color:#f29e38;'> 2 </color>回合，并使持有【<u class='infou'>会心</u>】的角色行动提前，每有1层【<u class='infou'>会心</u>】行动提前<color style='color:#f29e38;'> 5% </color>。",
    effects: [60000004],
    need: {
      '124': 5,
      '125': 3,
    },
    er: 6,
    rel: [
      GainType.CriticalBoost,
      GainType.MON_VUL_INC,
      GainType.SuccessiveAction,
    ],
    type: BuffType.Equation,
  },
  {
    _id: 671500,
    path: 125,
    rarity: 4,
    name: '战前关怀员',
    desc: "角色击破特攻提高<color style='color:#f29e38;'> 100% </color>，施放攻击击破敌方目标弱点时，获得能够抵消等同于自身生命上限<color style='color:#f29e38;'> 100% </color>伤害的护盾，持续<color style='color:#f29e38;'> 1 </color>回合，并在攻击后对该目标造成等同于当前护盾量<color style='color:#f29e38;'> 1000% </color>的【<u class='infou'>反震</u>】伤害。",
    effects: [70000102],
    need: {
      '120': 4,
      '125': 4,
    },
    er: 6,
    rel: [GainType.BREAK, GainType.Shield, GainType.QuakeDmg],
    type: BuffType.Equation,
  },
  {
    _id: 671610,
    path: 126,
    rarity: 4,
    name: '回想艺术家',
    desc: "【<u class='infou'>回味</u>】有<color style='color:#f29e38;'> 4% </color>的基础概率使未陷入冻结状态的敌方目标陷入冻结状态，持续<color style='color:#f29e38;'> 1 </color>回合，每次攻击对每名敌方目标最多判定<color style='color:#f29e38;'> 5 </color>次。【<u class='infou'>回味</u>】对冻结状态下的敌方目标的伤害倍率提高原倍率的<color style='color:#f29e38;'> 150% </color>。",
    effects: [60000003],
    need: {
      '121': 3,
      '126': 5,
    },
    er: 6,
    rel: [
      GainType.Aftertaste,
      GainType.FollowUpAtk,
      GainType.Freeze,
      GainType.HitFrozenUnit,
    ],
    type: BuffType.Equation,
  },
  {
    _id: 671740,
    path: 127,
    rarity: 4,
    name: '穷凶蠧役',
    desc: "角色施放攻击后，会为随机攻击目标附加【<u class='infou'>孢子</u>】，我方连续行动次数大于等于<color style='color:#f29e38;'> 1 </color>/<color style='color:#f29e38;'> 2 </color>/<color style='color:#f29e38;'> 3 </color>时，附加的【<u class='infou'>孢子</u>】个数为<color style='color:#f29e38;'> 4 </color>/<color style='color:#f29e38;'> 5 </color>/<color style='color:#f29e38;'> 6 </color>个。",
    effects: [60000017],
    need: {
      '124': 3,
      '127': 5,
    },
    er: 6,
    rel: [GainType.SporeCnt, GainType.SuccessiveAction],
    type: BuffType.Equation,
  },
  {
    _id: 671820,
    path: 128,
    rarity: 4,
    name: '积木师',
    desc: "角色施放攻击后，攻击目标每有1个负面效果，攻击力提高<color style='color:#f29e38;'> 3% </color>，最多叠加<color style='color:#f29e38;'> 99 </color>层，回合结束时失去<color style='color:#f29e38;'> 10 </color>层。",
    effects: [],
    need: {
      '122': 4,
      '128': 4,
    },
    er: 6,
    rel: [GainType.MON_in_NEG_EFFECT, GainType.ATK],
    type: BuffType.Equation,
  },
  {
    _id: 670320,
    path: 123,
    rarity: 4,
    name: '采药人',
    desc: "敌方目标进入战斗时陷入【灵药】：【<u class='infou'>珠露</u>】破裂时，基于充能的<color style='color:#f29e38;'> 5% </color>为攻击目标的【灵药】充能，上限为角色生命上限之和的<color style='color:#f29e38;'> 100% </color>。敌方目标回合开始时，消耗充能值并受到等同于<u class='infou'>基础伤害</u><color style='color:#f29e38;'> 200% </color>的风属性持续伤害，使我方全体回复等同于生命上限<color style='color:#f29e38;'> 5% </color>的生命值。每等同于角色生命上限之和1%的充能值使该伤害提高<color style='color:#f29e38;'> 8% </color>，生命值回复量提高<color style='color:#f29e38;'> 4% </color>。",
    effects: [60000013, 61000500],
    need: {
      '122': 5,
      '123': 7,
    },
    er: 8,
    type: BuffType.Equation,
    rel: [
      GainType.DewDropDmg,
      GainType.DewDropCharge,
      GainType.HEAL,
      GainType.Healing,
      GainType.DMG_Gain,
    ],
  },
  {
    _id: 671570,
    path: 125,
    rarity: 4,
    name: '自我背叛者',
    desc: "角色击破敌方目标弱点时，恢复<color style='color:#f29e38;'> 2 </color>点战技点。根据我方全体战意层数之和，每有<color style='color:#f29e38;'> 5 </color>层【<u class='infou'>战意</u>】，我方全体造成的击破伤害提高<color style='color:#f29e38;'> 2% </color>。",
    effects: [60000005],
    need: {
      '125': 5,
      '127': 3,
    },
    er: 6,
    type: BuffType.Equation,
    rel: [GainType.Break, GainType.Point, GainType.Grit, GainType.BreakDmg],
  },
  {
    _id: 671410,
    path: 124,
    rarity: 4,
    name: '虚构裁决官',
    desc: "角色每受到<color style='color:#f29e38;'> 1% </color>的实际行动提前效果，都会使下回合内造成的伤害提高<color style='color:#f29e38;'> 2% </color>。最多计入行动提前<color style='color:#f29e38;'> 100% </color>，该效果对处于冻结状态下的敌方目标额外提高<color style='color:#f29e38;'> 50% </color>。",
    effects: [],
    need: {
      '121': 3,
      '124': 5,
    },
    er: 6,
    type: BuffType.Equation,
    rel: [
      GainType.SuccessiveAction,
      GainType.DMG_Gain,
      GainType.Freeze,
      GainType.DissociationDmg,
    ],
  },
  {
    _id: 671680,
    path: 126,
    rarity: 4,
    name: '迷狂棋手',
    desc: "角色追加攻击造成的暴击伤害提高<color style='color:#f29e38;'> 100% </color>，利用【<u class='infou'>罐中脑</u>】施放终结技对敌方目标造成伤害时，被视为发动了追加攻击",
    effects: [61000044],
    need: {
      '126': 4,
      '128': 4,
    },
    er: 6,
    type: BuffType.Equation,
    rel: [
      GainType.FollowUpAtk,
      GainType.Aftertaste,
      GainType.Brain_in_a_Vat,
      GainType.UltimateAtk,
    ],
  },
  {
    _id: 671730,
    path: 127,
    rarity: 4,
    name: '孕灾残嗣',
    desc: "每次消耗或溢出1点战技点，使我方全体获得1层【蜜露】，最多叠加<color style='color:#f29e38;'> 10 </color>层。角色施放攻击后，消耗自身全部【蜜露】，每消耗1层，造成等同于生命上限<color style='color:#f29e38;'> 80% </color>的附加伤害，该伤害视为普攻伤害。",
    effects: [],
    need: {
      '123': 3,
      '127': 5,
    },
    er: 6,
    type: BuffType.Equation,
    rel: [
      GainType.Point,
      GainType.HEAL,
      GainType.AdditionalDmg,
      GainType.NomralAtk,
    ],
  },
  {
    _id: 671800,
    path: 128,
    rarity: 4,
    name: '星空生态护工',
    desc: "敌方目标受到的终结技伤害提高<color style='color:#f29e38;'> 75% </color>，角色持有护盾受到攻击时，为【<u class='infou'>罐中脑</u>】充能<color style='color:#f29e38;'> 12% </color>。",
    effects: [61000044],
    need: {
      '120': 3,
      '128': 5,
    },
    er: 6,
    type: BuffType.Equation,
    rel: [
      GainType.UltimateAtk,
      GainType.Shield,
      GainType.BeHit,
      GainType.Brain_in_a_Vat_Charge,
    ],
  },
  {
    _id: 671240,
    path: 122,
    rarity: 4,
    name: '冤仇代行',
    desc: "角色施放攻击后，使攻击目标陷入<color style='color:#f29e38;'> 3 </color>层【<u class='infou'>怀疑</u>】。【<u class='infou'>怀疑</u>】提供的易伤提高<color style='color:#f29e38;'> 20% </color>。角色击中处于【<u class='infou'>怀疑</u>】状态下的敌方目标时，基于【<u class='infou'>怀疑</u>】易伤数值的<color style='color:#f29e38;'> 80% </color>，提高造成的暴击伤害。",
    effects: [60000012],
    need: {
      '122': 5,
      '124': 3,
    },
    er: 6,
    type: BuffType.Equation,
    rel: [
      GainType.Suspicion,
      GainType.SuccessiveAction,
      GainType.MON_VUL_INC,
      GainType.CRIT,
      GainType.CRITDMG,
      GainType.CriticalBoost,
    ],
  },
  {
    _id: 671060,
    path: 120,
    rarity: 4,
    name: '多情卫士',
    desc: "敌方目标受到的追加攻击伤害提高<color style='color:#f29e38;'> 60% </color>，角色消灭敌方目标后，使我方全体可抵抗除持续伤害外的所有伤害，受到攻击后解除该效果，持续<color style='color:#f29e38;'> 2 </color>回合。",
    effects: [],
    need: {
      '120': 4,
      '126': 4,
    },
    er: 6,
    type: BuffType.Equation,
    rel: [
      GainType.FollowUpAtk,
      GainType.Aftertaste,
      GainType.Kill,
      GainType.Shield,
    ],
  },
  {
    _id: 671120,
    path: 121,
    rarity: 4,
    name: '著书人',
    desc: "敌方目标陷入冻结状态时，陷入<color style='color:#f29e38;'> 10 </color>层【<u class='infou'>怀疑</u>】，受到持续伤害后，有<color style='color:#f29e38;'> 20% </color>基础概率陷入冻结状态，持续<color style='color:#f29e38;'> 1 </color>回合，每名敌方目标每<color style='color:#f29e38;'> 2 </color>回合最多通过该方式陷入1次冻结状态。",
    effects: [60000012],
    need: {
      '121': 5,
      '122': 3,
    },
    er: 6,
    type: BuffType.Equation,
    rel: [
      GainType.Freeze,
      GainType.DissociationDmg,
      GainType.Suspicion,
      GainType.DoT,
      GainType.DoT_By_Char,
    ],
  },
  {
    _id: 671350,
    path: 123,
    rarity: 4,
    name: '烧火师',
    desc: "角色生命上限提高<color style='color:#f29e38;'> 50% </color>，每造成<color style='color:#f29e38;'> 10 </color>点实际削韧值，为我方全体的【<u class='infou'>珠露</u>】充能<color style='color:#f29e38;'> 3% </color>，攻击处于弱点击破状态下的敌方目标时，为我方全体的【<u class='infou'>珠露</u>】充能<color style='color:#f29e38;'> 6% </color>。",
    effects: [60000013],
    need: {
      '123': 4,
      '125': 4,
    },
    er: 6,
    type: BuffType.Equation,
    rel: [
      GainType.HEAL,
      GainType.CutToughness,
      GainType.BreakEfficiency,
      GainType.DewDropCharge,
      GainType.HitWeak,
      GainType.Break,
    ],
  },
  {
    _id: 672010,
    path: 120,
    rarity: 4,
    name: '筑城史官',
    desc: "角色攻击后若使敌方目标陷入冻结状态，则我方全体获得等同于生命上限<color style='color:#f29e38;'> 25% </color>的护盾，持续<color style='color:#f29e38;'> 3 </color>回合。本次攻击中每冻结一名敌方目标，获得的护盾量提高生命上限的<color style='color:#f29e38;'> 5% </color>。",
    effects: [],
    need: {
      '120': 3,
      '121': 2,
    },
    er: 4,
    rel: [GainType.HitFrozenUnit, GainType.Freeze, GainType.Shield],
    type: BuffType.Equation,
  },
  {
    _id: 672050,
    path: 120,
    rarity: 4,
    name: '不沉巨舰',
    desc: "角色获得的护盾量提高<color style='color:#f29e38;'> 20% </color>，每损失1%生命值，获得的护盾量额外提高<color style='color:#f29e38;'> 0.8% </color>。",
    effects: [],
    need: {
      '120': 3,
      '125': 2,
    },
    er: 4,
    rel: [GainType.Shield, GainType.HEAL],
    type: BuffType.Equation,
  },
  {
    _id: 672060,
    path: 120,
    rarity: 4,
    name: '筑梦师',
    desc: "角色发动追加攻击后，对攻击目标造成等同于角色当前护盾量<color style='color:#f29e38;'> 360% </color>的【<u class='infou'>反震</u>】伤害。",
    effects: [70000102],
    need: {
      '120': 3,
      '126': 2,
    },
    er: 4,
    rel: [GainType.FollowUpAtk, GainType.Shield, GainType.QuakeDmg],
    type: BuffType.Equation,
  },
  {
    _id: 672100,
    path: 121,
    rarity: 4,
    name: '烛墨学者',
    desc: "角色暴击伤害提高<color style='color:#f29e38;'> 50% </color>，受到致命伤害时，生命值变为1点并获得等同于生命上限<color style='color:#f29e38;'> 100% </color>的护盾，随后陷入无法解除的冻结状态，持续<color style='color:#f29e38;'> 1 </color>回合。该状态下无法回复生命值，我方全体最多触发<color style='color:#f29e38;'> 3 </color>次该效果，次数耗尽后失去暴击伤害提高效果。",
    effects: [],
    need: {
      '120': 2,
      '121': 3,
    },
    er: 4,
    rel: [GainType.CRITDMG, GainType.Shield],
    type: BuffType.Equation,
  },
  {
    _id: 672160,
    path: 121,
    rarity: 4,
    name: '传记作家',
    desc: "角色对冻结状态下的敌方目标施放攻击后，对其造成1次等同于角色攻击力<color style='color:#f29e38;'> 240% </color>的【<u class='infou'>回味</u>】伤害。",
    effects: [60000003],
    need: {
      '121': 3,
      '126': 2,
    },
    er: 4,
    rel: [
      GainType.HitFrozenUnit,
      GainType.Freeze,
      GainType.FollowUpAtk,
      GainType.Aftertaste,
    ],
    type: BuffType.Equation,
  },
  {
    _id: 672180,
    path: 121,
    rarity: 4,
    name: '武装考古队',
    desc: "敌方目标陷入冻结状态后，受到的终结技伤害提高<color style='color:#f29e38;'> 60% </color>，该效果在冻结状态解除后仍会持续<color style='color:#f29e38;'> 2 </color>回合。",
    effects: [],
    need: {
      '121': 3,
      '128': 2,
    },
    er: 4,
    rel: [GainType.Freeze, GainType.DissociationDmg, GainType.UltimateAtk],
    type: BuffType.Equation,
  },
  {
    _id: 672200,
    path: 122,
    rarity: 4,
    name: '守夜人',
    desc: "敌方目标进入战斗时，陷入裂伤状态。裂伤状态下，敌方目标每回合开始时受到等同于自身<color style='color:#f29e38;'> 10% </color>生命上限的物理属性持续伤害，最多不超过我方全体护盾量之和的<color style='color:#f29e38;'> 650% </color>。",
    effects: [],
    need: {
      '120': 2,
      '122': 3,
    },
    er: 4,
    rel: [GainType.DoT, GainType.Shield, GainType.MON_in_NEG_EFFECT],
    type: BuffType.Equation,
  },
  {
    _id: 672240,
    path: 122,
    rarity: 4,
    name: '血罪灵',
    desc: "角色造成的持续伤害可以暴击，造成持续伤害时，暴击伤害最高不超过<color style='color:#f29e38;'> 100% </color>。",
    effects: [],
    need: {
      '122': 3,
      '124': 2,
    },
    er: 4,
    rel: [
      GainType.DoT_By_Char,
      GainType.CRIT,
      GainType.CRITDMG,
      GainType.CriticalBoost,
    ],
    type: BuffType.Equation,
  },
  {
    _id: 672280,
    path: 122,
    rarity: 4,
    name: '庸众凡夫',
    desc: "敌方目标被消灭时，每有1层【<u class='infou'>怀疑</u>】效果，我方全体恢复<color style='color:#f29e38;'> 0.3 </color>点能量。",
    effects: [60000012],
    need: {
      '122': 3,
      '128': 2,
    },
    er: 4,
    rel: [GainType.Kill, GainType.Suspicion, GainType.ENERGY_Charge],
    type: BuffType.Equation,
  },
  {
    _id: 672340,
    path: 123,
    rarity: 4,
    name: '造翼者',
    desc: "敌方目标被消灭时，使【<u class='infou'>珠露</u>】 充能效率提高<color style='color:#f29e38;'> 20% </color>，最多叠加<color style='color:#f29e38;'> 4 </color>层。并使我方全体回复等同于生命上限<color style='color:#f29e38;'> 50% </color>的生命值。",
    effects: [60000013],
    need: {
      '123': 3,
      '124': 2,
    },
    er: 4,
    rel: [GainType.Kill, GainType.DewDropCharge, GainType.Healing],
    type: BuffType.Equation,
  },
  {
    _id: 672350,
    path: 123,
    rarity: 4,
    name: '慧骃',
    desc: "角色每有1层【<u class='infou'>战意</u>】，回复量提高<color style='color:#f29e38;'> 2% </color>。",
    effects: [60000005],
    need: {
      '123': 3,
      '125': 2,
    },
    er: 4,
    rel: [GainType.Grit, GainType.Healing],
    type: BuffType.Equation,
  },
  {
    _id: 672370,
    path: 123,
    rarity: 4,
    name: '共生体',
    desc: "角色回复量提高<color style='color:#f29e38;'> 35% </color>，为我方目标提供治疗后，有<color style='color:#f29e38;'> 50% </color>的固定概率恢复1个战技点，该效果角色每次行动最多触发1次。",
    effects: [],
    need: {
      '123': 3,
      '127': 2,
    },
    er: 4,
    rel: [GainType.Healing, GainType.Point],
    type: BuffType.Equation,
  },
  {
    _id: 672400,
    path: 124,
    rarity: 4,
    name: '边星快枪手',
    desc: "角色受到攻击后，若在该次攻击内未受到伤害，只会失去<color style='color:#f29e38;'> 1 </color>层【<u class='infou'>会心</u>】。",
    effects: [60000004],
    need: {
      '120': 2,
      '124': 3,
    },
    er: 4,
    rel: [GainType.BeHit, GainType.Shield, GainType.CriticalBoost],
    type: BuffType.Equation,
  },
  {
    _id: 672410,
    path: 124,
    rarity: 4,
    name: '失忆者',
    desc: "角色对冻结状态下的敌方目标造成伤害时， 每层【<u class='infou'>会心</u>】额外使暴击率提高<color style='color:#f29e38;'> 4% </color>，暴击伤害提高<color style='color:#f29e38;'> 30% </color>。",
    effects: [60000004],
    need: {
      '121': 2,
      '124': 3,
    },
    er: 4,
    rel: [
      GainType.HitFrozenUnit,
      GainType.Freeze,
      GainType.CRIT,
      GainType.CRITDMG,
    ],
    type: BuffType.Equation,
  },
  {
    _id: 672430,
    path: 124,
    rarity: 4,
    name: '和平主义者',
    desc: "角色回合开始时，每有1层【<u class='infou'>会心</u>】，回复等同于生命上限<color style='color:#f29e38;'> 5% </color>的生命值，队友回复等同于生命上限<color style='color:#f29e38;'> 2% </color>的生命值。",
    effects: [60000004],
    need: {
      '123': 2,
      '124': 3,
    },
    er: 4,
    rel: [GainType.CriticalBoost, GainType.Healing],
    type: BuffType.Equation,
  },
  {
    _id: 672520,
    path: 125,
    rarity: 4,
    name: '焦土行者',
    desc: "角色拥有【<u class='infou'>战意</u>】时，全属性抗性穿透提高<color style='color:#f29e38;'> 15% </color>，每有1层【<u class='infou'>战意</u>】，击破特攻提高<color style='color:#f29e38;'> 3% </color>。",
    effects: [60000005],
    need: {
      '122': 2,
      '125': 3,
    },
    er: 4,
    rel: [GainType.Grit, GainType.ResistStrike],
    type: BuffType.Equation,
  },
  {
    _id: 672530,
    path: 125,
    rarity: 4,
    name: '纵火士',
    desc: "每层【<u class='infou'>战意</u>】使角色的生命上限提高<color style='color:#f29e38;'> 6% </color>，但可回复的生命上限降低该数值的<color style='color:#f29e38;'> 80% </color>。",
    effects: [60000005],
    need: {
      '123': 2,
      '125': 3,
    },
    er: 4,
    rel: [GainType.Grit, GainType.HEAL],
    type: BuffType.Equation,
  },
  {
    _id: 672580,
    path: 125,
    rarity: 4,
    name: '火匠',
    desc: "角色造成的终结技伤害提高<color style='color:#f29e38;'> 60% </color>。角色每损失1%生命值，为【<u class='infou'>罐中脑</u>】充能<color style='color:#f29e38;'> 0.5% </color>。",
    effects: [61000044],
    need: {
      '125': 3,
      '128': 2,
    },
    er: 4,
    rel: [GainType.UltimateAtk, GainType.HEAL, GainType.Brain_in_a_Vat_Charge],
    type: BuffType.Equation,
  },
  {
    _id: 672620,
    path: 126,
    rarity: 4,
    name: '糖果骑士',
    desc: "角色造成的【<u class='infou'>回味</u>】伤害，可以无视弱点属性削减敌方目标<color style='color:#f29e38;'> 2.5 </color>点韧性值，单次攻击内对每名敌方目标最多触发<color style='color:#f29e38;'> 7 </color>次该效果。",
    effects: [60000003],
    need: {
      '122': 2,
      '126': 3,
    },
    er: 4,
    rel: [GainType.Aftertaste, GainType.FollowUpAtk, GainType.CutToughness],
    type: BuffType.Equation,
  },
  {
    _id: 672630,
    path: 126,
    rarity: 4,
    name: '漂流马戏团',
    desc: "角色每造成1次【<u class='infou'>回味</u>】伤害，使生命值上限提高<color style='color:#f29e38;'> 5% </color>，最多叠加<color style='color:#f29e38;'> 15 </color>层，持续<color style='color:#f29e38;'> 1 </color>回合。",
    effects: [60000003],
    need: {
      '123': 2,
      '126': 3,
    },
    er: 4,
    rel: [GainType.Aftertaste, GainType.FollowUpAtk, GainType.HEAL],
    type: BuffType.Equation,
  },
  {
    _id: 672670,
    path: 126,
    rarity: 4,
    name: '气球商',
    desc: "角色造成的追加攻击伤害提高<color style='color:#f29e38;'> 50% </color>，发动追加攻击后，有<color style='color:#f29e38;'> 100% </color>固定概率恢复1个战技点。",
    effects: [],
    need: {
      '126': 3,
      '127': 2,
    },
    er: 4,
    rel: [GainType.FollowUpAtk, GainType.DMG_Gain, GainType.Point],
    type: BuffType.Equation,
  },
  {
    _id: 672710,
    path: 127,
    rarity: 4,
    name: '幻螟蠧役',
    desc: "敌方目标受到的【<u class='infou'>孢子</u>】伤害提高<color style='color:#f29e38;'> 35% </color>，每有1层【<u class='infou'>孢子</u>】，效果抵抗降低<color style='color:#f29e38;'> 10% </color>。",
    effects: [60000017],
    need: {
      '121': 2,
      '127': 3,
    },
    er: 4,
    rel: [GainType.SporeDmg, GainType.MON_RESISTANCE_DEC],
    type: BuffType.Equation,
  },
  {
    _id: 672720,
    path: 127,
    rarity: 4,
    name: '残照蠧役',
    desc: "【<u class='infou'>孢子</u>】的伤害倍率提高原倍率的<color style='color:#f29e38;'> 60% </color>，孢子爆裂时，敌方目标每有1个负面效果，伤害倍率额外提高原倍率的<color style='color:#f29e38;'> 3% </color>。",
    effects: [60000017],
    need: {
      '122': 2,
      '127': 3,
    },
    er: 4,
    rel: [GainType.SporeDmg, GainType.MON_in_NEG_EFFECT],
    type: BuffType.Equation,
  },
  {
    _id: 672750,
    path: 127,
    rarity: 4,
    name: '碎星蠧役',
    desc: "角色造成的普攻伤害提高<color style='color:#f29e38;'> 80% </color>，施放普攻时，若生命值百分比大于等于<color style='color:#f29e38;'> 50% </color>，则消耗等同于生命上限<color style='color:#f29e38;'> 5% </color>的生命值并额外恢复1点战技点。",
    effects: [],
    need: {
      '125': 2,
      '127': 3,
    },
    er: 4,
    rel: [GainType.NomralAtk, GainType.HEAL, GainType.Point],
    type: BuffType.Equation,
  },
  {
    _id: 672840,
    path: 128,
    rarity: 4,
    name: '执笔人',
    desc: "角色施放攻击造成终结技伤害后，每击中一名敌方目标，都会对生命上限最高的敌方目标造成等同于角色<color style='color:#f29e38;'> 100% </color>攻击力的终结技伤害。",
    effects: [],
    need: {
      '124': 2,
      '128': 3,
    },
    er: 4,
    rel: [GainType.UltimateAtk, GainType.AdditionalDmg],
    type: BuffType.Equation,
  },
  {
    _id: 672860,
    path: 128,
    rarity: 4,
    name: '修补匠',
    desc: "角色造成的终结技伤害提高<color style='color:#f29e38;'> 60% </color>。发动追加攻击后，每击中1名敌方目标，都会使下次施放终结技无视敌方目标<color style='color:#f29e38;'> 5% </color>的防御力，最多叠加<color style='color:#f29e38;'> 5 </color>次。",
    effects: [],
    need: {
      '126': 2,
      '128': 3,
    },
    er: 4,
    rel: [GainType.UltimateAtk, GainType.FollowUpAtk, GainType.MON_DEF_DEC],
    type: BuffType.Equation,
  },
  {
    _id: 672870,
    path: 128,
    rarity: 4,
    name: '科尔奇人',
    desc: "角色每消耗1个战技点，造成的终结技伤害提高<color style='color:#f29e38;'> 65% </color>，最多提高<color style='color:#f29e38;'> 130% </color>，持续至施放终结技后。",
    effects: [],
    need: {
      '127': 2,
      '128': 3,
    },
    er: 4,
    rel: [GainType.UltimateAtk, GainType.Point],
    type: BuffType.Equation,
  },
  {
    _id: 672030,
    path: 120,
    rarity: 4,
    name: '行星净化工',
    desc: "角色获得的护盾量提高<color style='color:#f29e38;'> 30% </color>，失去护盾后，回复等同于生命上限<color style='color:#f29e38;'> 25% </color>的生命值。",
    effects: [],
    need: {
      '120': 3,
      '123': 2,
    },
    er: 4,
    rel: [GainType.Shield, GainType.Healing],
    type: BuffType.Equation,
  },
  {
    _id: 672140,
    path: 121,
    rarity: 4,
    name: '意识审查员',
    desc: "角色攻击当前生命值百分比小于<color style='color:#f29e38;'> 50% </color>的非精英敌方目标后，有<color style='color:#f29e38;'> 150% </color>基础概率使其陷入【<u class='infou'>离神</u>】状态，持续<color style='color:#f29e38;'> 1 </color>回合，并对该目标造成等同于其当前生命值的固定数值的暴击伤害。",
    effects: [60000002],
    need: {
      '121': 3,
      '124': 2,
    },
    er: 4,
    rel: [
      GainType.DissociationDmg,
      GainType.Freeze,
      GainType.CRITDMG,
      GainType.CRIT,
    ],
    type: BuffType.Equation,
  },
  {
    _id: 672250,
    path: 122,
    rarity: 4,
    name: '救难者',
    desc: "敌方目标在攻击中受到削韧伤害后，有<color style='color:#f29e38;'> 100% </color>基础概率陷入灼烧状态，回合开始时受到<color style='color:#f29e38;'> 120% </color><u class='infou'>基础伤害</u>的火属性伤害，持续<color style='color:#f29e38;'> 2 </color>回合。",
    effects: [61000500],
    need: {
      '122': 3,
      '125': 2,
    },
    er: 4,
    rel: [GainType.CutToughness, GainType.DoT, GainType.MON_in_NEG_EFFECT],
    type: BuffType.Equation,
  },
  {
    _id: 672371,
    path: 123,
    rarity: 4,
    name: '负子树',
    desc: "角色治疗量提高<color style='color:#f29e38;'> 30% </color>，为我方目标提供治疗后，使随机敌方目标获得<color style='color:#f29e38;'> 2 </color>个【<u class='infou'>孢子</u>】。",
    effects: [60000017],
    need: {
      '123': 3,
      '127': 2,
    },
    er: 4,
    rel: [GainType.Healing, GainType.SporeCnt],
    type: BuffType.Equation,
  },
  {
    _id: 672480,
    path: 124,
    rarity: 4,
    name: '预演家',
    desc: "每层【<u class='infou'>会心</u>】额外使暴击伤害提高<color style='color:#f29e38;'> 8% </color>，角色施放终结技时继承并获得<color style='color:#f29e38;'> 2 </color>层【<u class='infou'>会心</u>】。",
    effects: [60000004],
    need: {
      '124': 3,
      '128': 2,
    },
    er: 4,
    rel: [GainType.CriticalBoost, GainType.CRITDMG, GainType.UltimateAtk],
    type: BuffType.Equation,
  },
  {
    _id: 672510,
    path: 125,
    rarity: 4,
    name: '掘墓人',
    desc: "角色击破敌方目标后，有<color style='color:#f29e38;'> 120% </color>的基础概率使其陷入冻结状态，持续<color style='color:#f29e38;'> 1 </color>回合，若该敌方目标已陷入冻结状态，则对其额外造成一次等同于本次击破伤害<color style='color:#f29e38;'> 200% </color>的击破伤害。",
    effects: [],
    need: {
      '121': 2,
      '125': 3,
    },
    er: 4,
    rel: [
      GainType.Break,
      GainType.Freeze,
      GainType.BreakDmg,
      GainType.HitFrozenUnit,
    ],
    type: BuffType.Equation,
  },
  {
    _id: 672600,
    path: 126,
    rarity: 4,
    name: '战场魔术师',
    desc: "角色攻击后，本次攻击每造成一次【<u class='infou'>回味</u>】伤害，获得等同于生命上限<color style='color:#f29e38;'> 3% </color>的护盾，不超过生命上限的<color style='color:#f29e38;'> 36% </color>，护盾持续<color style='color:#f29e38;'> 1 </color>回合。",
    effects: [60000003],
    need: {
      '120': 2,
      '126': 3,
    },
    er: 4,
    rel: [GainType.FollowUpAtk, GainType.Aftertaste, GainType.Shield],
    type: BuffType.Equation,
  },
  {
    _id: 672721,
    path: 127,
    rarity: 4,
    name: '无争蠧役',
    desc: "角色每次消耗战技点或战技点溢出时，有<color style='color:#f29e38;'> 150% </color>的基础概率使随机敌方目标陷入随机负面效果，持续<color style='color:#f29e38;'> 2 </color>回合，随机负面效果包括：造成的伤害降低<color style='color:#f29e38;'> 15% </color>，效果抵抗降低<color style='color:#f29e38;'> 20% </color>，效果命中降低<color style='color:#f29e38;'> 30% </color>。",
    effects: [],
    need: {
      '122': 2,
      '127': 3,
    },
    er: 4,
    rel: [
      GainType.Point,
      GainType.MON_in_NEG_EFFECT,
      GainType.MON_DMG_DEC,
      GainType.MON_RESISTANCE_DEC,
    ],
    type: BuffType.Equation,
  },
  {
    _id: 672850,
    path: 128,
    rarity: 4,
    name: '摘星客',
    desc: "角色施放终结技时，获得<color style='color:#f29e38;'> 3 </color>层【<u class='infou'>战意</u>】，并使速度提高<color style='color:#f29e38;'> 25% </color>，攻击力提高<color style='color:#f29e38;'> 20% </color>，持续<color style='color:#f29e38;'> 2 </color>回合。",
    effects: [60000005],
    need: {
      '125': 2,
      '128': 3,
    },
    er: 4,
    rel: [GainType.UltimateAtk, GainType.Grit, GainType.SPD, GainType.ATK],
    type: BuffType.Equation,
  },
  {
    _id: 672020,
    path: 120,
    rarity: 4,
    name: '守陵人',
    desc: "角色效果抵抗提高<color style='color:#f29e38;'> 25% </color>，造成的【<u class='infou'>反震</u>】伤害提高<color style='color:#f29e38;'> 50% </color>，抵抗受到的负面效果时，对目标造成等同于当前护盾量<color style='color:#f29e38;'> 400% </color>的反震伤害。",
    effects: [70000102],
    need: {
      '120': 3,
      '122': 2,
    },
    er: 4,
    type: BuffType.Equation,
    rel: [GainType.RESIST, GainType.QuakeDmg, GainType.Shield],
  },
  {
    _id: 672540,
    path: 125,
    rarity: 4,
    name: '溯沙客',
    desc: "角色弱点击破效率提高<color style='color:#f29e38;'> 20% </color>，击破敌方目标弱点后，速度提高<color style='color:#f29e38;'> 25% </color>，持续<color style='color:#f29e38;'> 3 </color>回合。",
    effects: [],
    need: {
      '124': 2,
      '125': 3,
    },
    er: 4,
    type: BuffType.Equation,
    rel: [GainType.BreakEfficiency, GainType.Break, GainType.SPD],
  },
  {
    _id: 672810,
    path: 128,
    rarity: 4,
    name: '烛墨校验员',
    desc: "角色施放终结技时，每消耗<color style='color:#f29e38;'> 10 </color>点能量，使攻击力提高<color style='color:#f29e38;'> 4% </color>，效果命中提高<color style='color:#f29e38;'> 2% </color>，最多叠加<color style='color:#f29e38;'> 20 </color>层，持续<color style='color:#f29e38;'> 2 </color>回合，每次施放终结技时至少视为消耗了<color style='color:#f29e38;'> 80 </color>点能量。",
    effects: [],
    need: {
      '121': 2,
      '128': 3,
    },
    er: 4,
    type: BuffType.Equation,
    rel: [GainType.UltimateAtk, GainType.ATK, GainType.EFFECT_HIT_RATE],
  },
  {
    _id: 672700,
    path: 127,
    rarity: 4,
    name: '幻螟残嗣',
    desc: "角色造成的普攻、战技伤害提高<color style='color:#f29e38;'> 60% </color>。【<u class='infou'>孢子</u>】爆裂时造成的伤害提高，提高数值等同于我方全体护盾总量的<color style='color:#f29e38;'> 100% </color>。",
    effects: [60000017],
    need: {
      '120': 2,
      '127': 3,
    },
    er: 4,
    type: BuffType.Equation,
    rel: [
      GainType.NomralAtk,
      GainType.SkillAtk,
      GainType.SporeDmg,
      GainType.Shield,
    ],
  },
  {
    _id: 672230,
    path: 122,
    rarity: 4,
    name: '混沌医师',
    desc: "角色造成的持续伤害提高<color style='color:#f29e38;'> 50% </color>。敌方目标进入战斗时，陷入【觉察】状态。回合开始时，受到等同于我方全体生命上限之和的<color style='color:#f29e38;'> 300% </color>火属性持续伤害。",
    effects: [],
    need: {
      '122': 3,
      '123': 2,
    },
    er: 4,
    type: BuffType.Equation,
    rel: [GainType.DoT_By_Char, GainType.HEAL],
  },
  {
    _id: 672470,
    path: 124,
    rarity: 4,
    name: '离巢浪人',
    desc: "角色造成的普攻、战技暴击伤害提高<color style='color:#f29e38;'> 100% </color>。溢出的【<u class='infou'>会心</u>】层数会在角色回合开始时被重新获得。",
    effects: [60000004],
    need: {
      '124': 3,
      '127': 2,
    },
    er: 4,
    type: BuffType.Equation,
    rel: [
      GainType.NomralAtk,
      GainType.SkillAtk,
      GainType.CRIT,
      GainType.CRITDMG,
      GainType.CriticalBoost,
    ],
  },
  {
    _id: 672150,
    path: 121,
    rarity: 4,
    name: '洁净者',
    desc: "敌方目标当前生命值大于生命上限的<color style='color:#f29e38;'> 60% </color>时，陷入冻结状态的持续时间提高1回合。冻结状态下的敌方目标受到的伤害提高<color style='color:#f29e38;'> 30% </color>。",
    effects: [],
    need: {
      '121': 3,
      '125': 2,
    },
    er: 4,
    type: BuffType.Equation,
    rel: [GainType.Freeze, GainType.MON_VUL_INC],
  },
  {
    _id: 672360,
    path: 123,
    rarity: 4,
    name: '奇谈怪医',
    desc: "【<u class='infou'>珠露</u>】上限提高<color style='color:#f29e38;'> 50% </color>，角色发动追加攻击后，使当前生命值百分比最低的角色回复等同于自身生命上限<color style='color:#f29e38;'> 10% </color>的生命值。",
    effects: [60000013],
    need: {
      '123': 3,
      '126': 2,
    },
    er: 4,
    type: BuffType.Equation,
    rel: [
      GainType.DewDropDmg,
      GainType.DewDropCharge,
      GainType.FollowUpAtk,
      GainType.Healing,
    ],
  },
  {
    _id: 672680,
    path: 126,
    rarity: 4,
    name: '造物歌唱家',
    desc: "角色施放终结技后，使下次施放攻击后，对攻击目标造成<color style='color:#f29e38;'> 2 </color>次等同于角色攻击力<color style='color:#f29e38;'> 150% </color>的【<u class='infou'>回味</u>】伤害。",
    effects: [60000003],
    need: {
      '126': 3,
      '128': 2,
    },
    er: 4,
    type: BuffType.Equation,
    rel: [GainType.UltimateAtk, GainType.Aftertaste, GainType.FollowUpAtk],
  },
  {
    _id: 615020,
    path: 120,
    rarity: 3,
    name: '筑城者',
    desc: "可消耗 100 点能量施放技能与命途「存护」产生临界回响，为我方全体提供能够抵消等同于各自生命上限<color style='color:#f29e38;'> 80% </color>伤害的护盾，持续<color style='color:#f29e38;'> 2 </color>回合，并基于我方全体的护盾总量，对敌方全体造成物理属性伤害。",
    effects: [],
    need: {
      '120': 16,
    },
    type: BuffType.Equation,
    rel: [GainType.Shield],
    er: BlessingEquationEr.Critical,
  },
  {
    _id: 615120,
    path: 121,
    rarity: 3,
    name: '流光忆庭',
    desc: "可消耗 100 点能量施放技能与命途「记忆」产生临界回响，对敌方全体造成冰属性伤害，大概率使敌方全体陷入冻结状态，持续<color style='color:#f29e38;'> 2 </color>回合。",
    effects: [],
    need: {
      '121': 16,
    },
    type: BuffType.Equation,
    rel: [GainType.Freeze],
    er: BlessingEquationEr.Critical,
  },
  {
    _id: 615220,
    path: 122,
    rarity: 3,
    name: '自灭者',
    desc: "可消耗 100 点能量施放技能与命途「虚无」产生临界回响，使敌方全体陷入灼烧、触电、裂伤和2层风化状态，持续<color style='color:#f29e38;'> 3 </color>回合。受到角色攻击后上述持续伤害立即产生相当于原伤害<color style='color:#f29e38;'> 25% </color>的伤害。",
    effects: [],
    need: {
      '122': 16,
    },
    type: BuffType.Equation,
    rel: [GainType.DoT, GainType.DotDetonate],
    er: BlessingEquationEr.Critical,
  },
  {
    _id: 615320,
    path: 123,
    rarity: 3,
    name: '求药使',
    desc: "可消耗 100 点能量施放技能与命途「丰饶」产生临界回响，为我方全体回复等同于该角色<color style='color:#f29e38;'> 100% </color>生命上限的生命值并解除所有负面效果。并提供【<u class='infou'>谛苦除灭</u>】状态，持续<color style='color:#f29e38;'> 3 </color>回合。",
    effects: [61000301],
    need: {
      '123': 16,
    },
    type: BuffType.Equation,
    rel: [GainType.Healing, GainType.DebuffRemove],
    er: BlessingEquationEr.Critical,
  },
  {
    _id: 615420,
    path: 124,
    rarity: 3,
    name: '巡海游侠',
    desc: "可消耗 100 点能量施放技能与命途「巡猎」产生临界回响，对敌方全体造成风属性伤害，并使我方全体行动提前<color style='color:#f29e38;'> 100% </color>，能量上限为 200 。",
    effects: [],
    need: {
      '124': 16,
    },
    type: BuffType.Equation,
    rel: [GainType.SuccessiveAction, GainType.CriticalBoost],
    er: BlessingEquationEr.Critical,
  },
  {
    _id: 615520,
    path: 125,
    rarity: 3,
    name: '反物质军团',
    desc: "可消耗 100 点能量施放技能与命途「毁灭」产生临界回响，对敌方全体造成火属性伤害，任意角色受到攻击或消耗生命值，都会使下次施放回响时额外增加1段伤害，最多增加<color style='color:#f29e38;'> 20 </color>段。",
    effects: [],
    need: {
      '125': 16,
    },
    type: BuffType.Equation,
    rel: [GainType.BeHit, GainType.ConsumeHp, GainType.AdditionalDmg],
    er: BlessingEquationEr.Critical,
  },
  {
    _id: 615620,
    path: 126,
    rarity: 3,
    name: '假面愚者',
    desc: "可消耗 100 点能量施放技能与命途「欢愉」产生临界回响，对敌方全体造成<color style='color:#f29e38;'> 5 </color>~<color style='color:#f29e38;'> 10 </color>次随机属性的追加攻击伤害，并使我方全体的普攻/战技/终结技伤害被视为追加攻击伤害，持续<color style='color:#f29e38;'> 1 </color>回合。",
    effects: [],
    need: {
      '126': 16,
    },
    type: BuffType.Equation,
    rel: [GainType.Aftertaste, GainType.FollowUpAtk],
    er: BlessingEquationEr.Critical,
  },
  {
    _id: 615720,
    path: 127,
    rarity: 3,
    name: '孳孽王虫',
    desc: "可消耗 100 点能量施放技能与命途「繁育」产生临界回响，使指定我方单体立即行动，恢复<color style='color:#f29e38;'> 5 </color>个战技点，并获得【<u class='infou'>羽化</u>】效果，任意敌方单位被持有【<u class='infou'>羽化</u>】效果的角色消灭后，临界方程恢复<color style='color:#f29e38;'> 50 </color>点能量，能量上限为 200 。",
    effects: [61000302],
    need: {
      '127': 16,
    },
    type: BuffType.Equation,
    rel: [GainType.SuccessiveAction, GainType.Point],
    er: BlessingEquationEr.Critical,
  },
  {
    _id: 615820,
    path: 128,
    rarity: 3,
    name: '星空生态学派',
    desc: "可消耗 100 点能量施放技能与命途「智识」产生临界回响，对敌方全体造成少量虚数属性伤害，并将生命上限最高的敌方目标与其他敌方目标连接，使敌方全体陷入【<u class='infou'>中枢链接</u>】状态，并为我方全体恢复等同于能量上限<color style='color:#f29e38;'> 50% </color>的能量。",
    effects: [61000303],
    need: {
      '128': 16,
    },
    type: BuffType.Equation,
    rel: [GainType.ENERGY_Charge, GainType.DamageSpread],
    er: BlessingEquationEr.Critical,
  },
])

equations.forEach((e) => {
  const paths = Object.keys(e.need).map((i) => Number(i))
  e.rel.push(e.path as number as GainType, ...paths.filter((i) => i !== e.path))
})

export { equations as EQUATIONS }
