import { BuffType, type Blessing } from '@/libs/du/types'

const blessings: Blessing[] = [
  {
    _id: 616130,
    Path: 121,
    Type: BuffType.Blessing,
    rel: [],
    Rarity: 3,
    Icon: '/IconRogueMemory03.webp',
    Name: '未曾出错的直觉',
    Desc: [
      "角色行动时，使自身与忆灵获得<color style='color:#f29e38;'> 1 </color>层【<u class='infou'>执念</u>】，忆灵行动时，使自身与忆师获得<color style='color:#f29e38;'> 1 </color>层【<u class='infou'>执念</u>】。",
      "角色行动时，使自身与忆灵获得<color style='color:#f29e38;'> 1 </color>层【<u class='infou'>执念</u>】，忆灵行动时，使自身与忆师获得<color style='color:#f29e38;'> 2 </color>层【<u class='infou'>执念</u>】。",
    ],
    Effects: [61000049],
  },
  {
    _id: 616131,
    Path: 121,
    Type: BuffType.Blessing,
    rel: [],
    Rarity: 3,
    Icon: '/IconRogueMemory01.webp',
    Name: '历久弥新的回忆',
    Desc: [
      "我方目标施放攻击后，根据我方【<u class='infou'>执念</u>】总层数，对攻击目标造成每层<color style='color:#f29e38;'> 1% </color>攻击力的附加伤害。",
      "我方目标施放攻击后，根据我方【<u class='infou'>执念</u>】总层数，对攻击目标造成每层<color style='color:#f29e38;'> 1.5% </color>攻击力的附加伤害。",
    ],
    Effects: [61000049],
  },
  {
    _id: 616132,
    Path: 121,
    Type: BuffType.Blessing,
    rel: [],
    Rarity: 3,
    Icon: '/IconRogueMemory03.webp',
    Name: '恒常平和的梦境',
    Desc: [
      '我方目标进入战斗/忆灵被召唤后，在首次回合结束后获得1个额外回合。',
      "我方目标进入战斗/忆灵被召唤后，在首次回合结束后获得1个额外回合，额外回合内造成的伤害提高<color style='color:#f29e38;'> 80% </color>。",
    ],
    Effects: [],
  },
  {
    _id: 616140,
    Path: 121,
    Type: BuffType.Blessing,
    rel: [],
    Rarity: 2,
    Icon: '/IconRogueMemory03.webp',
    Name: '领悟：编织云朵',
    Desc: [
      "我方目标受到攻击时，获得<color style='color:#f29e38;'> 2 </color>层【<u class='infou'>执念</u>】。",
      "我方目标受到攻击时，获得<color style='color:#f29e38;'> 3 </color>层【<u class='infou'>执念</u>】。",
    ],
    Effects: [61000049],
  },
  {
    _id: 616141,
    Path: 121,
    Type: BuffType.Blessing,
    rel: [],
    Rarity: 2,
    Icon: '/IconRogueMemory03.webp',
    Name: '领悟：缝合山峦',
    Desc: [
      "我方目标消灭敌方目标后，为我方全体提供<color style='color:#f29e38;'> 3 </color>层【<u class='infou'>执念</u>】。",
      "我方目标消灭敌方目标后，为我方全体提供<color style='color:#f29e38;'> 4 </color>层【<u class='infou'>执念</u>】。",
    ],
    Effects: [61000049],
  },
  {
    _id: 616142,
    Path: 121,
    Type: BuffType.Blessing,
    rel: [],
    Rarity: 2,
    Icon: '/IconRogueMemory03.webp',
    Name: '领悟：装订波浪',
    Desc: [
      "我方目标进入战斗/忆灵被召唤后，获得<color style='color:#f29e38;'> 6 </color>层【<u class='infou'>执念</u>】。",
      "我方目标进入战斗/忆灵被召唤后，获得<color style='color:#f29e38;'> 9 </color>层【<u class='infou'>执念</u>】。",
    ],
    Effects: [61000049],
  },
  {
    _id: 616143,
    Path: 121,
    Type: BuffType.Blessing,
    rel: [],
    Rarity: 2,
    Icon: '/IconRogueMemory01.webp',
    Name: '领悟：浅海悼词',
    Desc: [
      "每层【<u class='infou'>执念</u>】额外使造成的伤害提高<color style='color:#f29e38;'> 0.3% </color>。",
      "每层【<u class='infou'>执念</u>】额外使造成的伤害提高<color style='color:#f29e38;'> 0.45% </color>。",
    ],
    Effects: [61000049],
  },
  {
    _id: 616144,
    Path: 121,
    Type: BuffType.Blessing,
    rel: [],
    Rarity: 2,
    Icon: '/IconRogueMemory03.webp',
    Name: '领悟：深渊礼赞',
    Desc: [
      "角色的【<u class='infou'>执念</u>】上限提高<color style='color:#f29e38;'> 4 </color>层。",
      "角色的【<u class='infou'>执念</u>】上限提高<color style='color:#f29e38;'> 6 </color>层。",
    ],
    Effects: [61000049],
  },
  {
    _id: 616145,
    Path: 121,
    Type: BuffType.Blessing,
    rel: [],
    Rarity: 2,
    Icon: '/IconRogueMemory04.webp',
    Name: '领悟：精炼晨曦',
    Desc: [
      "敌方目标每次受到不同我方目标攻击时，受到的伤害提高<color style='color:#f29e38;'> 4% </color>，最多叠加<color style='color:#f29e38;'> 6 </color>层，持续至回合结束时。",
      "敌方目标每次受到不同我方目标攻击时，受到的伤害提高<color style='color:#f29e38;'> 6% </color>，最多叠加<color style='color:#f29e38;'> 6 </color>层，持续至回合结束时。",
    ],
    Effects: [],
  },
  {
    _id: 616146,
    Path: 121,
    Type: BuffType.Blessing,
    rel: [],
    Rarity: 2,
    Icon: '/IconRogueMemory04.webp',
    Name: '领悟：溶解夕阳',
    Desc: [
      "敌方目标每次受到不同我方目标攻击时，造成的伤害降低<color style='color:#f29e38;'> 3% </color>，最多叠加<color style='color:#f29e38;'> 6 </color>层，持续至回合结束时。",
      "敌方目标每次受到不同我方目标攻击时，造成的伤害降低<color style='color:#f29e38;'> 4% </color>，最多叠加<color style='color:#f29e38;'> 6 </color>层，持续至回合结束时。",
    ],
    Effects: [],
  },
  {
    _id: 616150,
    Path: 121,
    Type: BuffType.Blessing,
    rel: [],
    Rarity: 1,
    Icon: '/IconRogueMemory01.webp',
    Name: '感知：锋刃的温度',
    Desc: [
      "我方全体目标攻击力提高<color style='color:#f29e38;'> 18% </color>。",
      "我方全体目标攻击力提高<color style='color:#f29e38;'> 27% </color>。",
    ],
    Effects: [],
  },
  {
    _id: 616151,
    Path: 121,
    Type: BuffType.Blessing,
    rel: [],
    Rarity: 1,
    Icon: '/IconRogueMemory01.webp',
    Name: '感知：兽爪的形状',
    Desc: [
      "我方全体目标造成的伤害提高<color style='color:#f29e38;'> 12% </color>。",
      "我方全体目标造成的伤害提高<color style='color:#f29e38;'> 18% </color>。",
    ],
    Effects: [],
  },
  {
    _id: 616152,
    Path: 121,
    Type: BuffType.Blessing,
    rel: [],
    Rarity: 1,
    Icon: '/IconRogueMemory02.webp',
    Name: '感知：螺壳的纹理',
    Desc: [
      "我方全体目标防御力提高<color style='color:#f29e38;'> 16% </color>。",
      "我方全体目标防御力提高<color style='color:#f29e38;'> 24% </color>。",
    ],
    Effects: [],
  },
  {
    _id: 616153,
    Path: 121,
    Type: BuffType.Blessing,
    rel: [],
    Rarity: 1,
    Icon: '/IconRogueMemory01.webp',
    Name: '感知：季风的故事',
    Desc: [
      "我方全体目标造成的伤害提高<color style='color:#f29e38;'> 8% </color>，忆灵额外提高<color style='color:#f29e38;'> 8% </color>。",
      "我方全体目标造成的伤害提高<color style='color:#f29e38;'> 12% </color>，忆灵额外提高<color style='color:#f29e38;'> 12% </color>。",
    ],
    Effects: [],
  },
  {
    _id: 616154,
    Path: 121,
    Type: BuffType.Blessing,
    rel: [],
    Rarity: 1,
    Icon: '/IconRogueMemory02.webp',
    Name: '感知：岩石的故事',
    Desc: [
      "我方全体目标防御力提高<color style='color:#f29e38;'> 12% </color>，忆灵额外提高<color style='color:#f29e38;'> 12% </color>。",
      "我方全体目标防御力提高<color style='color:#f29e38;'> 18% </color>，忆灵额外提高<color style='color:#f29e38;'> 18% </color>。",
    ],
    Effects: [],
  },
  {
    _id: 616155,
    Path: 121,
    Type: BuffType.Blessing,
    rel: [],
    Rarity: 1,
    Icon: '/IconRogueMemory02.webp',
    Name: '感知：潮汐的故事',
    Desc: [
      "我方全体目标回复量提高<color style='color:#f29e38;'> 8% </color>，忆灵额外提高<color style='color:#f29e38;'> 8% </color>。",
      "我方全体目标回复量提高<color style='color:#f29e38;'> 12% </color>，忆灵额外提高<color style='color:#f29e38;'> 12% </color>。",
    ],
    Effects: [],
  },
  {
    _id: 616156,
    Path: 121,
    Type: BuffType.Blessing,
    rel: [],
    Rarity: 1,
    Icon: '/IconRogueMemory01.webp',
    Name: '感知：赤骨与红叶',
    Desc: [
      "忆灵行动后，我方全体目标暴击率提高<color style='color:#f29e38;'> 14% </color>，持续<color style='color:#f29e38;'> 2 </color>回合。",
      "忆灵行动后，我方全体目标暴击率提高<color style='color:#f29e38;'> 21% </color>，持续<color style='color:#f29e38;'> 2 </color>回合。",
    ],
    Effects: [],
  },
  {
    _id: 616157,
    Path: 121,
    Type: BuffType.Blessing,
    rel: [],
    Rarity: 1,
    Icon: '/IconRogueMemory01.webp',
    Name: '感知：白发与珍珠',
    Desc: [
      "忆灵行动后，我方全体目标暴击伤害提高<color style='color:#f29e38;'> 24% </color>，持续<color style='color:#f29e38;'> 2 </color>回合。",
      "忆灵行动后，我方全体目标暴击伤害提高<color style='color:#f29e38;'> 36% </color>，持续<color style='color:#f29e38;'> 2 </color>回合。",
    ],
    Effects: [],
  },
  {
    _id: 616230,
    Path: 122,
    Type: BuffType.Blessing,
    rel: [],
    Rarity: 3,
    Icon: '/IconRogueWarlock04.webp',
    Name: '不可言明共通体',
    Desc: [
      "敌方目标陷入持续伤害时，【<u class='infou'>呢喃</u>】获得等同于我方角色攻击力之和<color style='color:#f29e38;'> 10% </color>的充能值。",
      "敌方目标陷入持续伤害时，【<u class='infou'>呢喃</u>】获得等同于我方角色攻击力之和<color style='color:#f29e38;'> 15% </color>的充能值。",
    ],
    Effects: [61000050],
  },
  {
    _id: 616231,
    Path: 122,
    Type: BuffType.Blessing,
    rel: [],
    Rarity: 3,
    Icon: '/IconRogueWarlock01.webp',
    Name: '从存在到存在者',
    Desc: [
      "我方目标施放攻击后，以<color style='color:#f29e38;'> 12% </color>的比例触发1次【<u class='infou'>呢喃</u>】伤害。",
      "我方目标施放攻击后，以<color style='color:#f29e38;'> 18% </color>的比例触发1次【<u class='infou'>呢喃</u>】伤害。",
    ],
    Effects: [61000050],
  },
  {
    _id: 616232,
    Path: 122,
    Type: BuffType.Blessing,
    rel: [],
    Rarity: 3,
    Icon: '/IconRogueWarlock04.webp',
    Name: '来自别处的声音',
    Desc: [
      "敌方目标回合开始时额外触发1次持续伤害结算，使其当前承受的持续伤害状态立即产生相当于原伤害<color style='color:#f29e38;'> 90% </color>的伤害。",
      "敌方目标回合开始时额外触发1次持续伤害结算，使其当前承受的持续伤害状态立即产生相当于原伤害<color style='color:#f29e38;'> 135% </color>的伤害。",
    ],
    Effects: [],
  },
  {
    _id: 616240,
    Path: 122,
    Type: BuffType.Blessing,
    rel: [],
    Rarity: 2,
    Icon: '/IconRogueWarlock04.webp',
    Name: '启蒙与灭尽',
    Desc: [
      "敌方目标回合结束时，【<u class='infou'>呢喃</u>】获得等同于我方角色攻击力之和<color style='color:#f29e38;'> 16% </color>的充能值。",
      "敌方目标回合结束时，【<u class='infou'>呢喃</u>】获得等同于我方角色攻击力之和<color style='color:#f29e38;'> 24% </color>的充能值。",
    ],
    Effects: [61000050],
  },
  {
    _id: 616241,
    Path: 122,
    Type: BuffType.Blessing,
    rel: [],
    Rarity: 2,
    Icon: '/IconRogueWarlock04.webp',
    Name: '眼泪与圣徒',
    Desc: [
      "持有【<u class='infou'>呢喃</u>】的目标被消灭后，把充能值的<color style='color:#f29e38;'> 70% </color>平分给其他所有敌方目标",
      "持有【<u class='infou'>呢喃</u>】的目标被消灭后，把充能值的<color style='color:#f29e38;'> 100% </color>平分给其他所有敌方目标",
    ],
    Effects: [61000050],
  },
  {
    _id: 616242,
    Path: 122,
    Type: BuffType.Blessing,
    rel: [],
    Rarity: 2,
    Icon: '/IconRogueWarlock01.webp',
    Name: '失眠之礼赞',
    Desc: [
      "【<u class='infou'>呢喃</u>】伤害提高等同于原伤害倍率的<color style='color:#f29e38;'> 30% </color>。",
      "【<u class='infou'>呢喃</u>】伤害提高等同于原伤害倍率的<color style='color:#f29e38;'> 45% </color>。",
    ],
    Effects: [61000050],
  },
  {
    _id: 616243,
    Path: 122,
    Type: BuffType.Blessing,
    rel: [],
    Rarity: 2,
    Icon: '/IconRogueWarlock04.webp',
    Name: '在绝望之巅',
    Desc: [
      "【<u class='infou'>呢喃</u>】的清除阈值提高<color style='color:#f29e38;'> 50% </color>。",
      "【<u class='infou'>呢喃</u>】的清除阈值提高<color style='color:#f29e38;'> 75% </color>。",
    ],
    Effects: [61000050],
  },
  {
    _id: 616244,
    Path: 122,
    Type: BuffType.Blessing,
    rel: [],
    Rarity: 2,
    Icon: '/IconRogueWarlock04.webp',
    Name: '灾异的书写',
    Desc: [
      "【<u class='infou'>呢喃</u>】获得充能时的充能效率提高<color style='color:#f29e38;'> 20% </color>。",
      "【<u class='infou'>呢喃</u>】获得充能时的充能效率提高<color style='color:#f29e38;'> 30% </color>。",
    ],
    Effects: [61000050],
  },
  {
    _id: 616245,
    Path: 122,
    Type: BuffType.Blessing,
    rel: [],
    Rarity: 2,
    Icon: '/IconRogueWarlock02.webp',
    Name: '最后的言者',
    Desc: [
      "敌方目标每受到1次持续伤害，我方全体回复等同于各自<color style='color:#f29e38;'> 1% </color>生命上限的生命值。",
      "敌方目标每受到1次持续伤害，我方全体回复等同于各自<color style='color:#f29e38;'> 1.5% </color>生命上限的生命值。",
    ],
    Effects: [],
  },
  {
    _id: 616246,
    Path: 122,
    Type: BuffType.Blessing,
    rel: [],
    Rarity: 2,
    Icon: '/IconRogueWarlock04.webp',
    Name: '模棱两可',
    Desc: [
      "敌方目标每陷入1个持续伤害状态，造成的伤害降低<color style='color:#f29e38;'> 3% </color>，最多叠加<color style='color:#f29e38;'> 4 </color>层。",
      "敌方目标每陷入1个持续伤害状态，造成的伤害降低<color style='color:#f29e38;'> 4.5% </color>，最多叠加<color style='color:#f29e38;'> 4 </color>层。",
    ],
    Effects: [],
  },
  {
    _id: 616250,
    Path: 122,
    Type: BuffType.Blessing,
    rel: [],
    Rarity: 1,
    Icon: '/IconRogueWarlock01.webp',
    Name: '活的隐喻',
    Desc: [
      "我方目标造成的持续伤害提高<color style='color:#f29e38;'> 24% </color>。",
      "我方目标造成的持续伤害提高<color style='color:#f29e38;'> 36% </color>。",
    ],
    Effects: [],
  },
  {
    _id: 616251,
    Path: 122,
    Type: BuffType.Blessing,
    rel: [],
    Rarity: 1,
    Icon: '/IconRogueWarlock03.webp',
    Name: '无存在者',
    Desc: [
      "我方目标效果命中提高<color style='color:#f29e38;'> 24% </color>。",
      "我方目标效果命中提高<color style='color:#f29e38;'> 36% </color>。",
    ],
    Effects: [],
  },
  {
    _id: 616252,
    Path: 122,
    Type: BuffType.Blessing,
    rel: [],
    Rarity: 1,
    Icon: '/IconRogueWarlock04.webp',
    Name: '疾病致死',
    Desc: [
      "敌方目标效果抵抗降低<color style='color:#f29e38;'> 12% </color>。",
      "敌方目标效果抵抗降低<color style='color:#f29e38;'> 18% </color>。",
    ],
    Effects: [],
  },
  {
    _id: 616253,
    Path: 122,
    Type: BuffType.Blessing,
    rel: [],
    Rarity: 1,
    Icon: '/IconRogueWarlock04.webp',
    Name: '不敬神明',
    Desc: [
      "敌方目标受到的持续伤害提高<color style='color:#f29e38;'> 10% </color>。",
      "敌方目标受到的持续伤害提高<color style='color:#f29e38;'> 15% </color>。",
    ],
    Effects: [],
  },
  {
    _id: 616254,
    Path: 122,
    Type: BuffType.Blessing,
    rel: [],
    Rarity: 1,
    Icon: '/IconRogueWarlock01.webp',
    Name: '内在体验',
    Desc: [
      "我方目标施加负面状态后，攻击力提高<color style='color:#f29e38;'> 24% </color>，持续<color style='color:#f29e38;'> 2 </color>回合。",
      "我方目标施加负面状态后，攻击力提高<color style='color:#f29e38;'> 36% </color>，持续<color style='color:#f29e38;'> 2 </color>回合。",
    ],
    Effects: [],
  },
  {
    _id: 616255,
    Path: 122,
    Type: BuffType.Blessing,
    rel: [],
    Rarity: 1,
    Icon: '/IconRogueWarlock04.webp',
    Name: '黑色太阳',
    Desc: [
      "持有持续伤害状态的敌方目标，受到的伤害提高<color style='color:#f29e38;'> 8% </color>。",
      "持有持续伤害状态的敌方目标，受到的伤害提高<color style='color:#f29e38;'> 12% </color>。",
    ],
    Effects: [],
  },
  {
    _id: 616256,
    Path: 122,
    Type: BuffType.Blessing,
    rel: [],
    Rarity: 1,
    Icon: '/IconRogueWarlock03.webp',
    Name: '超越善恶',
    Desc: [
      "我方目标施加负面状态后，速度提高<color style='color:#f29e38;'> 12% </color>，持续<color style='color:#f29e38;'> 2 </color>回合。",
      "我方目标施加负面状态后，速度提高<color style='color:#f29e38;'> 18% </color>，持续<color style='color:#f29e38;'> 2 </color>回合。",
    ],
    Effects: [],
  },
  {
    _id: 616257,
    Path: 122,
    Type: BuffType.Blessing,
    rel: [],
    Rarity: 1,
    Icon: '/IconRogueWarlock02.webp',
    Name: '他者之死',
    Desc: [
      "敌方目标每受到1次持续伤害，我方随机目标恢复<color style='color:#f29e38;'> 1 </color>点能量，敌方目标每回合最多触发<color style='color:#f29e38;'> 20 </color>次该效果。",
      "敌方目标每受到1次持续伤害，我方随机目标恢复<color style='color:#f29e38;'> 1.5 </color>点能量，敌方目标每回合最多触发<color style='color:#f29e38;'> 20 </color>次该效果。",
    ],
    Effects: [],
  },
  {
    _id: 616430,
    Path: 124,
    Type: BuffType.Blessing,
    rel: [],
    Rarity: 3,
    Icon: '/IconRogueRogue03.webp',
    Name: '弹铗枕弓，世路干戈',
    Desc: [
      "我方目标消灭敌方目标后，行动提前 100% ，并在下个回合开始时获得<color style='color:#f29e38;'> 4 </color>层【<u class='infou'>会心</u>】效果。",
      "我方目标速度提高<color style='color:#f29e38;'> 15% </color>，消灭敌方目标后，行动提前 100% ，并在下个回合开始时获得<color style='color:#f29e38;'> 6 </color>层【<u class='infou'>会心</u>】效果。",
    ],
    Effects: [61000055],
  },
  {
    _id: 616431,
    Path: 124,
    Type: BuffType.Blessing,
    rel: [],
    Rarity: 3,
    Icon: '/IconRogueRogue01.webp',
    Name: '白羽奔湍，星海俄空',
    Desc: [
      "我方目标持有【<u class='infou'>会心</u>】时，暴击率提高<color style='color:#f29e38;'> 10% </color>，每溢出1%暴击率提高<color style='color:#f29e38;'> 2% </color>暴击伤害，暴击伤害最多提高<color style='color:#f29e38;'> 180% </color>。",
      "我方目标持有【<u class='infou'>会心</u>】时，暴击率提高<color style='color:#f29e38;'> 15% </color>，每溢出1%暴击率提高<color style='color:#f29e38;'> 2% </color>暴击伤害，暴击伤害最多提高<color style='color:#f29e38;'> 270% </color>。",
    ],
    Effects: [61000055],
  },
  {
    _id: 616432,
    Path: 124,
    Type: BuffType.Blessing,
    rel: [],
    Rarity: 3,
    Icon: '/IconRogueRogue03.webp',
    Name: '万乘之变，可堪试勇',
    Desc: [
      "我方目标击破敌方目标弱点后，自身行动提前 100% ，并使下次攻击造成的伤害提高<color style='color:#f29e38;'> 50% </color>。",
      "我方目标击破敌方目标弱点后，自身行动提前 100% ，并使造成的伤害提高<color style='color:#f29e38;'> 75% </color>，伤害提高效果最多叠加<color style='color:#f29e38;'> 2 </color>层，持续至受到攻击后。",
    ],
    Effects: [],
  },
  {
    _id: 616440,
    Path: 124,
    Type: BuffType.Blessing,
    rel: [],
    Rarity: 2,
    Icon: '/IconRogueRogue03.webp',
    Name: '连星入剑端',
    Desc: [
      "我方目标回合开始时，获得<color style='color:#f29e38;'> 1 </color>层【<u class='infou'>会心</u>】效果。",
      "我方目标回合开始时，获得<color style='color:#f29e38;'> 1 </color>层【<u class='infou'>会心</u>】效果。相同我方目标连续行动时，获得<color style='color:#f29e38;'> 1 </color>层【<u class='infou'>会心</u>】效果。",
    ],
    Effects: [61000055],
  },
  {
    _id: 616441,
    Path: 124,
    Type: BuffType.Blessing,
    rel: [],
    Rarity: 2,
    Icon: '/IconRogueRogue01.webp',
    Name: '楛矢何参差',
    Desc: [
      "每层【<u class='infou'>会心</u>】效果额外提高<color style='color:#f29e38;'> 4% </color>攻击力，当任意我方目标施放终结技时，可以继承【<u class='infou'>会心</u>】效果。",
      "每层【<u class='infou'>会心</u>】效果额外提高<color style='color:#f29e38;'> 6% </color>攻击力，当任意我方目标施放终结技时，可以继承【<u class='infou'>会心</u>】效果。",
    ],
    Effects: [61000055],
  },
  {
    _id: 616442,
    Path: 124,
    Type: BuffType.Blessing,
    rel: [],
    Rarity: 2,
    Icon: '/IconRogueRogue03.webp',
    Name: '腾骑纷往来',
    Desc: [
      "【<u class='infou'>会心</u>】上限提高<color style='color:#f29e38;'> 2 </color>层，受攻击后失去的【<u class='infou'>会心</u>】不超过<color style='color:#f29e38;'> 4 </color>层。",
      "【<u class='infou'>会心</u>】上限提高<color style='color:#f29e38;'> 4 </color>层，受攻击后失去的【<u class='infou'>会心</u>】不超过<color style='color:#f29e38;'> 4 </color>层。",
    ],
    Effects: [61000055],
  },
  {
    _id: 616443,
    Path: 124,
    Type: BuffType.Blessing,
    rel: [],
    Rarity: 2,
    Icon: '/IconRogueRogue02.webp',
    Name: '可使寸寸折',
    Desc: [
      "我方目标持有大于等于<color style='color:#f29e38;'> 4 </color>层【<u class='infou'>会心</u>】时，我方全体目标受到伤害降低<color style='color:#f29e38;'> 16% </color>。",
      "我方目标持有大于等于<color style='color:#f29e38;'> 4 </color>层【<u class='infou'>会心</u>】时，我方全体目标受到伤害降低<color style='color:#f29e38;'> 24% </color>。",
    ],
    Effects: [61000055],
  },
  {
    _id: 616444,
    Path: 124,
    Type: BuffType.Blessing,
    rel: [],
    Rarity: 2,
    Icon: '/IconRogueRogue03.webp',
    Name: '炯然耀电光',
    Desc: [
      "我方目标回合开始时，若持有大于等于<color style='color:#f29e38;'> 4 </color>层【<u class='infou'>会心</u>】，速度提高<color style='color:#f29e38;'> 20% </color>，持续<color style='color:#f29e38;'> 2 </color>回合。",
      "我方目标回合开始时，若持有大于等于<color style='color:#f29e38;'> 4 </color>层【<u class='infou'>会心</u>】，速度提高<color style='color:#f29e38;'> 30% </color>，持续<color style='color:#f29e38;'> 2 </color>回合。",
    ],
    Effects: [61000055],
  },
  {
    _id: 616445,
    Path: 124,
    Type: BuffType.Blessing,
    rel: [],
    Rarity: 2,
    Icon: '/IconRogueRogue03.webp',
    Name: '宿昔秉良弓',
    Desc: [
      "相同我方目标连续行动时，有<color style='color:#f29e38;'> 40% </color>的固定概率回复1点战技点。",
      "相同我方目标连续行动时，有<color style='color:#f29e38;'> 60% </color>的固定概率回复1点战技点。",
    ],
    Effects: [],
  },
  {
    _id: 616446,
    Path: 124,
    Type: BuffType.Blessing,
    rel: [],
    Rarity: 2,
    Icon: '/IconRogueRogue03.webp',
    Name: '激箭流星远',
    Desc: [
      "我方目标速度提高<color style='color:#f29e38;'> 5% </color>，全队每经过<color style='color:#f29e38;'> 10 </color>个回合后，当前我方目标行动提前 100% 。",
      "我方目标速度提高<color style='color:#f29e38;'> 15% </color>，全队每经过<color style='color:#f29e38;'> 10 </color>个回合后，当前我方目标行动提前 100% 。",
    ],
    Effects: [],
  },
  {
    _id: 616450,
    Path: 124,
    Type: BuffType.Blessing,
    rel: [],
    Rarity: 1,
    Icon: '/IconRogueRogue03.webp',
    Name: '排檠则正',
    Desc: [
      "我方目标速度提高<color style='color:#f29e38;'> 8% </color>。",
      "我方目标速度提高<color style='color:#f29e38;'> 12% </color>。",
    ],
    Effects: [],
  },
  {
    _id: 616451,
    Path: 124,
    Type: BuffType.Blessing,
    rel: [],
    Rarity: 1,
    Icon: '/IconRogueRogue01.webp',
    Name: '百夫决拾',
    Desc: [
      "我方目标暴击率提高<color style='color:#f29e38;'> 11% </color>。",
      "我方目标暴击率提高<color style='color:#f29e38;'> 16% </color>。",
    ],
    Effects: [],
  },
  {
    _id: 616452,
    Path: 124,
    Type: BuffType.Blessing,
    rel: [],
    Rarity: 1,
    Icon: '/IconRogueRogue01.webp',
    Name: '昭质既设',
    Desc: [
      "我方目标暴击伤害提高<color style='color:#f29e38;'> 20% </color>。",
      "我方目标暴击伤害提高<color style='color:#f29e38;'> 30% </color>。",
    ],
    Effects: [],
  },
  {
    _id: 616453,
    Path: 124,
    Type: BuffType.Blessing,
    rel: [],
    Rarity: 1,
    Icon: '/IconRogueRogue02.webp',
    Name: '秋月行天',
    Desc: [
      "消灭敌方目标后，为我方全体目标回复等同于生命值上限<color style='color:#f29e38;'> 30% </color>的生命值。",
      "消灭敌方目标后，为我方全体目标回复等同于生命值上限<color style='color:#f29e38;'> 45% </color>的生命值。",
    ],
    Effects: [],
  },
  {
    _id: 616454,
    Path: 124,
    Type: BuffType.Blessing,
    rel: [],
    Rarity: 1,
    Icon: '/IconRogueRogue01.webp',
    Name: '卷手一挃',
    Desc: [
      "消灭敌方目标后，我方全体攻击力提高<color style='color:#f29e38;'> 6% </color>，最多叠加<color style='color:#f29e38;'> 4 </color>次。",
      "消灭敌方目标后，我方全体攻击力提高<color style='color:#f29e38;'> 9% </color>，最多叠加<color style='color:#f29e38;'> 4 </color>次。",
    ],
    Effects: [],
  },
  {
    _id: 616455,
    Path: 124,
    Type: BuffType.Blessing,
    rel: [],
    Rarity: 1,
    Icon: '/IconRogueRogue03.webp',
    Name: '矢摧月支',
    Desc: [
      "我方目标回合结束时，行动提前<color style='color:#f29e38;'> 8% </color>。",
      "我方目标回合结束时，行动提前<color style='color:#f29e38;'> 12% </color>。",
    ],
    Effects: [],
  },
  {
    _id: 616456,
    Path: 124,
    Type: BuffType.Blessing,
    rel: [],
    Rarity: 1,
    Icon: '/IconRogueRogue03.webp',
    Name: '壁上雷鸣',
    Desc: [
      "我方目标回合开始时，恢复<color style='color:#f29e38;'> 4 </color>点能量。",
      "我方目标回合开始时，恢复<color style='color:#f29e38;'> 6 </color>点能量。",
    ],
    Effects: [],
  },
  {
    _id: 616457,
    Path: 124,
    Type: BuffType.Blessing,
    rel: [],
    Rarity: 1,
    Icon: '/IconRogueRogue03.webp',
    Name: '青枝朱弦',
    Desc: [
      "消灭敌方目标后，我方全体速度提高<color style='color:#f29e38;'> 4% </color>，最多叠加<color style='color:#f29e38;'> 3 </color>次。",
      "消灭敌方目标后，我方全体速度提高<color style='color:#f29e38;'> 6% </color>，最多叠加<color style='color:#f29e38;'> 3 </color>次。",
    ],
    Effects: [],
  },
  {
    _id: 616530,
    Path: 125,
    Type: BuffType.Blessing,
    rel: [],
    Rarity: 3,
    Icon: '/IconRogueWarrior03.webp',
    Name: '无毛超光速暴涨',
    Desc: [
      "【<u class='infou'>耀变</u>】充能效率提高<color style='color:#f29e38;'> 30% </color>，【<u class='infou'>耀变</u>】被清除后返还<color style='color:#f29e38;'> 20% </color>的充能值。",
      "【<u class='infou'>耀变</u>】充能效率提高<color style='color:#f29e38;'> 45% </color>，【<u class='infou'>耀变</u>】被清除后返还<color style='color:#f29e38;'> 20% </color>的充能值。",
    ],
    Effects: [61000051],
  },
  {
    _id: 616531,
    Path: 125,
    Type: BuffType.Blessing,
    rel: [],
    Rarity: 3,
    Icon: '/IconRogueWarrior01.webp',
    Name: '随机自由程激波',
    Desc: [
      "我方目标发动攻击后，对攻击目标造成等同于【<u class='infou'>耀变</u>】<color style='color:#f29e38;'> 50% </color>的附加伤害。",
      "我方目标发动攻击后，对攻击目标造成等同于【<u class='infou'>耀变</u>】<color style='color:#f29e38;'> 75% </color>的附加伤害。",
    ],
    Effects: [61000051],
  },
  {
    _id: 616532,
    Path: 125,
    Type: BuffType.Blessing,
    rel: [],
    Rarity: 3,
    Icon: '/IconRogueWarrior02.webp',
    Name: '超高速云际介质',
    Desc: [
      '受到攻击时，我方目标所受伤害将由我方全体分摊。',
      "我方目标受到的伤害降低<color style='color:#f29e38;'> 15% </color>，受到攻击时，我方目标所受伤害由我方全体分摊。",
    ],
    Effects: [],
  },
  {
    _id: 616540,
    Path: 125,
    Type: BuffType.Blessing,
    rel: [],
    Rarity: 2,
    Icon: '/IconRogueWarrior01.webp',
    Name: '致密型闪焰',
    Desc: [
      "我方目标受到攻击时，【<u class='infou'>耀变</u>】伤害倍率提高原倍率的<color style='color:#f29e38;'> 20% </color>，最多叠加<color style='color:#f29e38;'> 2 </color>次，持续<color style='color:#f29e38;'> 2 </color>回合。",
      "我方目标受到攻击时，【<u class='infou'>耀变</u>】伤害倍率提高原倍率的<color style='color:#f29e38;'> 30% </color>，最多叠加<color style='color:#f29e38;'> 2 </color>次，持续<color style='color:#f29e38;'> 2 </color>回合。",
    ],
    Effects: [61000051],
  },
  {
    _id: 616541,
    Path: 125,
    Type: BuffType.Blessing,
    rel: [],
    Rarity: 2,
    Icon: '/IconRogueWarrior03.webp',
    Name: '同步性辐射',
    Desc: [
      "我方目标获得护盾量的<color style='color:#f29e38;'> 50% </color>也可被转化为【<u class='infou'>耀变</u>】。",
      "我方目标获得护盾量的<color style='color:#f29e38;'> 75% </color>也可被转化为【<u class='infou'>耀变</u>】。",
    ],
    Effects: [61000051],
  },
  {
    _id: 616542,
    Path: 125,
    Type: BuffType.Blessing,
    rel: [],
    Rarity: 2,
    Icon: '/IconRogueWarrior03.webp',
    Name: '连续性谱区',
    Desc: [
      "溢出回复量的<color style='color:#f29e38;'> 50% </color>也可被转化为【<u class='infou'>耀变</u>】。",
      "溢出回复量的<color style='color:#f29e38;'> 75% </color>也可被转化为【<u class='infou'>耀变</u>】。",
    ],
    Effects: [61000051],
  },
  {
    _id: 616543,
    Path: 125,
    Type: BuffType.Blessing,
    rel: [],
    Rarity: 2,
    Icon: '/IconRogueWarrior02.webp',
    Name: '遮蔽性隐带',
    Desc: [
      "【<u class='infou'>耀变</u>】基础值提高生命上限的<color style='color:#f29e38;'> 50% </color>。",
      "【<u class='infou'>耀变</u>】基础值提高生命上限的<color style='color:#f29e38;'> 75% </color>。",
    ],
    Effects: [61000051],
  },
  {
    _id: 616544,
    Path: 125,
    Type: BuffType.Blessing,
    rel: [],
    Rarity: 2,
    Icon: '/IconRogueWarrior01.webp',
    Name: '灾难性变星',
    Desc: [
      "【<u class='infou'>耀变</u>】造成伤害的暴击率提高<color style='color:#f29e38;'> 20% </color>，暴击伤害提高<color style='color:#f29e38;'> 50% </color>。",
      "【<u class='infou'>耀变</u>】造成伤害的暴击率提高<color style='color:#f29e38;'> 30% </color>，暴击伤害提高<color style='color:#f29e38;'> 75% </color>。",
    ],
    Effects: [61000051],
  },
  {
    _id: 616545,
    Path: 125,
    Type: BuffType.Blessing,
    rel: [],
    Rarity: 2,
    Icon: '/IconRogueWarrior02.webp',
    Name: '受迫性跃迁',
    Desc: [
      "我方目标受到攻击或消耗生命值后，若当前生命值百分比小于<color style='color:#f29e38;'> 35% </color>，回复等同于生命上限<color style='color:#f29e38;'> 12% </color>的生命值。",
      "我方目标受到攻击或消耗生命值后，若当前生命值百分比小于<color style='color:#f29e38;'> 35% </color>，则回复等同于生命上限<color style='color:#f29e38;'> 12% </color>的生命值。当前生命值百分比越低回复量越高，最多不超过<color style='color:#f29e38;'> 20% </color>。",
    ],
    Effects: [],
  },
  {
    _id: 616546,
    Path: 125,
    Type: BuffType.Blessing,
    rel: [],
    Rarity: 2,
    Icon: '/IconRogueWarrior02.webp',
    Name: '放射性衰变',
    Desc: [
      "我方目标生命百分比低于 50% 时，受到的伤害降低<color style='color:#f29e38;'> 10% </color>，回复量提高<color style='color:#f29e38;'> 20% </color>。",
      "我方目标生命百分比低于 50% 时，受到的伤害降低<color style='color:#f29e38;'> 15% </color>，回复量提高<color style='color:#f29e38;'> 30% </color>。",
    ],
    Effects: [],
  },
  {
    _id: 616550,
    Path: 125,
    Type: BuffType.Blessing,
    rel: [],
    Rarity: 1,
    Icon: '/IconRogueWarrior02.webp',
    Name: '双极喷流',
    Desc: [
      "我方目标受到的伤害降低<color style='color:#f29e38;'> 6% </color>。",
      "我方目标受到的伤害降低<color style='color:#f29e38;'> 9% </color>。",
    ],
    Effects: [],
  },
  {
    _id: 616551,
    Path: 125,
    Type: BuffType.Blessing,
    rel: [],
    Rarity: 1,
    Icon: '/IconRogueWarrior02.webp',
    Name: '双瓣结构',
    Desc: [
      "我方目标效果抵抗提高<color style='color:#f29e38;'> 12% </color>。",
      "我方目标效果抵抗提高<color style='color:#f29e38;'> 18% </color>。",
    ],
    Effects: [],
  },
  {
    _id: 616552,
    Path: 125,
    Type: BuffType.Blessing,
    rel: [],
    Rarity: 1,
    Icon: '/IconRogueWarrior02.webp',
    Name: '相接双星',
    Desc: [
      "我方目标生命上限提高<color style='color:#f29e38;'> 16% </color>。",
      "我方目标生命上限提高<color style='color:#f29e38;'> 24% </color>。",
    ],
    Effects: [],
  },
  {
    _id: 616553,
    Path: 125,
    Type: BuffType.Blessing,
    rel: [],
    Rarity: 1,
    Icon: '/IconRogueWarrior02.webp',
    Name: '绝对星等',
    Desc: [
      "我方目标回复量提高<color style='color:#f29e38;'> 12% </color>。",
      "我方目标回复量提高<color style='color:#f29e38;'> 18% </color>。",
    ],
    Effects: [],
  },
  {
    _id: 616554,
    Path: 125,
    Type: BuffType.Blessing,
    rel: [],
    Rarity: 1,
    Icon: '/IconRogueWarrior02.webp',
    Name: '标准烛光',
    Desc: [
      "我方目标获得的护盾量提高<color style='color:#f29e38;'> 12% </color>。",
      "我方目标获得的护盾量提高<color style='color:#f29e38;'> 18% </color>。",
    ],
    Effects: [],
  },
  {
    _id: 616555,
    Path: 125,
    Type: BuffType.Blessing,
    rel: [],
    Rarity: 1,
    Icon: '/IconRogueWarrior02.webp',
    Name: '传质次星',
    Desc: [
      "我方目标生命值或护盾量降低后，生命上限提高<color style='color:#f29e38;'> 20% </color>，持续<color style='color:#f29e38;'> 2 </color>回合。",
      "我方目标生命值或护盾量降低后，生命上限提高<color style='color:#f29e38;'> 30% </color>，持续<color style='color:#f29e38;'> 2 </color>回合。",
    ],
    Effects: [],
  },
  {
    _id: 616556,
    Path: 125,
    Type: BuffType.Blessing,
    rel: [],
    Rarity: 1,
    Icon: '/IconRogueWarrior02.webp',
    Name: '互食联星',
    Desc: [
      "我方目标生命值或护盾量降低后，效果抵抗提高<color style='color:#f29e38;'> 16% </color>，持续<color style='color:#f29e38;'> 2 </color>回合。",
      "我方目标生命值或护盾量降低后，效果抵抗提高<color style='color:#f29e38;'> 24% </color>，持续<color style='color:#f29e38;'> 2 </color>回合。",
    ],
    Effects: [],
  },
  {
    _id: 616557,
    Path: 125,
    Type: BuffType.Blessing,
    rel: [],
    Rarity: 1,
    Icon: '/IconRogueWarrior02.webp',
    Name: '新星爆发',
    Desc: [
      "角色受到致命攻击时不会陷入无法战斗状态，并使当前生命值立即回复至自身生命上限的<color style='color:#f29e38;'> 20% </color>。该效果我方全体单场战斗中只能触发<color style='color:#f29e38;'> 1 </color>次。",
      "角色受到致命攻击时不会陷入无法战斗状态，并使当前生命值立即回复至自身生命上限的<color style='color:#f29e38;'> 100% </color>。该效果我方全体单场战斗中只能触发<color style='color:#f29e38;'> 1 </color>次。",
    ],
    Effects: [],
  },
  {
    _id: 616630,
    Path: 126,
    Type: BuffType.Blessing,
    rel: [],
    Rarity: 3,
    Icon: '/IconRogueJoy01.webp',
    Name: '《甘草披萨•薄荷刨冰》',
    Desc: [
      "我方目标发动追加攻击后，对攻击目标造成<color style='color:#f29e38;'> 1 </color>次等同于攻击力<color style='color:#f29e38;'> 80% </color>的【<u class='infou'>回味</u>】伤害，造成【<u class='infou'>回味</u>】伤害时，额外以<color style='color:#f29e38;'> 20% </color>的比例触发1次【<u class='infou'>回味</u>】伤害。",
      "我方目标发动追加攻击后，对攻击目标造成<color style='color:#f29e38;'> 1 </color>次等同于攻击力<color style='color:#f29e38;'> 120% </color>的【<u class='infou'>回味</u>】伤害，造成【<u class='infou'>回味</u>】伤害时，额外以<color style='color:#f29e38;'> 30% </color>的比例触发1次【<u class='infou'>回味</u>】伤害。",
    ],
    Effects: [61000054],
  },
  {
    _id: 616631,
    Path: 126,
    Type: BuffType.Blessing,
    rel: [],
    Rarity: 3,
    Icon: '/IconRogueJoy01.webp',
    Name: '《海洋上校•昨日世界》',
    Desc: [
      "我方目标施放终结技后，下<color style='color:#f29e38;'> 2 </color>次攻击会对受到攻击的敌方目标造成<color style='color:#f29e38;'> 1 </color>次等同于攻击力<color style='color:#f29e38;'> 100% </color>的【<u class='infou'>回味</u>】伤害。",
      "我方目标施放终结技后，下<color style='color:#f29e38;'> 3 </color>次攻击会对受到攻击的敌方目标造成<color style='color:#f29e38;'> 1 </color>次等同于攻击力<color style='color:#f29e38;'> 100% </color>的【<u class='infou'>回味</u>】伤害，本次终结技也会触发该效果。",
    ],
    Effects: [61000054],
  },
  {
    _id: 616632,
    Path: 126,
    Type: BuffType.Blessing,
    rel: [],
    Rarity: 3,
    Icon: '/IconRogueJoy04.webp',
    Name: '《日出黄沙•单人舞团》',
    Desc: [
      "我方目标对敌方目标发动追加攻击后，使其行动延后<color style='color:#f29e38;'> 25% </color>，敌方目标每回合最多触发<color style='color:#f29e38;'> 2 </color>次。",
      "我方目标对敌方目标发动追加攻击后，使其行动延后<color style='color:#f29e38;'> 30% </color>，敌方目标每回合最多触发<color style='color:#f29e38;'> 3 </color>次。",
    ],
    Effects: [],
  },
  {
    _id: 616640,
    Path: 126,
    Type: BuffType.Blessing,
    rel: [],
    Rarity: 2,
    Icon: '/IconRogueJoy01.webp',
    Name: '《屋中寂静的一月》',
    Desc: [
      "我方目标攻击处于弱点击破状态下的敌方目标后，造成<color style='color:#f29e38;'> 1 </color>次等同于攻击力<color style='color:#f29e38;'> 100% </color>的【<u class='infou'>回味</u>】伤害。",
      "我方目标攻击处于弱点击破状态下的敌方目标后，造成<color style='color:#f29e38;'> 1 </color>次等同于攻击力<color style='color:#f29e38;'> 150% </color>的【<u class='infou'>回味</u>】伤害。",
    ],
    Effects: [61000054],
  },
  {
    _id: 616641,
    Path: 126,
    Type: BuffType.Blessing,
    rel: [],
    Rarity: 2,
    Icon: '/IconRogueJoy04.webp',
    Name: '《少尉深爱鱼子酱》',
    Desc: [
      "敌方目标每受到1种属性的【<u class='infou'>回味</u>】伤害，攻击力降低<color style='color:#f29e38;'> 4% </color>，持续至下次行动后。",
      "敌方目标每受到1种属性的【<u class='infou'>回味</u>】伤害，攻击力降低<color style='color:#f29e38;'> 6% </color>，持续至下次行动后。",
    ],
    Effects: [61000054],
  },
  {
    _id: 616642,
    Path: 126,
    Type: BuffType.Blessing,
    rel: [],
    Rarity: 2,
    Icon: '/IconRogueJoy04.webp',
    Name: '《你知道，你的柜子很漂亮》',
    Desc: [
      "敌方目标每受到1种属性的【<u class='infou'>回味</u>】伤害，受到的伤害提高<color style='color:#f29e38;'> 4% </color>，持续至下次行动后。",
      "敌方目标每受到1种属性的【<u class='infou'>回味</u>】伤害，受到的伤害提高<color style='color:#f29e38;'> 6% </color>，持续至下次行动后。",
    ],
    Effects: [61000054],
  },
  {
    _id: 616643,
    Path: 126,
    Type: BuffType.Blessing,
    rel: [],
    Rarity: 2,
    Icon: '/IconRogueJoy01.webp',
    Name: '《神圣奇异果之种》',
    Desc: [
      "我方目标对敌方目标造成【<u class='infou'>回味</u>】伤害时，使自身造成的伤害提高<color style='color:#f29e38;'> 12% </color>，最多叠加<color style='color:#f29e38;'> 4 </color>层，持续至下回合开始时。",
      "我方目标对敌方目标造成【<u class='infou'>回味</u>】伤害时，使自身造成的伤害提高<color style='color:#f29e38;'> 12% </color>，最多叠加<color style='color:#f29e38;'> 7 </color>层，持续至下回合开始时。",
    ],
    Effects: [61000054],
  },
  {
    _id: 616644,
    Path: 126,
    Type: BuffType.Blessing,
    rel: [],
    Rarity: 2,
    Icon: '/IconRogueJoy01.webp',
    Name: '《银河系的猫叫声》',
    Desc: [
      "【<u class='infou'>回味</u>】造成的伤害提高<color style='color:#f29e38;'> 70% </color>。",
      "【<u class='infou'>回味</u>】造成的伤害提高<color style='color:#f29e38;'> 105% </color>。",
    ],
    Effects: [61000054],
  },
  {
    _id: 616645,
    Path: 126,
    Type: BuffType.Blessing,
    rel: [],
    Rarity: 2,
    Icon: '/IconRogueJoy01.webp',
    Name: '《海洋里的西蒙》',
    Desc: [
      "我方目标造成的追加攻击伤害和附加伤害无视敌方目标<color style='color:#f29e38;'> 18% </color>的防御力。",
      "我方目标造成的追加攻击伤害和附加伤害无视敌方目标<color style='color:#f29e38;'> 24% </color>的防御力。",
    ],
    Effects: [],
  },
  {
    _id: 616646,
    Path: 126,
    Type: BuffType.Blessing,
    rel: [],
    Rarity: 2,
    Icon: '/IconRogueJoy03.webp',
    Name: '《白日漫漫路迢迢》',
    Desc: [
      "我方目标造成追加攻击伤害时的弱点击破效率提高<color style='color:#f29e38;'> 35% </color>。",
      "我方目标造成追加攻击伤害时的弱点击破效率提高<color style='color:#f29e38;'> 50% </color>。",
    ],
    Effects: [],
  },
  {
    _id: 616650,
    Path: 126,
    Type: BuffType.Blessing,
    rel: [],
    Rarity: 1,
    Icon: '/IconRogueJoy01.webp',
    Name: '《迷幻停车场》',
    Desc: [
      "我方目标造成的追加攻击伤害和附加伤害，暴击伤害提高<color style='color:#f29e38;'> 30% </color>。",
      "我方目标造成的追加攻击伤害和附加伤害，暴击伤害提高<color style='color:#f29e38;'> 45% </color>。",
    ],
    Effects: [],
  },
  {
    _id: 616651,
    Path: 126,
    Type: BuffType.Blessing,
    rel: [],
    Rarity: 1,
    Icon: '/IconRogueJoy01.webp',
    Name: '《点恋线》',
    Desc: [
      "我方目标发动追加攻击后，我方全体目标攻击力提高<color style='color:#f29e38;'> 20% </color>，持续<color style='color:#f29e38;'> 2 </color>回合。",
      "我方目标发动追加攻击后，我方全体目标攻击力提高<color style='color:#f29e38;'> 30% </color>，持续<color style='color:#f29e38;'> 2 </color>回合。",
    ],
    Effects: [],
  },
  {
    _id: 616652,
    Path: 126,
    Type: BuffType.Blessing,
    rel: [],
    Rarity: 1,
    Icon: '/IconRogueJoy01.webp',
    Name: '《欧米茄城》',
    Desc: [
      "我方目标造成的追加攻击伤害和附加伤害提高<color style='color:#f29e38;'> 30% </color>。",
      "我方目标造成的追加攻击伤害和附加伤害提高<color style='color:#f29e38;'> 45% </color>。",
    ],
    Effects: [],
  },
  {
    _id: 616653,
    Path: 126,
    Type: BuffType.Blessing,
    rel: [],
    Rarity: 1,
    Icon: '/IconRogueJoy01.webp',
    Name: '《暴力先生》',
    Desc: [
      "我方目标造成的追加攻击伤害和附加伤害，暴击率提高<color style='color:#f29e38;'> 18% </color>。",
      "我方目标造成的追加攻击伤害和附加伤害，暴击率提高<color style='color:#f29e38;'> 27% </color>。",
    ],
    Effects: [],
  },
  {
    _id: 616654,
    Path: 126,
    Type: BuffType.Blessing,
    rel: [],
    Rarity: 1,
    Icon: '/IconRogueJoy03.webp',
    Name: '《遗世避难所》',
    Desc: [
      "我方目标发动追加攻击后，恢复<color style='color:#f29e38;'> 6 </color>点能量，该效果每回合最多触发<color style='color:#f29e38;'> 1 </color>次。",
      "我方目标发动追加攻击后，恢复<color style='color:#f29e38;'> 8 </color>点能量，该效果每回合最多触发<color style='color:#f29e38;'> 1 </color>次。",
    ],
    Effects: [],
  },
  {
    _id: 616655,
    Path: 126,
    Type: BuffType.Blessing,
    rel: [],
    Rarity: 1,
    Icon: '/IconRogueJoy02.webp',
    Name: '《灰币金黄》',
    Desc: [
      "我方目标发动追加攻击后，回复等同于自身生命上限<color style='color:#f29e38;'> 10% </color>的生命值。",
      "我方目标发动追加攻击后，回复等同于自身生命上限<color style='color:#f29e38;'> 15% </color>的生命值。",
    ],
    Effects: [],
  },
  {
    _id: 616656,
    Path: 126,
    Type: BuffType.Blessing,
    rel: [],
    Rarity: 1,
    Icon: '/IconRogueJoy02.webp',
    Name: '《死神骑车来》',
    Desc: [
      "我方目标发动追加攻击后，我方全体目标防御力提高<color style='color:#f29e38;'> 20% </color>，持续<color style='color:#f29e38;'> 2 </color>回合。",
      "我方目标发动追加攻击后，我方全体目标防御力提高<color style='color:#f29e38;'> 30% </color>，持续<color style='color:#f29e38;'> 2 </color>回合。",
    ],
    Effects: [],
  },
  {
    _id: 616657,
    Path: 126,
    Type: BuffType.Blessing,
    rel: [],
    Rarity: 1,
    Icon: '/IconRogueJoy03.webp',
    Name: '《猫镇》',
    Desc: [
      "我方目标发动追加攻击后，我方全体目标速度提高<color style='color:#f29e38;'> 10% </color>，持续<color style='color:#f29e38;'> 2 </color>回合。",
      "我方目标发动追加攻击后，我方全体目标速度提高<color style='color:#f29e38;'> 15% </color>，持续<color style='color:#f29e38;'> 2 </color>回合。",
    ],
    Effects: [],
  },
  {
    _id: 616730,
    Path: 127,
    Type: BuffType.Blessing,
    rel: [],
    Rarity: 3,
    Icon: '/IconRoguePropagation03.webp',
    Name: '穆氏拟态',
    Desc: [
      "我方目标攻击力提高<color style='color:#f29e38;'> 50% </color>，每获得或消耗1个战技点，为【<u class='infou'>魂茧</u>】充能<color style='color:#f29e38;'> 6% </color>。",
      "我方目标攻击力提高<color style='color:#f29e38;'> 75% </color>，每获得或消耗1个战技点，为【<u class='infou'>魂茧</u>】充能<color style='color:#f29e38;'> 9% </color>。",
    ],
    Effects: [61000052],
  },
  {
    _id: 616731,
    Path: 127,
    Type: BuffType.Blessing,
    rel: [],
    Rarity: 3,
    Icon: '/IconRoguePropagation01.webp',
    Name: '弹射孢子',
    Desc: [
      "【<u class='infou'>蝶魄</u>】状态下，我方目标造成的普攻/战技伤害提高<color style='color:#f29e38;'> 40% </color>，且【<u class='infou'>蝶魄</u>】会额外造成1次原伤害<color style='color:#f29e38;'> 20% </color>的真实伤害。",
      "【<u class='infou'>蝶魄</u>】状态下，我方目标造成的普攻/战技伤害提高<color style='color:#f29e38;'> 60% </color>，且【<u class='infou'>蝶魄</u>】会额外造成1次原伤害<color style='color:#f29e38;'> 25% </color>的真实伤害。",
    ],
    Effects: [61000052],
  },
  {
    _id: 616732,
    Path: 127,
    Type: BuffType.Blessing,
    rel: [],
    Rarity: 3,
    Icon: '/IconRoguePropagation01.webp',
    Name: '布勒水滴',
    Desc: [
      "我方目标消耗战技点后，我方全体暴击伤害提高<color style='color:#f29e38;'> 2% </color>，最多叠加<color style='color:#f29e38;'> 40 </color>层，施放终结技后，下次消耗战技点后视为额外消耗一点。",
      "我方目标消耗或获得战技点后，我方全体暴击伤害提高<color style='color:#f29e38;'> 3% </color>，最多叠加<color style='color:#f29e38;'> 40 </color>层，施放终结技后，下次消耗或获得战技点后视为额外消耗或获得1点。",
    ],
    Effects: [],
  },
  {
    _id: 616740,
    Path: 127,
    Type: BuffType.Blessing,
    rel: [],
    Rarity: 2,
    Icon: '/IconRoguePropagation03.webp',
    Name: '子实体',
    Desc: [
      "消灭敌方目标后，为【<u class='infou'>魂茧</u>】充能<color style='color:#f29e38;'> 30% </color>。",
      "消灭敌方目标后，为【<u class='infou'>魂茧</u>】充能<color style='color:#f29e38;'> 45% </color>。",
    ],
    Effects: [61000052],
  },
  {
    _id: 616741,
    Path: 127,
    Type: BuffType.Blessing,
    rel: [],
    Rarity: 2,
    Icon: '/IconRoguePropagation03.webp',
    Name: '几丁质',
    Desc: [
      "我方目标攻击力提高<color style='color:#f29e38;'> 30% </color>。进入战斗时，为【<u class='infou'>魂茧</u>】额外充能<color style='color:#f29e38;'> 20% </color>。",
      "我方目标攻击力提高<color style='color:#f29e38;'> 45% </color>。进入战斗时，为【<u class='infou'>魂茧</u>】额外充能<color style='color:#f29e38;'> 30% </color>。",
    ],
    Effects: [61000052],
  },
  {
    _id: 616742,
    Path: 127,
    Type: BuffType.Blessing,
    rel: [],
    Rarity: 2,
    Icon: '/IconRoguePropagation03.webp',
    Name: '自由蛹',
    Desc: [
      "【<u class='infou'>魂茧</u>】变为【<u class='infou'>蝶魄</u>】时，回复<color style='color:#f29e38;'> 60% </color>生命值，并使该状态下造成的伤害提高<color style='color:#f29e38;'> 20% </color>。",
      "【<u class='infou'>魂茧</u>】变为【<u class='infou'>蝶魄</u>】时，回复<color style='color:#f29e38;'> 100% </color>生命值，并使该状态下造成的伤害提高<color style='color:#f29e38;'> 30% </color>。",
    ],
    Effects: [61000052],
  },
  {
    _id: 616743,
    Path: 127,
    Type: BuffType.Blessing,
    rel: [],
    Rarity: 2,
    Icon: '/IconRoguePropagation01.webp',
    Name: '担孢子',
    Desc: [
      "【<u class='infou'>蝶魄</u>】状态下，普攻战技伤害的抗性穿透提高<color style='color:#f29e38;'> 14% </color>。",
      "【<u class='infou'>蝶魄</u>】状态下，普攻战技伤害的抗性穿透提高<color style='color:#f29e38;'> 21% </color>。",
    ],
    Effects: [61000052],
  },
  {
    _id: 616744,
    Path: 127,
    Type: BuffType.Blessing,
    rel: [],
    Rarity: 2,
    Icon: '/IconRoguePropagation03.webp',
    Name: '结构色',
    Desc: [
      "【<u class='infou'>魂茧</u>】状态下，速度提高<color style='color:#f29e38;'> 16% </color>，【<u class='infou'>蝶魄</u>】状态下，普攻战技造成的伤害提高<color style='color:#f29e38;'> 50% </color>。",
      "【<u class='infou'>魂茧</u>】状态下，速度提高<color style='color:#f29e38;'> 24% </color>，【<u class='infou'>蝶魄</u>】状态下，普攻战技造成的伤害提高<color style='color:#f29e38;'> 75% </color>。",
    ],
    Effects: [61000052],
  },
  {
    _id: 616745,
    Path: 127,
    Type: BuffType.Blessing,
    rel: [],
    Rarity: 2,
    Icon: '/IconRoguePropagation02.webp',
    Name: '端感棒',
    Desc: [
      "我方目标每消耗1个战技点，受到的伤害降低<color style='color:#f29e38;'> 6% </color>，持续<color style='color:#f29e38;'> 2 </color>回合，该效果最多叠加<color style='color:#f29e38;'> 2 </color>层。",
      "我方目标每消耗1个战技点，受到的伤害降低<color style='color:#f29e38;'> 6% </color>，持续<color style='color:#f29e38;'> 2 </color>回合，该效果最多叠加<color style='color:#f29e38;'> 3 </color>层。",
    ],
    Effects: [],
  },
  {
    _id: 616746,
    Path: 127,
    Type: BuffType.Blessing,
    rel: [],
    Rarity: 2,
    Icon: '/IconRoguePropagation01.webp',
    Name: '飞溅蛊',
    Desc: [
      "我方目标造成的普攻/战技伤害会对相邻目标，造成等同于原伤害<color style='color:#f29e38;'> 20% </color>的伤害。",
      "我方目标造成的普攻/战技伤害会对相邻目标，造成等同于原伤害<color style='color:#f29e38;'> 30% </color>的伤害。",
    ],
    Effects: [],
  },
  {
    _id: 616750,
    Path: 127,
    Type: BuffType.Blessing,
    rel: [],
    Rarity: 1,
    Icon: '/IconRoguePropagation03.webp',
    Name: '蕈托',
    Desc: [
      "我方目标消耗战技点时，有<color style='color:#f29e38;'> 20% </color>固定概率恢复<color style='color:#f29e38;'> 1 </color>个战技点。",
      "我方目标消耗战技点时，有<color style='color:#f29e38;'> 30% </color>固定概率恢复<color style='color:#f29e38;'> 1 </color>个战技点。",
    ],
    Effects: [],
  },
  {
    _id: 616751,
    Path: 127,
    Type: BuffType.Blessing,
    rel: [],
    Rarity: 1,
    Icon: '/IconRoguePropagation01.webp',
    Name: '悬丝',
    Desc: [
      "我方目标施放普攻、战技时造成的伤害提高<color style='color:#f29e38;'> 30% </color>。",
      "我方目标施放普攻、战技时造成的伤害提高<color style='color:#f29e38;'> 45% </color>。",
    ],
    Effects: [],
  },
  {
    _id: 616752,
    Path: 127,
    Type: BuffType.Blessing,
    rel: [],
    Rarity: 1,
    Icon: '/IconRoguePropagation01.webp',
    Name: '眼斑',
    Desc: [
      "我方目标施放普攻、战技时造成的暴击伤害提高<color style='color:#f29e38;'> 30% </color>。",
      "我方目标施放普攻、战技时造成的暴击伤害提高<color style='color:#f29e38;'> 45% </color>。",
    ],
    Effects: [],
  },
  {
    _id: 616753,
    Path: 127,
    Type: BuffType.Blessing,
    rel: [],
    Rarity: 1,
    Icon: '/IconRoguePropagation01.webp',
    Name: '背翼',
    Desc: [
      "我方目标施放普攻、战技时造成的暴击率提高<color style='color:#f29e38;'> 16% </color>。",
      "我方目标施放普攻、战技时造成的暴击率提高<color style='color:#f29e38;'> 24% </color>。",
    ],
    Effects: [],
  },
  {
    _id: 616754,
    Path: 127,
    Type: BuffType.Blessing,
    rel: [],
    Rarity: 1,
    Icon: '/IconRoguePropagation02.webp',
    Name: '厚垣',
    Desc: [
      "我方目标消耗战技点时，防御力提高<color style='color:#f29e38;'> 30% </color>，持续<color style='color:#f29e38;'> 1 </color>回合",
      "我方目标消耗战技点时，防御力提高<color style='color:#f29e38;'> 45% </color>，持续<color style='color:#f29e38;'> 1 </color>回合",
    ],
    Effects: [],
  },
  {
    _id: 616755,
    Path: 127,
    Type: BuffType.Blessing,
    rel: [],
    Rarity: 1,
    Icon: '/IconRoguePropagation03.webp',
    Name: '跗节',
    Desc: [
      "我方目标消耗战技点时，速度提高<color style='color:#f29e38;'> 12% </color>，持续<color style='color:#f29e38;'> 2 </color>回合",
      "我方目标消耗战技点时，速度提高<color style='color:#f29e38;'> 18% </color>，持续<color style='color:#f29e38;'> 2 </color>回合",
    ],
    Effects: [],
  },
  {
    _id: 616756,
    Path: 127,
    Type: BuffType.Blessing,
    rel: [],
    Rarity: 1,
    Icon: '/IconRoguePropagation03.webp',
    Name: '唇须',
    Desc: [
      "我方目标消耗战技点时，恢复<color style='color:#f29e38;'> 3 </color>点能量。",
      "我方目标消耗战技点时，恢复<color style='color:#f29e38;'> 4 </color>点能量。",
    ],
    Effects: [],
  },
  {
    _id: 616757,
    Path: 127,
    Type: BuffType.Blessing,
    rel: [],
    Rarity: 1,
    Icon: '/IconRoguePropagation02.webp',
    Name: '芽殖',
    Desc: [
      "我方目标消耗战技点时，回复等同于<color style='color:#f29e38;'> 10% </color>生命上限的生命值。",
      "我方目标消耗战技点时，回复等同于<color style='color:#f29e38;'> 15% </color>生命上限的生命值。",
    ],
    Effects: [],
  },
  {
    _id: 616830,
    Path: 128,
    Type: BuffType.Blessing,
    rel: [],
    Rarity: 3,
    Icon: '/IconRogueMage03.webp',
    Name: 'TR -303 式海马体',
    Desc: [
      "我方目标击破敌方目标弱点后，为【<u class='infou'>罐中脑</u>】充能<color style='color:#f29e38;'> 10% </color>，若为精英敌人时则额外充能<color style='color:#f29e38;'> 40% </color>。",
      "进入战斗时，为【<u class='infou'>罐中脑</u>】充能<color style='color:#f29e38;'> 100% </color>。我方目标击破敌方目标弱点后，为【<u class='infou'>罐中脑</u>】充能<color style='color:#f29e38;'> 15% </color>，若为精英敌人时则额外充能<color style='color:#f29e38;'> 45% </color>。",
    ],
    Effects: [61000044],
  },
  {
    _id: 616831,
    Path: 128,
    Type: BuffType.Blessing,
    rel: [],
    Rarity: 3,
    Icon: '/IconRogueMage03.webp',
    Name: 'DBS -45 式伏隔核',
    Desc: [
      "我方目标使敌方目标受到致命伤害时，为【<u class='infou'>罐中脑</u>】充能<color style='color:#f29e38;'> 50% </color>。",
      "我方目标使敌方目标受到致命伤害时，为【<u class='infou'>罐中脑</u>】充能<color style='color:#f29e38;'> 50% </color>，每次充满【<u class='infou'>罐中脑</u>】后，速度提高<color style='color:#f29e38;'> 20% </color>，持续<color style='color:#f29e38;'> 2 </color>回合。",
    ],
    Effects: [61000044],
  },
  {
    _id: 616832,
    Path: 128,
    Type: BuffType.Blessing,
    rel: [],
    Rarity: 3,
    Icon: '/IconRogueMage01.webp',
    Name: 'ELO -536 式黑质',
    Desc: [
      "我方目标造成的终结技伤害的全属性抗性穿透提高<color style='color:#f29e38;'> 20% </color>，场上每有一名敌方目标，都会使造成的终结技伤害的全属性抗性穿透额外提高<color style='color:#f29e38;'> 3% </color>，持续至下一次施放终结技后。",
      "我方目标造成的终结技伤害的全属性抗性穿透提高<color style='color:#f29e38;'> 25% </color>，场上每有一名敌方目标，都会使造成的终结技伤害的全属性抗性穿透额外提高<color style='color:#f29e38;'> 3% </color>，持续至下一次施放终结技后。",
    ],
    Effects: [],
  },
  {
    _id: 616840,
    Path: 128,
    Type: BuffType.Blessing,
    rel: [],
    Rarity: 2,
    Icon: '/IconRogueMage01.webp',
    Name: '重启：终末神经',
    Desc: [
      "我方目标利用【<u class='infou'>罐中脑</u>】施放终结技时，使暴击伤害提高<color style='color:#f29e38;'> 80% </color>，持续至本次技能结束。",
      "我方目标利用【<u class='infou'>罐中脑</u>】施放终结技时，使暴击伤害提高<color style='color:#f29e38;'> 90% </color>，暴击伤害提高效果会持续至下一次攻击结束。",
    ],
    Effects: [61000044],
  },
  {
    _id: 616841,
    Path: 128,
    Type: BuffType.Blessing,
    rel: [],
    Rarity: 2,
    Icon: '/IconRogueMage02.webp',
    Name: '迭代：认知地图',
    Desc: [
      "我方目标利用【<u class='infou'>罐中脑</u>】施放终结技后，获得等同于生命上限<color style='color:#f29e38;'> 36% </color>的护盾，持续<color style='color:#f29e38;'> 2 </color>回合。",
      "我方目标利用【<u class='infou'>罐中脑</u>】施放终结技后，获得等同于生命上限<color style='color:#f29e38;'> 45% </color>的护盾，持续<color style='color:#f29e38;'> 3 </color>回合。",
    ],
    Effects: [61000044],
  },
  {
    _id: 616842,
    Path: 128,
    Type: BuffType.Blessing,
    rel: [],
    Rarity: 2,
    Icon: '/IconRogueMage01.webp',
    Name: '解析：程序记忆',
    Desc: [
      "我方目标使用【<u class='infou'>罐中脑</u>】施放终结技时，我方全体造成的伤害提高<color style='color:#f29e38;'> 36% </color>，持续2回合。",
      "我方目标使用【<u class='infou'>罐中脑</u>】施放终结技时，我方全体造成的伤害提高<color style='color:#f29e38;'> 54% </color>，持续2回合。",
    ],
    Effects: [61000044],
  },
  {
    _id: 616843,
    Path: 128,
    Type: BuffType.Blessing,
    rel: [],
    Rarity: 2,
    Icon: '/IconRogueMage03.webp',
    Name: '稳定：慢波睡眠',
    Desc: [
      "我方目标受到攻击后，为【<u class='infou'>罐中脑</u>】充能<color style='color:#f29e38;'> 6% </color>。",
      "我方目标受到攻击后，为【<u class='infou'>罐中脑</u>】充能<color style='color:#f29e38;'> 9% </color>。",
    ],
    Effects: [61000044],
  },
  {
    _id: 616844,
    Path: 128,
    Type: BuffType.Blessing,
    rel: [],
    Rarity: 2,
    Icon: '/IconRogueMage03.webp',
    Name: '衍生：分野细胞',
    Desc: [
      "我方目标使用【<u class='infou'>罐中脑</u>】施放终结技后，攻击力提高<color style='color:#f29e38;'> 60% </color>，持续<color style='color:#f29e38;'> 2 </color>回合。",
      "我方目标使用【<u class='infou'>罐中脑</u>】施放终结技后，攻击力提高<color style='color:#f29e38;'> 90% </color>，持续<color style='color:#f29e38;'> 2 </color>回合。",
    ],
    Effects: [61000044],
  },
  {
    _id: 616845,
    Path: 128,
    Type: BuffType.Blessing,
    rel: [],
    Rarity: 2,
    Icon: '/IconRogueMage04.webp',
    Name: '执行：强化学习',
    Desc: [
      "我方目标施放终结技攻击处于弱点击破状态下的敌方目标后，使其行动延后<color style='color:#f29e38;'> 16% </color>，敌方目标每次陷入弱点击破状态后最多触发<color style='color:#f29e38;'> 3 </color>次该效果。",
      "我方目标施放终结技攻击处于弱点击破状态下的敌方目标后，使其行动延后<color style='color:#f29e38;'> 24% </color>，敌方目标每次陷入弱点击破状态后最多触发<color style='color:#f29e38;'> 3 </color>次该效果。",
    ],
    Effects: [],
  },
  {
    _id: 616846,
    Path: 128,
    Type: BuffType.Blessing,
    rel: [],
    Rarity: 2,
    Icon: '/IconRogueMage01.webp',
    Name: '开放：直接通路',
    Desc: [
      "若我方目标的<u class='infou'>群攻</u>技能只攻击了1个敌方目标，则本次攻击对受到攻击的敌方目标额外造成等同于原伤害<color style='color:#f29e38;'> 40% </color>的固定数值的伤害。",
      "若我方目标的<u class='infou'>群攻</u>技能只攻击了1个敌方目标，则本次攻击对受到攻击的敌方目标额外造成等同于原伤害<color style='color:#f29e38;'> 60% </color>的固定数值的伤害。",
    ],
    Effects: [61000045],
  },
  {
    _id: 616850,
    Path: 128,
    Type: BuffType.Blessing,
    rel: [],
    Rarity: 1,
    Icon: '/IconRogueMage01.webp',
    Name: '投影闪烁的旌旗',
    Desc: [
      "我方目标造成的终结技伤害提高<color style='color:#f29e38;'> 18% </color>。",
      "我方目标造成的终结技伤害提高<color style='color:#f29e38;'> 27% </color>。",
    ],
    Effects: [],
  },
  {
    _id: 616851,
    Path: 128,
    Type: BuffType.Blessing,
    rel: [],
    Rarity: 1,
    Icon: '/IconRogueMage01.webp',
    Name: '固态存储的甲胄',
    Desc: [
      "我方目标造成的终结技伤害暴击率提高<color style='color:#f29e38;'> 18% </color>。",
      "我方目标造成的终结技伤害暴击率提高<color style='color:#f29e38;'> 27% </color>。",
    ],
    Effects: [],
  },
  {
    _id: 616852,
    Path: 128,
    Type: BuffType.Blessing,
    rel: [],
    Rarity: 1,
    Icon: '/IconRogueMage01.webp',
    Name: '安全擦除的舆图',
    Desc: [
      "我方目标造成的终结技伤害暴击伤害提高<color style='color:#f29e38;'> 30% </color>。",
      "我方目标造成的终结技伤害暴击伤害提高<color style='color:#f29e38;'> 45% </color>。",
    ],
    Effects: [],
  },
  {
    _id: 616853,
    Path: 128,
    Type: BuffType.Blessing,
    rel: [],
    Rarity: 1,
    Icon: '/IconRogueMage03.webp',
    Name: '分区对齐的包裹',
    Desc: [
      "进入战斗时，恢复等同于能量上限<color style='color:#f29e38;'> 40% </color>的能量。",
      "进入战斗时，恢复等同于能量上限<color style='color:#f29e38;'> 60% </color>的能量。",
    ],
    Effects: [],
  },
  {
    _id: 616854,
    Path: 128,
    Type: BuffType.Blessing,
    rel: [],
    Rarity: 1,
    Icon: '/IconRogueMage01.webp',
    Name: '宏块抹除的航路',
    Desc: [
      "我方目标施放终结技时，使攻击力提高<color style='color:#f29e38;'> 24% </color>，持续<color style='color:#f29e38;'> 2 </color>回合。",
      "我方目标施放终结技时，使攻击力提高<color style='color:#f29e38;'> 36% </color>，持续<color style='color:#f29e38;'> 2 </color>回合。",
    ],
    Effects: [],
  },
  {
    _id: 616855,
    Path: 128,
    Type: BuffType.Blessing,
    rel: [],
    Rarity: 1,
    Icon: '/IconRogueMage02.webp',
    Name: '晶体谐振的灯塔',
    Desc: [
      "我方目标施放终结技后，生命上限提高<color style='color:#f29e38;'> 20% </color>，持续<color style='color:#f29e38;'> 2 </color>回合。",
      "我方目标施放终结技后，生命上限提高<color style='color:#f29e38;'> 30% </color>，持续<color style='color:#f29e38;'> 2 </color>回合。",
    ],
    Effects: [],
  },
  {
    _id: 616856,
    Path: 128,
    Type: BuffType.Blessing,
    rel: [],
    Rarity: 1,
    Icon: '/IconRogueMage02.webp',
    Name: '光学导引的透镜',
    Desc: [
      "我方目标施放终结技后，回复等同于生命上限<color style='color:#f29e38;'> 20% </color>的生命值。",
      "我方目标施放终结技后，回复等同于生命上限<color style='color:#f29e38;'> 30% </color>的生命值。",
    ],
    Effects: [],
  },
  {
    _id: 616857,
    Path: 128,
    Type: BuffType.Blessing,
    rel: [],
    Rarity: 1,
    Icon: '/IconRogueMage02.webp',
    Name: '顺序写入的轨道',
    Desc: [
      "角色受到致命攻击时，不会陷入无法战斗状态，消耗自身所有能量，回复等同于消耗能量值百分比的<color style='color:#f29e38;'> 50% </color>的生命值，全队每场战斗只能触发1次。",
      "角色受到致命攻击时，不会陷入无法战斗状态，消耗自身所有能量，回复等同于消耗能量值百分比的<color style='color:#f29e38;'> 100% </color>的生命值，全队每场战斗只能触发1次。",
    ],
    Effects: [],
  },
  {
    _id: 616930,
    Path: 129,
    Type: BuffType.Blessing,
    rel: [],
    Rarity: 3,
    Icon: '/IconRogueHarmony04.webp',
    Name: '第一乐章：鸣蛙与骑士',
    Desc: [
      "敌方目标每受到<color style='color:#f29e38;'> 10 </color>点实际削韧值，陷入<color style='color:#f29e38;'> 1 </color>层【<u class='infou'>和音</u>】。",
      "敌方目标每受到<color style='color:#f29e38;'> 10 </color>点实际削韧值，陷入<color style='color:#f29e38;'> 1 </color>层【<u class='infou'>和音</u>】，处于弱点击破状态时受到的实际削韧值也会被计入。",
    ],
    Effects: [61000053],
  },
  {
    _id: 616931,
    Path: 129,
    Type: BuffType.Blessing,
    rel: [],
    Rarity: 3,
    Icon: '/IconRogueHarmony01.webp',
    Name: '第二乐章：牧神的早餐',
    Desc: [
      "我方目标攻击处于弱点击破状态下的敌方目标后，以<color style='color:#f29e38;'> 8% </color>的比例触发1次【<u class='infou'>和音</u>】伤害。",
      "我方目标攻击处于弱点击破状态下的敌方目标后，以<color style='color:#f29e38;'> 10% </color>的比例触发1次【<u class='infou'>和音</u>】伤害，【<u class='infou'>和音</u>】伤害倍率提高原倍率的<color style='color:#f29e38;'> 20% </color>。",
    ],
    Effects: [61000053],
  },
  {
    _id: 616932,
    Path: 129,
    Type: BuffType.Blessing,
    rel: [],
    Rarity: 3,
    Icon: '/IconRogueHarmony01.webp',
    Name: '第三乐章：回旋曲式',
    Desc: [
      "我方目标击破敌方目标弱点时，以<color style='color:#f29e38;'> 50% </color>的比例额外触发其余持有弱点的弱点击破效果。",
      "我方目标击破敌方目标弱点时，以<color style='color:#f29e38;'> 80% </color>的比例额外触发其余持有弱点的弱点击破效果。",
    ],
    Effects: [],
  },
  {
    _id: 616940,
    Path: 129,
    Type: BuffType.Blessing,
    rel: [],
    Rarity: 2,
    Icon: '/IconRogueHarmony04.webp',
    Name: '共晓的时期',
    Desc: [
      "持有【<u class='infou'>和音</u>】的敌方目标被消灭后，使<color style='color:#f29e38;'> 1 </color>个随机相邻目标获得其持有层数的【<u class='infou'>和音</u>】。",
      "持有【<u class='infou'>和音</u>】的敌方目标被消灭后，使<color style='color:#f29e38;'> 2 </color>个随机相邻目标获得其持有层数的【<u class='infou'>和音</u>】。",
    ],
    Effects: [61000053],
  },
  {
    _id: 616941,
    Path: 129,
    Type: BuffType.Blessing,
    rel: [],
    Rarity: 2,
    Icon: '/IconRogueHarmony04.webp',
    Name: '酒神的汲器',
    Desc: [
      "我方目标攻击处于弱点击破状态下的敌方目标后，使其陷入<color style='color:#f29e38;'> 2 </color>层【<u class='infou'>和音</u>】。",
      "我方目标攻击处于弱点击破状态下的敌方目标后，使其陷入<color style='color:#f29e38;'> 3 </color>层【<u class='infou'>和音</u>】。",
    ],
    Effects: [61000053],
  },
  {
    _id: 616942,
    Path: 129,
    Type: BuffType.Blessing,
    rel: [],
    Rarity: 2,
    Icon: '/IconRogueHarmony04.webp',
    Name: '日冕的悸动',
    Desc: [
      "敌方目标每持有1层【<u class='infou'>和音</u>】，受到的击破伤害提高<color style='color:#f29e38;'> 1% </color>。",
      "敌方目标每持有1层【<u class='infou'>和音</u>】，受到的击破伤害提高<color style='color:#f29e38;'> 1.5% </color>。",
    ],
    Effects: [61000053],
  },
  {
    _id: 616943,
    Path: 129,
    Type: BuffType.Blessing,
    rel: [],
    Rarity: 2,
    Icon: '/IconRogueHarmony03.webp',
    Name: '弦乐四重奏',
    Desc: [
      "【<u class='infou'>和音</u>】伤害触发时额外计入<color style='color:#f29e38;'> 5 </color>层，【<u class='infou'>和音</u>】上限提高<color style='color:#f29e38;'> 5 </color>层。",
      "【<u class='infou'>和音</u>】伤害触发时额外计入<color style='color:#f29e38;'> 6 </color>层，【<u class='infou'>和音</u>】上限提高<color style='color:#f29e38;'> 10 </color>层。",
    ],
    Effects: [61000053],
  },
  {
    _id: 616944,
    Path: 129,
    Type: BuffType.Blessing,
    rel: [],
    Rarity: 2,
    Icon: '/IconRogueHarmony01.webp',
    Name: '抑扬五步格',
    Desc: [
      "【<u class='infou'>和音</u>】的伤害倍率提高原倍率的<color style='color:#f29e38;'> 30% </color>。",
      "【<u class='infou'>和音</u>】的伤害倍率提高原倍率的<color style='color:#f29e38;'> 45% </color>。",
    ],
    Effects: [61000053],
  },
  {
    _id: 616945,
    Path: 129,
    Type: BuffType.Blessing,
    rel: [],
    Rarity: 2,
    Icon: '/IconRogueHarmony01.webp',
    Name: '通奏的低音',
    Desc: [
      "我方目标攻击处于弱点击破状态下的敌方目标后，会将本次攻击的削韧值转化为1次<color style='color:#f29e38;'> 50% </color>的<u class='infou'>超击破伤害</u>。",
      "我方目标攻击处于弱点击破状态下的敌方目标后，会将本次攻击的削韧值转化为1次<color style='color:#f29e38;'> 75% </color>的<u class='infou'>超击破伤害</u>。",
    ],
    Effects: [10000015],
  },
  {
    _id: 616946,
    Path: 129,
    Type: BuffType.Blessing,
    rel: [],
    Rarity: 2,
    Icon: '/IconRogueHarmony04.webp',
    Name: '正直的诺姆',
    Desc: [
      "我方目标击破敌方目标弱点时，有<color style='color:#f29e38;'> 100% </color>基础概率使其陷入冻结状态，持续<color style='color:#f29e38;'> 1 </color>回合。",
      "我方目标击破敌方目标弱点时，有<color style='color:#f29e38;'> 150% </color>基础概率使其陷入冻结状态，持续<color style='color:#f29e38;'> 1 </color>回合。",
    ],
    Effects: [],
  },
  {
    _id: 616950,
    Path: 129,
    Type: BuffType.Blessing,
    rel: [],
    Rarity: 1,
    Icon: '/IconRogueHarmony04.webp',
    Name: '凝滞织体',
    Desc: [
      "我方目标击破敌方目标弱点时，使其行动延后<color style='color:#f29e38;'> 20% </color>。",
      "我方目标击破敌方目标弱点时，使其行动延后<color style='color:#f29e38;'> 30% </color>。",
    ],
    Effects: [],
  },
  {
    _id: 616951,
    Path: 129,
    Type: BuffType.Blessing,
    rel: [],
    Rarity: 1,
    Icon: '/IconRogueHarmony01.webp',
    Name: '原始陈述',
    Desc: [
      "我方目标造成的击破伤害提高<color style='color:#f29e38;'> 8% </color>。",
      "我方目标造成的击破伤害提高<color style='color:#f29e38;'> 12% </color>。",
    ],
    Effects: [],
  },
  {
    _id: 616952,
    Path: 129,
    Type: BuffType.Blessing,
    rel: [],
    Rarity: 1,
    Icon: '/IconRogueHarmony01.webp',
    Name: '宁静风暴',
    Desc: [
      "我方目标击破特攻提高<color style='color:#f29e38;'> 30% </color>。",
      "我方目标击破特攻提高<color style='color:#f29e38;'> 45% </color>。",
    ],
    Effects: [],
  },
  {
    _id: 616953,
    Path: 129,
    Type: BuffType.Blessing,
    rel: [],
    Rarity: 1,
    Icon: '/IconRogueHarmony03.webp',
    Name: '直行旋律',
    Desc: [
      "我方目标击破敌方目标弱点时，速度提高<color style='color:#f29e38;'> 12% </color>，持续<color style='color:#f29e38;'> 3 </color>回合。",
      "我方目标击破敌方目标弱点时，速度提高<color style='color:#f29e38;'> 18% </color>，持续<color style='color:#f29e38;'> 3 </color>回合。",
    ],
    Effects: [],
  },
  {
    _id: 616954,
    Path: 129,
    Type: BuffType.Blessing,
    rel: [],
    Rarity: 1,
    Icon: '/IconRogueHarmony01.webp',
    Name: '交叉节拍',
    Desc: [
      "我方目标击破敌方目标弱点时，我方全体目标击破特攻提高<color style='color:#f29e38;'> 40% </color>，持续<color style='color:#f29e38;'> 3 </color>回合。",
      "我方目标击破敌方目标弱点时，我方全体目标击破特攻提高<color style='color:#f29e38;'> 60% </color>，持续<color style='color:#f29e38;'> 3 </color>回合。",
    ],
    Effects: [],
  },
  {
    _id: 616955,
    Path: 129,
    Type: BuffType.Blessing,
    rel: [],
    Rarity: 1,
    Icon: '/IconRogueHarmony04.webp',
    Name: '自由调性',
    Desc: [
      "敌方目标受到的击破伤害提高<color style='color:#f29e38;'> 16% </color>。",
      "敌方目标受到的击破伤害提高<color style='color:#f29e38;'> 24% </color>。",
    ],
    Effects: [],
  },
  {
    _id: 616956,
    Path: 129,
    Type: BuffType.Blessing,
    rel: [],
    Rarity: 1,
    Icon: '/IconRogueHarmony04.webp',
    Name: '厄运爵士',
    Desc: [
      "处于弱点击破状态下的敌方目标，防御力降低<color style='color:#f29e38;'> 15% </color>。",
      "处于弱点击破状态下的敌方目标，防御力降低<color style='color:#f29e38;'> 20% </color>。",
    ],
    Effects: [],
  },
  {
    _id: 616957,
    Path: 129,
    Type: BuffType.Blessing,
    rel: [],
    Rarity: 1,
    Icon: '/IconRogueHarmony02.webp',
    Name: '崭新乐想',
    Desc: [
      "我方目标击破敌方目标弱点时，回复等同于自身生命上限<color style='color:#f29e38;'> 24% </color>的生命值。",
      "我方目标击破敌方目标弱点时，回复等同于自身生命上限<color style='color:#f29e38;'> 36% </color>的生命值。",
    ],
    Effects: [],
  },
]

export { blessings }
