import { type BlessingEquation, BuffType } from '@/libs/du/types'
import { GainType } from './gains'

const equations: BlessingEquation[] = [
  {
    _id: 2105001,
    Path: 121,
    Rarity: 4,
    Icon: '/RogueFormulaIcon_Main_2.png',
    Name: '岁月之神迹',
    Desc: "可消耗 100 点能量施放技能与命途「记忆」产生临界回响，对敌方全体目标造成冰属性伤害，并使其大概率陷入冻结状态，持续<color style='color:#f29e38;'> 1 </color>回合。该冻结状态下，受到忆灵攻击后，会额外受到等同于生命上限<color style='color:#f29e38;'> 8% </color>的真实伤害。敌方目标每次陷入该冻结状态后，最多触发<color style='color:#f29e38;'> 4 </color>次该伤害。",
    Effects: [],
    Need: {
      '121': 16,
    },
    Type: BuffType.Equation,
    rel: [GainType.Freeze, GainType.AdditionalDmg],
    er: 16,
  },
  {
    _id: 2105002,
    Path: 122,
    Rarity: 4,
    Icon: '/RogueFormulaIcon_Main_3.png',
    Name: '死亡之神迹',
    Desc: "可消耗 100 点能量施放技能与命途「虚无」产生临界回响，使敌方全体目标陷入灼烧、触电、裂伤和2层风化状态，持续<color style='color:#f29e38;'> 3 </color>回合。受到角色攻击后上述持续伤害立即产生相当于原伤害<color style='color:#f29e38;'> 25% </color>的伤害。",
    Effects: [],
    Need: {
      '122': 16,
    },
    Type: BuffType.Equation,
    rel: [GainType.DoT, GainType.DotDetonate],
    er: 16,
  },
  {
    _id: 2105003,
    Path: 124,
    Rarity: 4,
    Icon: '/RogueFormulaIcon_Main_5.png',
    Name: '纷争之神迹',
    Desc: "可消耗 100 点能量施放技能与命途「巡猎」产生临界回响，对敌方全体目标造成风属性伤害，并使我方全体行动提前<color style='color:#f29e38;'> 100% </color>，能量上限为 200 。",
    Effects: [],
    Need: {
      '124': 16,
    },
    Type: BuffType.Equation,
    rel: [GainType.SuccessiveAction],
    er: 16,
  },
  {
    _id: 2105004,
    Path: 125,
    Rarity: 4,
    Icon: '/RogueFormulaIcon_Main_6.png',
    Name: '天空之神迹',
    Desc: "可消耗 100 点能量施放技能与命途「毁灭」产生临界回响，对敌方全体目标造成火属性伤害，消耗我方全体生命值至<color style='color:#f29e38;'> 60% </color>，并使我方全体生命值上限提高<color style='color:#f29e38;'> 100% </color>，在回合开始时回复自身已消耗生命值的<color style='color:#f29e38;'> 100% </color>，持续<color style='color:#f29e38;'> 4 </color>回合。",
    Effects: [],
    Need: {
      '125': 16,
    },
    Type: BuffType.Equation,
    rel: [GainType.ConsumeHp, GainType.HEAL, GainType.Healing],
    er: 16,
  },
  {
    _id: 2105005,
    Path: 126,
    Rarity: 4,
    Icon: '/RogueFormulaIcon_Main_7.png',
    Name: '诡计之神迹',
    Desc: "可消耗 100 点能量施放技能与命途「欢愉」产生临界回响，对敌方全体目标造成<color style='color:#f29e38;'> 5 </color>~<color style='color:#f29e38;'> 10 </color>次随机属性的追加攻击伤害，并使我方全体的普攻/战技/终结技伤害被视为追加攻击伤害，持续<color style='color:#f29e38;'> 2 </color>回合。",
    Effects: [],
    Need: {
      '126': 16,
    },
    Type: BuffType.Equation,
    rel: [GainType.FollowUpAtk, GainType.Aftertaste],
    er: 16,
  },
  {
    _id: 2105006,
    Path: 127,
    Rarity: 4,
    Icon: '/RogueFormulaIcon_Main_8.png',
    Name: '浪漫之神迹',
    Desc: "可消耗 100 点能量施放技能与命途「繁育」产生临界回响，使指定我方单体立即行动，恢复<color style='color:#f29e38;'> 5 </color>个战技点，并获得【<u class='infou'>羽化</u>】效果，任意敌方单位被持有【<u class='infou'>羽化</u>】效果的角色消灭后，临界方程恢复<color style='color:#f29e38;'> 50 </color>点能量，能量上限为 200 。",
    Effects: [61000302],
    Need: {
      '127': 16,
    },
    Type: BuffType.Equation,
    rel: [GainType.SuccessiveAction, GainType.Kill],
    er: 16,
  },
  {
    _id: 2105007,
    Path: 128,
    Rarity: 4,
    Icon: '/RogueFormulaIcon_Main_9.png',
    Name: '理性之神迹',
    Desc: "可消耗 100 点能量施放技能与命途「智识」产生临界回响，对敌方全体目标造成少量虚数属性伤害，并将生命上限最高的敌方目标与其他敌方目标连接，使敌方全体陷入【<u class='infou'>中枢链接</u>】状态，并为我方全体恢复等同于能量上限<color style='color:#f29e38;'> 100% </color>的能量。",
    Effects: [61000303],
    Need: {
      '128': 16,
    },
    Type: BuffType.Equation,
    rel: [GainType.DamageSpread, GainType.ENERGY_Charge],
    er: 16,
  },
  {
    _id: 2105008,
    Path: 129,
    Rarity: 4,
    Icon: '/RogueFormulaIcon_Main_10.png',
    Name: '门径之神迹',
    Desc: "可消耗 100 点能量施放技能与命途「同谐」产生临界回响，对敌方全体目标造成量子属性伤害并以<color style='color:#f29e38;'> 1000% </color>的击破特攻击破其弱点，击破弱点时触发所有属性的弱点击破效果。",
    Effects: [],
    Need: {
      '129': 16,
    },
    Type: BuffType.Equation,
    rel: [GainType.MakeBreak],
    er: 16,
  },
  {
    _id: 2104001,
    Path: 129,
    Rarity: 4,
    Icon: '/RogueFormulaIcon_Main_10.png',
    Name: '逐火同盟',
    Desc: "敌方目标受到击破伤害时，额外受到<color style='color:#f29e38;'> 3 </color>次等同于【<u class='infou'>和音</u>】上限<color style='color:#f29e38;'> 35% </color>的伤害，并为我方全体充能等同于各自生命上限的<color style='color:#f29e38;'> 25% </color>的【<u class='infou'>耀变</u>】，该效果敌方目标每回合最多触发1次。",
    Effects: [61000053, 61000051],
    Need: {
      '129': 6,
      '125': 4,
    },
    Type: BuffType.Equation,
    rel: [
      GainType.BreakDmg,
      GainType.Harmony,
      GainType.Destruction,
      GainType.DestructionCharge,
      GainType.AdditionalDmg,
    ],
    er: 8,
  },
  {
    _id: 2104002,
    Path: 129,
    Rarity: 4,
    Icon: '/RogueFormulaIcon_Main_10.png',
    Name: '怠惰指节',
    Desc: "我方目标击破敌方目标弱点时，使其陷入<color style='color:#f29e38;'> 20 </color>层【<u class='infou'>和音</u>】，攻击处于弱点击破状态下的敌方目标后，使其当前承受的持续伤害与【<u class='infou'>和音</u>】立即产生相当于原伤害<color style='color:#f29e38;'> 24% </color>的伤害。",
    Effects: [61000053],
    Need: {
      '129': 6,
      '122': 4,
    },
    Type: BuffType.Equation,
    rel: [
      GainType.MakeBreak,
      GainType.Harmony,
      GainType.HitWeak,
      GainType.DoT,
      GainType.DotDetonate,
    ],
    er: 8,
  },
  {
    _id: 2104003,
    Path: 121,
    Rarity: 4,
    Icon: '/RogueFormulaIcon_Main_2.png',
    Name: '哀歌祭祷',
    Desc: "行动序列上出现【断灭花】：记录我方获得的【<u class='infou'>耀变</u>】，行动时，对敌方全体目标造成等同于记录值<color style='color:#f29e38;'> 5000% </color>+<color style='color:#f29e38;'> 3000% </color><u class='infou'>基础伤害</u>的火属性伤害并清空记录值， 我方每有1层【<u class='infou'>执念</u>】，速度提高<color style='color:#f29e38;'> 1% </color>。我方目标进入战斗或陷入无法战斗状态/忆灵被召唤或消失时，为我方全体目标充能等同于生命上限<color style='color:#f29e38;'> 25% </color>的【<u class='infou'>耀变</u>】。",
    Effects: [61000051, 61000500, 61000049],
    Need: {
      '121': 6,
      '125': 4,
    },
    Type: BuffType.Equation,
    rel: [
      GainType.Destruction,
      GainType.AdditionalDmg,
      GainType.Rememberance,
      GainType.DestructionCharge,
    ],
    er: 8,
  },
  {
    _id: 2104004,
    Path: 121,
    Rarity: 4,
    Icon: '/RogueFormulaIcon_Main_2.png',
    Name: '护誓者',
    Desc: "我方全体累计<color style='color:#f29e38;'> 12 </color>次回合结束时，编队中的第1位角色及其忆灵行动提前 100% ，且在之后的<color style='color:#f29e38;'> 1 </color>回合，回合结束后使自身获得额外回合，在该额外回合内施放攻击后，对攻击目标造成等同于攻击力<color style='color:#f29e38;'> 600% </color>的附加伤害，我方每有1层【<u class='infou'>执念</u>】，该伤害倍率提高原倍率的<color style='color:#f29e38;'> 1% </color>。",
    Effects: [61000049],
    Need: {
      '121': 6,
      '124': 4,
    },
    Type: BuffType.Equation,
    rel: [
      GainType.SuccessiveAction,
      GainType.AdditionalDmg,
      GainType.Rememberance,
    ],
    er: 8,
  },
  {
    _id: 2104005,
    Path: 122,
    Rarity: 4,
    Icon: '/RogueFormulaIcon_Main_3.png',
    Name: '年轮刻工',
    Desc: "敌方目标陷入冻结和持续伤害状态时，有<color style='color:#f29e38;'> 150% </color>的基础概率将该效果扩散给相邻目标，无相邻目标时扩散给自身，单次行动内同一目标只能扩散1次相同效果。单个敌方目标每累计扩散<color style='color:#f29e38;'> 15 </color>次或被消灭，使该目标与相邻目标受到<color style='color:#f29e38;'> 2000% </color><u class='infou'>基础伤害</u>的冰属性伤害，我方每有1层【<u class='infou'>执念</u>】，伤害提高<color style='color:#f29e38;'> 1% </color>。",
    Effects: [61000500, 61000049],
    Need: {
      '122': 6,
      '121': 4,
    },
    Type: BuffType.Equation,
    rel: [
      GainType.Freeze,
      GainType.DoT,
      GainType.DamageSpread,
      GainType.Rememberance,
      GainType.Kill,
      GainType.AdditionalDmg,
    ],
    er: 8,
  },
  {
    _id: 2104006,
    Path: 122,
    Rarity: 4,
    Icon: '/RogueFormulaIcon_Main_3.png',
    Name: '垂语森林',
    Desc: "我方目标累计施放<color style='color:#f29e38;'> 5 </color>次终结技后，【<u class='infou'>呢喃</u>】会对相邻目标造成原伤害倍率<color style='color:#f29e38;'> 60% </color>的伤害，之后每次施放终结技，都会使【<u class='infou'>呢喃</u>】造成的伤害额外提高<color style='color:#f29e38;'> 2% </color>。",
    Effects: [61000050],
    Need: {
      '122': 6,
      '128': 4,
    },
    Type: BuffType.Equation,
    rel: [GainType.UltimateAtk, GainType.ENERGY_Charge, GainType.Nihility],
    er: 8,
  },
  {
    _id: 2104007,
    Path: 125,
    Rarity: 4,
    Icon: '/RogueFormulaIcon_Main_6.png',
    Name: '天空祭司',
    Desc: "我方目标受到攻击后获得<color style='color:#f29e38;'> 2 </color>个【雷祭】，发动反击后获得<color style='color:#f29e38;'> 1 </color>个。拥有<color style='color:#f29e38;'> 6 </color>个【雷祭】时，清空【雷祭】，使造成的终结技伤害提高<color style='color:#f29e38;'> 180% </color>，持续<color style='color:#f29e38;'> 2 </color>回合，并对敌方全体目标造成<color style='color:#f29e38;'> 200% </color>的【<u class='infou'>耀变</u>】伤害，该伤害视为终结技伤害。",
    Effects: [61000051],
    Need: {
      '125': 6,
      '128': 4,
    },
    Type: BuffType.Equation,
    rel: [
      GainType.BeHit,
      GainType.CounterAtk,
      GainType.UltimateAtk,
      GainType.Destruction,
    ],
    er: 8,
  },
  {
    _id: 2104008,
    Path: 125,
    Rarity: 4,
    Icon: '/RogueFormulaIcon_Main_6.png',
    Name: '纷争剧作家',
    Desc: "我方目标累计损失等同于生命上限<color style='color:#f29e38;'> 100% </color>的生命值，或从无法战斗状态恢复时，对敌方全体造成等同于生命上限<color style='color:#f29e38;'> 350% </color>的【<u class='infou'>回味</u>】伤害。角色回合开始时，消耗生命上限的<color style='color:#f29e38;'> 5% </color>，每次触发后使该值提高<color style='color:#f29e38;'> 5% </color>。我方角色首次陷入无法战斗状态时，使当前生命值回复至生命上限的<color style='color:#f29e38;'> 100% </color>，且之后回合开始不再消耗生命值。",
    Effects: [61000054],
    Need: {
      '125': 6,
      '126': 4,
    },
    Type: BuffType.Equation,
    rel: [
      GainType.HEAL,
      GainType.ConsumeHp,
      GainType.Aftertaste,
      GainType.Healing,
    ],
    er: 8,
  },
  {
    _id: 2104009,
    Path: 126,
    Rarity: 4,
    Icon: '/RogueFormulaIcon_Main_7.png',
    Name: '满溢之伤',
    Desc: "行动序列上出现【狂音】：我方目标发动追加攻击后，使其行动提前<color style='color:#f29e38;'> 5% </color>，行动时，编队中的第一位我方目标行动提前<color style='color:#f29e38;'> 100% </color>，施放攻击后造成<color style='color:#f29e38;'> 10 </color>次等同于我方目标攻击力<color style='color:#f29e38;'> 30% </color>的【<u class='infou'>回味</u>】伤害，最多生效<color style='color:#f29e38;'> 4 </color>次攻击，我方全体造成的【<u class='infou'>回味</u>】伤害倍率提高原倍率的<color style='color:#f29e38;'> 100% </color>，且行动序列上出现速度为<color style='color:#f29e38;'> 150 </color>的倒计时，效果持续至倒计时回合开始时。",
    Effects: [61000054],
    Need: {
      '126': 6,
      '124': 4,
    },
    Type: BuffType.Equation,
    rel: [GainType.FollowUpAtk, GainType.Aftertaste, GainType.SuccessiveAction],
    er: 8,
  },
  {
    _id: 2104010,
    Path: 126,
    Rarity: 4,
    Icon: '/RogueFormulaIcon_Main_7.png',
    Name: '无泪花园',
    Desc: "我方目标发动追加攻击后可无视弱点属性额外削减<color style='color:#f29e38;'> 10 </color>点韧性值。我方目标击破敌方目标弱点时，对敌方全体目标造成<color style='color:#f29e38;'> 2 </color>次等同于攻击力<color style='color:#f29e38;'> 150% </color>的【<u class='infou'>回味</u>】伤害，敌方目标每1点韧性上限将使该伤害倍率提高原倍率的<color style='color:#f29e38;'> 1% </color>。",
    Effects: [61000054],
    Need: {
      '126': 6,
      '129': 4,
    },
    Type: BuffType.Equation,
    rel: [
      GainType.FollowUpAtk,
      GainType.CutToughness,
      GainType.MakeBreak,
      GainType.Aftertaste,
    ],
    er: 8,
  },
  {
    _id: 2104011,
    Path: 124,
    Rarity: 4,
    Icon: '/RogueFormulaIcon_Main_5.png',
    Name: '百兽族亲',
    Desc: "不存在持有【兽语】的敌方目标时，我方目标施放攻击后使随机攻击目标持有【兽语】。持有【兽语】的目标累计受到<color style='color:#f29e38;'> 8 </color>次攻击后或被消灭后，受到<color style='color:#f29e38;'> 4000% </color><u class='infou'>基础伤害</u>的雷属性伤害，相邻目标受到<color style='color:#f29e38;'> 3000% </color><u class='infou'>基础伤害</u>的伤害，并使我方全体暴击伤害提高<color style='color:#f29e38;'> 60% </color>，速度提高<color style='color:#f29e38;'> 20% </color>，持续<color style='color:#f29e38;'> 2 </color>回合，若处于【<u class='infou'>蝶魄</u>】状态，则视为额外发动<color style='color:#f29e38;'> 1 </color>次攻击。",
    Effects: [61000500, 61000052],
    Need: {
      '124': 6,
      '127': 4,
    },
    Type: BuffType.Equation,
    rel: [
      GainType.SuccessiveAction,
      GainType.Kill,
      GainType.AdditionalDmg,
      GainType.CRITDMG,
      GainType.SPD,
      GainType.PropagationBless,
    ],
    er: 8,
  },
  {
    _id: 2104012,
    Path: 124,
    Rarity: 4,
    Icon: '/RogueFormulaIcon_Main_5.png',
    Name: '灰河代理',
    Desc: "我方全体每获得<color style='color:#f29e38;'> 10 </color>层【<u class='infou'>会心</u>】或消灭敌方目标后，射出<color style='color:#f29e38;'> 10 </color>根光矢攻击随机敌方目标，每支光矢造成<color style='color:#f29e38;'> 300% </color><u class='infou'>基础伤害</u>的风属性伤害，每个光矢会使【<u class='infou'>呢喃</u>】产生原伤害<color style='color:#f29e38;'> 30% </color>的伤害，并使【<u class='infou'>呢喃</u>】获得等同于我方角色攻击力之和的<color style='color:#f29e38;'> 20% </color>的充能。",
    Effects: [61000055, 61000500, 61000050],
    Need: {
      '124': 6,
      '122': 4,
    },
    Type: BuffType.Equation,
    rel: [
      GainType.CriticalBoost,
      GainType.Kill,
      GainType.AdditionalDmg,
      GainType.Nihility,
      GainType.NihilityCharge,
    ],
    er: 8,
  },
  {
    _id: 2104013,
    Path: 128,
    Rarity: 4,
    Icon: '/RogueFormulaIcon_Main_9.png',
    Name: '山羊学派',
    Desc: "我方全体累计施放<color style='color:#f29e38;'> 2 </color>次终结技后，对随机敌方目标造成<color style='color:#f29e38;'> 2 </color>段等同于<color style='color:#f29e38;'> 600% </color><u class='infou'>基础伤害</u>的风属性伤害，该伤害会对相邻单位造成等同于原伤害<color style='color:#f29e38;'> 30% </color>的伤害。每次触发该效果，都会使伤害段数在本场战斗中增加1段，并使我方目标造成的普攻/战技/终结技伤害提高<color style='color:#f29e38;'> 12% </color>，最多叠加<color style='color:#f29e38;'> 15 </color>次。",
    Effects: [61000500],
    Need: {
      '128': 6,
      '127': 4,
    },
    Type: BuffType.Equation,
    rel: [
      GainType.UltimateAtk,
      GainType.AdditionalDmg,
      GainType.NomralAtk,
      GainType.SkillAtk,
    ],
    er: 8,
  },
  {
    _id: 2104014,
    Path: 128,
    Rarity: 4,
    Icon: '/RogueFormulaIcon_Main_9.png',
    Name: '戏偶师',
    Desc: "我方全体在非【超频】状态下累计施放<color style='color:#f29e38;'> 6 </color>次终结技后，获得【超频】状态：施放终结技发动攻击后，对攻击目标造成<color style='color:#f29e38;'> 3 </color>次等同于攻击者<color style='color:#f29e38;'> 130% </color>攻击力的【<u class='infou'>回味</u>】伤害，施放终结技后退出该状态，编队中的第1位角色激活终结技并将【<u class='infou'>罐中脑</u>】充能至<color style='color:#f29e38;'> 200% </color>，且在施放<color style='color:#f29e38;'> 4 </color>次终结技后才退出该状态。",
    Effects: [61000054, 61000044],
    Need: {
      '128': 6,
      '126': 4,
    },
    Type: BuffType.Equation,
    rel: [GainType.UltimateAtk, GainType.Aftertaste, GainType.Brain_in_a_Vat],
    er: 8,
  },
  {
    _id: 2104015,
    Path: 127,
    Rarity: 4,
    Icon: '/RogueFormulaIcon_Main_8.png',
    Name: '颂歌之家',
    Desc: "【<u class='infou'>蝶魄</u>】所需充能数提高<color style='color:#f29e38;'> 50% </color>。进入【<u class='infou'>蝶魄</u>】状态后，我方全体目标行动提前<color style='color:#f29e38;'> 50% </color>，【<u class='infou'>蝶魄</u>】造成的真实伤害倍率提高原倍率的<color style='color:#f29e38;'> 50% </color>，我方全体每有1层【<u class='infou'>执念</u>】额外提高<color style='color:#f29e38;'> 1% </color>。",
    Effects: [61000052, 61000049],
    Need: {
      '127': 6,
      '121': 4,
    },
    Type: BuffType.Equation,
    rel: [
      GainType.PropagationBless,
      GainType.PropagationBlessCharge,
      GainType.AdditionalDmg,
      GainType.Rememberance,
    ],
    er: 8,
  },
  {
    _id: 2104016,
    Path: 127,
    Rarity: 4,
    Icon: '/RogueFormulaIcon_Main_8.png',
    Name: '蛹衣匠人',
    Desc: "进入【<u class='infou'>蝶魄</u>】状态时使敌方全体目标陷入【茧衣】状态：1回合内无法行动，回合开始时行动延后<color style='color:#f29e38;'> 50% </color>并受到<color style='color:#f29e38;'> 3500% </color><u class='infou'>基础伤害</u>的物理属性伤害。我方处于【<u class='infou'>蝶魄</u>】状态下时，敌方目标每<color style='color:#f29e38;'> 2 </color>个回合将再次陷入【茧衣】状态，并在首次被击破弱点后恢复<color style='color:#f29e38;'> 1 </color>次【<u class='infou'>蝶魄</u>】的攻击次数。",
    Effects: [61000052, 61000500],
    Need: {
      '127': 6,
      '129': 4,
    },
    Type: BuffType.Equation,
    rel: [
      GainType.PropagationBless,
      GainType.MON_act_delay,
      GainType.AdditionalDmg,
      GainType.MakeBreak,
    ],
    er: 8,
  },
  {
    _id: 2103001,
    Path: 129,
    Rarity: 4,
    Icon: '/RogueFormulaIcon_Main_10.png',
    Name: '博爱会社',
    Desc: "我方目标攻击处于弱点击破状态下的敌方目标后，会将本次攻击的削韧值转化为1次<color style='color:#f29e38;'> 100% </color>的<u class='infou'>超击破伤害</u>，处于【<u class='infou'>蝶魄</u>】状态时，该效果额外造成<color style='color:#f29e38;'> 100% </color>的<u class='infou'>超击破伤害</u>。",
    Effects: [10000015, 61000052],
    Need: {
      '129': 4,
      '127': 2,
    },
    Type: BuffType.Equation,
    rel: [GainType.HitWeak, GainType.SuperBreakDmg, GainType.PropagationBless],
    er: 6,
  },
  {
    _id: 2103002,
    Path: 129,
    Rarity: 4,
    Icon: '/RogueFormulaIcon_Main_10.png',
    Name: '共死者',
    Desc: "我方目标击破特攻提高<color style='color:#f29e38;'> 100% </color>，施放攻击击破敌方目标弱点时，获得能够抵消等同于自身生命上限<color style='color:#f29e38;'> 30% </color>伤害的护盾，持续<color style='color:#f29e38;'> 5 </color>回合，并在攻击后对该目标造成等同于【<u class='infou'>耀变</u>】<color style='color:#f29e38;'> 300% </color>的附加伤害。",
    Effects: [61000051],
    Need: {
      '129': 4,
      '125': 2,
    },
    Type: BuffType.Equation,
    rel: [GainType.BREAK, GainType.Shield, GainType.Destruction],
    er: 6,
  },
  {
    _id: 2103003,
    Path: 129,
    Rarity: 4,
    Icon: '/RogueFormulaIcon_Main_10.png',
    Name: '枯萎病人',
    Desc: "敌方目标受到【<u class='infou'>和音</u>】伤害时，额外受到1次等同于原伤害<color style='color:#f29e38;'> 75% </color>的【<u class='infou'>和音</u>】伤害，每陷入1个负面状态，该伤害额外提高<color style='color:#f29e38;'> 2% </color>，最多提高<color style='color:#f29e38;'> 40% </color>。",
    Effects: [61000053],
    Need: {
      '129': 4,
      '122': 2,
    },
    Type: BuffType.Equation,
    rel: [GainType.Harmony, GainType.MON_in_NEG_EFFECT, GainType.AdditionalDmg],
    er: 6,
  },
  {
    _id: 2103004,
    Path: 121,
    Rarity: 4,
    Icon: '/RogueFormulaIcon_Main_2.png',
    Name: '信史追查官',
    Desc: "我方目标受到攻击后，我方全体目标速度提高<color style='color:#f29e38;'> 35% </color>，持续<color style='color:#f29e38;'> 2 </color>回合，并获得<color style='color:#f29e38;'> 2 </color>层【<u class='infou'>会心</u>】效果。忆灵受到攻击时不会失去【<u class='infou'>会心</u>】。",
    Effects: [61000055],
    Need: {
      '121': 4,
      '124': 2,
    },
    Type: BuffType.Equation,
    rel: [GainType.BeHit, GainType.SPD, GainType.CriticalBoost],
    er: 6,
  },
  {
    _id: 2103005,
    Path: 121,
    Rarity: 4,
    Icon: '/RogueFormulaIcon_Main_2.png',
    Name: '围炉氏族',
    Desc: "我方目标【<u class='infou'>执念</u>】上限提高<color style='color:#f29e38;'> 4 </color>层，且全队每层【<u class='infou'>执念</u>】额外提高<color style='color:#f29e38;'> 0.4% </color>生命上限，击破敌方目标弱点时，我方全体目标获得<color style='color:#f29e38;'> 3 </color>层【<u class='infou'>执念</u>】。",
    Effects: [61000049],
    Need: {
      '121': 4,
      '129': 2,
    },
    Type: BuffType.Equation,
    rel: [GainType.Rememberance, GainType.HEAL, GainType.MakeBreak],
    er: 6,
  },
  {
    _id: 2103006,
    Path: 121,
    Rarity: 4,
    Icon: '/RogueFormulaIcon_Main_2.png',
    Name: '苦忆酿酒师',
    Desc: "每层【<u class='infou'>执念</u>】额外提高我方全体目标<color style='color:#f29e38;'> 1.5% </color>攻击力。角色施放攻击后，其忆灵下次攻击视为追加攻击。",
    Effects: [61000049],
    Need: {
      '121': 4,
      '126': 2,
    },
    Type: BuffType.Equation,
    rel: [
      GainType.Rememberance,
      GainType.ATK,
      GainType.FollowUpAtk,
      GainType.Aftertaste,
    ],
    er: 6,
  },
  {
    _id: 2103007,
    Path: 122,
    Rarity: 4,
    Icon: '/RogueFormulaIcon_Main_3.png',
    Name: '处刑人',
    Desc: "敌方目标受到的持续伤害可以暴击，暴击率/暴击伤害等同于我方全体角色暴击率/暴击伤害之和的<color style='color:#f29e38;'> 20% </color>，暴击伤害最高不超过<color style='color:#f29e38;'> 120% </color>。",
    Effects: [],
    Need: {
      '122': 4,
      '124': 2,
    },
    Type: BuffType.Equation,
    rel: [GainType.CRIT, GainType.DoT],
    er: 6,
  },
  {
    _id: 2103008,
    Path: 122,
    Rarity: 4,
    Icon: '/RogueFormulaIcon_Main_3.png',
    Name: '海葬者',
    Desc: "【<u class='infou'>呢喃</u>】的清除阈值提高<color style='color:#f29e38;'> 120% </color>。我方目标发动追加攻击后，使攻击目标的【<u class='infou'>呢喃</u>】产生等同于原伤害<color style='color:#f29e38;'> 20% </color>的伤害。",
    Effects: [61000050],
    Need: {
      '122': 4,
      '126': 2,
    },
    Type: BuffType.Equation,
    rel: [GainType.Nihility, GainType.FollowUpAtk],
    er: 6,
  },
  {
    _id: 2103009,
    Path: 122,
    Rarity: 4,
    Icon: '/RogueFormulaIcon_Main_3.png',
    Name: '焚书官',
    Desc: "我方目标造成的终结技伤害提高<color style='color:#f29e38;'> 160% </color>，施放终结技后，使攻击目标持有的【<u class='infou'>呢喃</u>】获得等同于本次终结技伤害<color style='color:#f29e38;'> 10% </color>的充能，不超过我方角色攻击力之和的<color style='color:#f29e38;'> 300% </color>。",
    Effects: [61000050],
    Need: {
      '122': 4,
      '128': 2,
    },
    Type: BuffType.Equation,
    rel: [GainType.UltimateAtk, GainType.Nihility, GainType.NihilityCharge],
    er: 6,
  },
  {
    _id: 2103010,
    Path: 125,
    Rarity: 4,
    Icon: '/RogueFormulaIcon_Main_6.png',
    Name: '日冕不死鸟',
    Desc: "【<u class='infou'>耀变</u>】充能效率提高<color style='color:#f29e38;'> 50% </color>。【<u class='infou'>蝶魄</u>】状态下施放普攻/战技发动攻击后，对攻击目标造成<color style='color:#f29e38;'> 100% </color>的【<u class='infou'>耀变</u>】伤害。",
    Effects: [61000051, 61000052],
    Need: {
      '125': 4,
      '127': 2,
    },
    Type: BuffType.Equation,
    rel: [
      GainType.DestructionCharge,
      GainType.Destruction,
      GainType.PropagationBless,
      GainType.NomralAtk,
      GainType.SkillAtk,
    ],
    er: 6,
  },
  {
    _id: 2103011,
    Path: 125,
    Rarity: 4,
    Icon: '/RogueFormulaIcon_Main_6.png',
    Name: '噩兆火灵',
    Desc: "我方目标造成【<u class='infou'>耀变</u>】伤害时，敌方目标若处于持续伤害状态，本次【<u class='infou'>耀变</u>】的伤害倍率提高原倍率的<color style='color:#f29e38;'> 60% </color>，每有1个持续伤害状态类型，额外提高<color style='color:#f29e38;'> 15% </color>。",
    Effects: [61000051],
    Need: {
      '125': 4,
      '122': 2,
    },
    Type: BuffType.Equation,
    rel: [GainType.Destruction, GainType.DoT],
    er: 6,
  },
  {
    _id: 2103012,
    Path: 125,
    Rarity: 4,
    Icon: '/RogueFormulaIcon_Main_6.png',
    Name: '悬锋伙友',
    Desc: "我方目标击破敌方目标弱点时，充能等同于生命上限<color style='color:#f29e38;'> 25% </color>的【<u class='infou'>耀变</u>】，若所有敌方目标都处于弱点击破状态，我方目标回合开始时不清除【<u class='infou'>耀变</u>】。",
    Effects: [61000051],
    Need: {
      '125': 4,
      '129': 2,
    },
    Type: BuffType.Equation,
    rel: [GainType.MakeBreak, GainType.DestructionCharge, GainType.Destruction],
    er: 6,
  },
  {
    _id: 2103013,
    Path: 126,
    Rarity: 4,
    Icon: '/RogueFormulaIcon_Main_7.png',
    Name: '阴谋论者',
    Desc: "我方目标发动追加攻击后，有<color style='color:#f29e38;'> 150% </color>基础概率使攻击目标陷入1个随机负面效果，持续<color style='color:#f29e38;'> 2 </color>回合，随机负面效果包括：造成的伤害降低<color style='color:#f29e38;'> 15% </color>，防御力降低<color style='color:#f29e38;'> 30% </color>，速度降低<color style='color:#f29e38;'> 20% </color>。",
    Effects: [],
    Need: {
      '126': 4,
      '122': 2,
    },
    Type: BuffType.Equation,
    rel: [GainType.FollowUpAtk, GainType.MON_in_NEG_EFFECT],
    er: 6,
  },
  {
    _id: 2103014,
    Path: 126,
    Rarity: 4,
    Icon: '/RogueFormulaIcon_Main_7.png',
    Name: '酩酊导师',
    Desc: "我方目标追加攻击造成的暴击伤害提高<color style='color:#f29e38;'> 150% </color>，利用【<u class='infou'>罐中脑</u>】施放终结技对敌方目标造成伤害时，被视为发动了追加攻击。",
    Effects: [61000044],
    Need: {
      '126': 4,
      '128': 2,
    },
    Type: BuffType.Equation,
    rel: [GainType.FollowUpAtk, GainType.Brain_in_a_Vat, GainType.Aftertaste],
    er: 6,
  },
  {
    _id: 2103015,
    Path: 126,
    Rarity: 4,
    Icon: '/RogueFormulaIcon_Main_7.png',
    Name: '笑面刽子手',
    Desc: "我方目标施放攻击后，若生命值百分比大于<color style='color:#f29e38;'> 60% </color>，则消耗<color style='color:#f29e38;'> 5% </color>最大生命值并造成1次等同于自身生命上限<color style='color:#f29e38;'> 120% </color>的【<u class='infou'>回味</u>】伤害。",
    Effects: [61000054],
    Need: {
      '126': 4,
      '125': 2,
    },
    Type: BuffType.Equation,
    rel: [GainType.ConsumeHp, GainType.Aftertaste, GainType.Healing],
    er: 6,
  },
  {
    _id: 2103016,
    Path: 124,
    Rarity: 4,
    Icon: '/RogueFormulaIcon_Main_5.png',
    Name: '巡游乐团',
    Desc: "我方目标施放攻击造成暴击伤害后，在攻击后造成1次等同于原伤害<color style='color:#f29e38;'> 1% </color>~<color style='color:#f29e38;'> 50% </color>的真实伤害，若为追加攻击，则造成原伤害<color style='color:#f29e38;'> 1% </color>~<color style='color:#f29e38;'> 70% </color>的真实伤害",
    Effects: [],
    Need: {
      '124': 4,
      '126': 2,
    },
    Type: BuffType.Equation,
    rel: [
      GainType.CRIT,
      GainType.AdditionalDmg,
      GainType.FollowUpAtk,
      GainType.Aftertaste,
    ],
    er: 6,
  },
  {
    _id: 2103017,
    Path: 124,
    Rarity: 4,
    Icon: '/RogueFormulaIcon_Main_5.png',
    Name: '猎冕金爪',
    Desc: "我方目标每获得1%的行动提前效果，都会使下回合内造成的伤害提高<color style='color:#f29e38;'> 2% </color>，最多计入<color style='color:#f29e38;'> 100% </color>，该效果对处于【<u class='infou'>蝶魄</u>】状态下的目标额外提高<color style='color:#f29e38;'> 30% </color>。",
    Effects: [61000052],
    Need: {
      '124': 4,
      '127': 2,
    },
    Type: BuffType.Equation,
    rel: [
      GainType.SuccessiveAction,
      GainType.DMG_Gain,
      GainType.PropagationBless,
    ],
    er: 6,
  },
  {
    _id: 2103018,
    Path: 124,
    Rarity: 4,
    Icon: '/RogueFormulaIcon_Main_5.png',
    Name: '追忆弓箭手',
    Desc: "【<u class='infou'>会心</u>】上限提高<color style='color:#f29e38;'> 4 </color>层。每层【<u class='infou'>会心</u>】使速度提高<color style='color:#f29e38;'> 3% </color>，忆灵额外提高<color style='color:#f29e38;'> 2% </color>。",
    Effects: [61000055],
    Need: {
      '124': 4,
      '121': 2,
    },
    Type: BuffType.Equation,
    rel: [GainType.CriticalBoost, GainType.SPD],
    er: 6,
  },
  {
    _id: 2103019,
    Path: 128,
    Rarity: 4,
    Icon: '/RogueFormulaIcon_Main_9.png',
    Name: '兵戈学者',
    Desc: "我方目标击破敌方目标弱点时，为【<u class='infou'>罐中脑</u>】充能 <color style='color:#f29e38;'> 20% </color>，并恢复等同于能量上限<color style='color:#f29e38;'> 10% </color>的能量，消灭敌方目标后，恢复等同于能量上限<color style='color:#f29e38;'> 60% </color>的能量。",
    Effects: [61000044],
    Need: {
      '128': 4,
      '124': 2,
    },
    Type: BuffType.Equation,
    rel: [
      GainType.MakeBreak,
      GainType.Brain_in_a_Vat_Charge,
      GainType.Brain_in_a_Vat,
      GainType.ENERGY_Charge,
      GainType.Kill,
    ],
    er: 6,
  },
  {
    _id: 2103020,
    Path: 128,
    Rarity: 4,
    Icon: '/RogueFormulaIcon_Main_9.png',
    Name: '禁识殉道者',
    Desc: "我方目标施放终结技时，使我方全体目标消耗等同于当前生命值<color style='color:#f29e38;'> 5% </color>的生命值，且造成的伤害提高<color style='color:#f29e38;'> 30% </color>，最多叠加<color style='color:#f29e38;'> 4 </color>层，持续<color style='color:#f29e38;'> 2 </color>回合。",
    Effects: [],
    Need: {
      '128': 4,
      '125': 2,
    },
    Type: BuffType.Equation,
    rel: [GainType.UltimateAtk, GainType.ConsumeHp, GainType.DMG_Gain],
    er: 6,
  },
  {
    _id: 2103021,
    Path: 128,
    Rarity: 4,
    Icon: '/RogueFormulaIcon_Main_9.png',
    Name: '赤陶学派',
    Desc: "忆灵施放攻击后，为忆师的【<u class='infou'>罐中脑</u>】充能<color style='color:#f29e38;'> 8% </color>。忆师使用【<u class='infou'>罐中脑</u>】释放终结技后，忆灵的伤害提高<color style='color:#f29e38;'> 240% </color>，持续<color style='color:#f29e38;'> 4 </color>回合。",
    Effects: [61000044],
    Need: {
      '128': 4,
      '121': 2,
    },
    Type: BuffType.Equation,
    rel: [
      GainType.MemElfAtk,
      GainType.Brain_in_a_Vat_Charge,
      GainType.Brain_in_a_Vat,
      GainType.UltimateAtk,
      GainType.DMG_Gain,
    ],
    er: 6,
  },
  {
    _id: 2103022,
    Path: 127,
    Rarity: 4,
    Icon: '/RogueFormulaIcon_Main_8.png',
    Name: '织书神机',
    Desc: "我方目标进入【<u class='infou'>蝶魄</u>】后，施放的终结技也能造成【<u class='infou'>蝶魄</u>】的真实伤害，并使【<u class='infou'>蝶魄</u>】的攻击次数增加<color style='color:#f29e38;'> 2 </color>次，每名我方目标最多触发1次该效果。",
    Effects: [61000052],
    Need: {
      '127': 4,
      '128': 2,
    },
    Type: BuffType.Equation,
    rel: [
      GainType.PropagationBless,
      GainType.UltimateAtk,
      GainType.AdditionalDmg,
    ],
    er: 6,
  },
  {
    _id: 2103023,
    Path: 127,
    Rarity: 4,
    Icon: '/RogueFormulaIcon_Main_8.png',
    Name: '忆种培育师',
    Desc: "【<u class='infou'>蝶魄</u>】的真实伤害倍率提高原倍率的<color style='color:#f29e38;'> 60% </color>，攻击次数增加<color style='color:#f29e38;'> 4 </color>次。忆灵施放攻击后可造成【<u class='infou'>蝶魄</u>】的真实伤害并消耗其攻击次数。",
    Effects: [61000052],
    Need: {
      '127': 4,
      '121': 2,
    },
    Type: BuffType.Equation,
    rel: [GainType.PropagationBless, GainType.MemElfAtk],
    er: 6,
  },
  {
    _id: 2103024,
    Path: 127,
    Rarity: 4,
    Icon: '/RogueFormulaIcon_Main_8.png',
    Name: '遗孤抚养院',
    Desc: "我方目标击破敌方目标弱点时，回复<color style='color:#f29e38;'> 1 </color>点战技点。使用普攻和战技施放攻击后，造成<color style='color:#f29e38;'> 5 </color>点额外削韧值，并附加<color style='color:#f29e38;'> 2 </color>层【<u class='infou'>和音</u>】。",
    Effects: [61000053],
    Need: {
      '127': 4,
      '129': 2,
    },
    Type: BuffType.Equation,
    rel: [
      GainType.MakeBreak,
      GainType.Point,
      GainType.NomralAtk,
      GainType.SkillAtk,
      GainType.CutToughness,
      GainType.Harmony,
    ],
    er: 6,
  },
  {
    _id: 2102001,
    Path: 129,
    Rarity: 4,
    Icon: '/RogueFormulaIcon_Main_10.png',
    Name: '追火讯使',
    Desc: "我方目标弱点击破效率提高<color style='color:#f29e38;'> 20% </color>，击破敌方目标弱点后，速度提高<color style='color:#f29e38;'> 10% </color>，攻击力提高<color style='color:#f29e38;'> 30% </color>，持续<color style='color:#f29e38;'> 2 </color>回合。",
    Effects: [],
    Need: {
      '129': 2,
      '124': 2,
    },
    Type: BuffType.Equation,
    rel: [
      GainType.BreakEfficiency,
      GainType.MakeBreak,
      GainType.SPD,
      GainType.ATK,
    ],
    er: 4,
  },
  {
    _id: 2102002,
    Path: 129,
    Rarity: 4,
    Icon: '/RogueFormulaIcon_Main_10.png',
    Name: '黎明剧团',
    Desc: "【<u class='infou'>和音</u>】伤害倍率提高原倍率<color style='color:#f29e38;'> 50% </color>，我方目标发动追加攻击后为目标添加<color style='color:#f29e38;'> 1 </color>层【<u class='infou'>和音</u>】。",
    Effects: [61000053],
    Need: {
      '129': 2,
      '126': 2,
    },
    Type: BuffType.Equation,
    rel: [GainType.Harmony, GainType.FollowUpAtk],
    er: 4,
  },
  {
    _id: 2102003,
    Path: 129,
    Rarity: 4,
    Icon: '/RogueFormulaIcon_Main_10.png',
    Name: '迷途隐者',
    Desc: "我方目标施放攻击使敌方目标陷入了负面状态时，为其添加<color style='color:#f29e38;'> 1 </color>层【<u class='infou'>和音</u>】，如果目标处于弱点击破状态则添加的层数翻倍。",
    Effects: [61000053],
    Need: {
      '129': 2,
      '122': 2,
    },
    Type: BuffType.Equation,
    rel: [GainType.MON_in_NEG_EFFECT, GainType.Harmony, GainType.HitWeak],
    er: 4,
  },
  {
    _id: 2102004,
    Path: 129,
    Rarity: 4,
    Icon: '/RogueFormulaIcon_Main_10.png',
    Name: '回响庭',
    Desc: "每层【<u class='infou'>执念</u>】将使击破特攻提高<color style='color:#f29e38;'> 0.8% </color>，忆灵的击破特攻额外再提高<color style='color:#f29e38;'> 0.5% </color>。",
    Effects: [61000049],
    Need: {
      '129': 2,
      '121': 2,
    },
    Type: BuffType.Equation,
    rel: [GainType.Rememberance, GainType.BREAK],
    er: 4,
  },
  {
    _id: 2102005,
    Path: 121,
    Rarity: 4,
    Icon: '/RogueFormulaIcon_Main_2.png',
    Name: '岁月祭司',
    Desc: "我方目标持有【<u class='infou'>执念</u>】时，全属性抗性穿透提高<color style='color:#f29e38;'> 15% </color>。每层【<u class='infou'>执念</u>】使我方全体目标击破特攻提高<color style='color:#f29e38;'> 0.5% </color>。",
    Effects: [61000049],
    Need: {
      '121': 2,
      '129': 2,
    },
    Type: BuffType.Equation,
    rel: [GainType.Rememberance, GainType.DMG_Gain],
    er: 4,
  },
  {
    _id: 2102006,
    Path: 121,
    Rarity: 4,
    Icon: '/RogueFormulaIcon_Main_2.png',
    Name: '赋生雕塑家',
    Desc: "忆灵造成的伤害提高<color style='color:#f29e38;'> 80% </color>，施放攻击后，忆师下次施放普攻/战技造成的伤害提高<color style='color:#f29e38;'> 80% </color>。",
    Effects: [],
    Need: {
      '121': 2,
      '127': 2,
    },
    Type: BuffType.Equation,
    rel: [GainType.MemElfAtk, GainType.NomralAtk, GainType.SkillAtk],
    er: 4,
  },
  {
    _id: 2102007,
    Path: 121,
    Rarity: 4,
    Icon: '/RogueFormulaIcon_Main_2.png',
    Name: '夜帷裁断官',
    Desc: "忆灵消失时，使我方全体目标速度提高<color style='color:#f29e38;'> 25% </color>、暴击伤害提高<color style='color:#f29e38;'> 100% </color>，持续<color style='color:#f29e38;'> 5 </color>回合。",
    Effects: [],
    Need: {
      '121': 2,
      '124': 2,
    },
    Type: BuffType.Equation,
    rel: [GainType.SPD, GainType.CRITDMG],
    er: 4,
  },
  {
    _id: 2102008,
    Path: 121,
    Rarity: 4,
    Icon: '/RogueFormulaIcon_Main_2.png',
    Name: '吟游诗人',
    Desc: "我方【<u class='infou'>执念</u>】层数超过<color style='color:#f29e38;'> 70 </color>层时，使终结技伤害提高<color style='color:#f29e38;'> 75% </color>，忆灵伤害提高<color style='color:#f29e38;'> 75% </color>。",
    Effects: [61000049],
    Need: {
      '121': 2,
      '128': 2,
    },
    Type: BuffType.Equation,
    rel: [GainType.Rememberance, GainType.UltimateAtk, GainType.MemElfAtk],
    er: 4,
  },
  {
    _id: 2102009,
    Path: 122,
    Rarity: 4,
    Icon: '/RogueFormulaIcon_Main_3.png',
    Name: '灰黯朝圣者',
    Desc: "敌方目标进入战斗时，陷入裂伤状态。裂伤状态下，敌方目标每回合开始时受到等同于自身<color style='color:#f29e38;'> 10% </color>生命上限的物理属性持续伤害，最多不超过我方全体目标生命值之和的<color style='color:#f29e38;'> 200% </color>。",
    Effects: [],
    Need: {
      '122': 2,
      '125': 2,
    },
    Type: BuffType.Equation,
    rel: [GainType.DoT],
    er: 4,
  },
  {
    _id: 2102010,
    Path: 122,
    Rarity: 4,
    Icon: '/RogueFormulaIcon_Main_3.png',
    Name: '冥河渡客',
    Desc: "我方目标造成的持续伤害提高<color style='color:#f29e38;'> 50% </color>。敌方目标进入战斗时，陷入【觉察】状态。回合开始时，受到<color style='color:#f29e38;'> 75% </color><u class='infou'>基础伤害</u>的火属性持续伤害，我方全体目标每有一层【<u class='infou'>执念</u>】该伤害提高<color style='color:#f29e38;'> 1% </color>。",
    Effects: [61000049],
    Need: {
      '122': 2,
      '121': 2,
    },
    Type: BuffType.Equation,
    rel: [GainType.DoT_By_Char, GainType.Rememberance, GainType.DoT],
    er: 4,
  },
  {
    _id: 2102011,
    Path: 122,
    Rarity: 4,
    Icon: '/RogueFormulaIcon_Main_3.png',
    Name: '失意结社',
    Desc: "敌方目标被消灭时，每陷入灼烧、触电、裂伤、风化状态中的1种，我方全体回复<color style='color:#f29e38;'> 5 </color>点能量。",
    Effects: [],
    Need: {
      '122': 2,
      '128': 2,
    },
    Type: BuffType.Equation,
    rel: [GainType.Kill, GainType.DoT, GainType.ENERGY_Charge],
    er: 4,
  },
  {
    _id: 2102012,
    Path: 122,
    Rarity: 4,
    Icon: '/RogueFormulaIcon_Main_3.png',
    Name: '种骨者',
    Desc: "【<u class='infou'>呢喃</u>】的清除阈值提高<color style='color:#f29e38;'> 80% </color>。消耗战技点后为敌方全体【<u class='infou'>呢喃</u>】充能，充能值等同于清除阈值的<color style='color:#f29e38;'> 4% </color>。",
    Effects: [61000050],
    Need: {
      '122': 2,
      '127': 2,
    },
    Type: BuffType.Equation,
    rel: [GainType.Nihility, GainType.NihilityCharge, GainType.Point],
    er: 4,
  },
  {
    _id: 2102013,
    Path: 125,
    Rarity: 4,
    Icon: '/RogueFormulaIcon_Main_6.png',
    Name: '红月使者',
    Desc: "【<u class='infou'>耀变</u>】基础值提高<color style='color:#f29e38;'> 50% </color>，我方目标发动追加攻击后，使当前生命值百分比最低的我方目标回复等同于自身生命上限<color style='color:#f29e38;'> 10% </color>的生命值。",
    Effects: [61000051],
    Need: {
      '125': 2,
      '126': 2,
    },
    Type: BuffType.Equation,
    rel: [GainType.Destruction, GainType.FollowUpAtk, GainType.Healing],
    er: 4,
  },
  {
    _id: 2102014,
    Path: 125,
    Rarity: 4,
    Icon: '/RogueFormulaIcon_Main_6.png',
    Name: '金血愚子',
    Desc: "敌方目标被消灭时，使【<u class='infou'>耀变</u>】 充能效率提高<color style='color:#f29e38;'> 18% </color>，最多叠加<color style='color:#f29e38;'> 3 </color>层。并使我方全体回复等同于生命上限<color style='color:#f29e38;'> 30% </color>的生命值。",
    Effects: [61000051],
    Need: {
      '125': 2,
      '124': 2,
    },
    Type: BuffType.Equation,
    rel: [
      GainType.Kill,
      GainType.DestructionCharge,
      GainType.Destruction,
      GainType.Healing,
    ],
    er: 4,
  },
  {
    _id: 2102015,
    Path: 125,
    Rarity: 4,
    Icon: '/RogueFormulaIcon_Main_6.png',
    Name: '残阳之牙',
    Desc: "我方目标效果抵抗提高<color style='color:#f29e38;'> 20% </color>，造成的【<u class='infou'>耀变</u>】伤害提高<color style='color:#f29e38;'> 40% </color>，抵抗受到的负面效果时，对目标造成等同于【<u class='infou'>耀变</u>】<color style='color:#f29e38;'> 60% </color>的附加伤害，该伤害无法消灭敌方目标。",
    Effects: [61000051],
    Need: {
      '125': 2,
      '122': 2,
    },
    Type: BuffType.Equation,
    rel: [GainType.RESIST, GainType.Destruction, GainType.AdditionalDmg],
    er: 4,
  },
  {
    _id: 2102016,
    Path: 125,
    Rarity: 4,
    Icon: '/RogueFormulaIcon_Main_6.png',
    Name: '天锋军团',
    Desc: "获得的护盾量提高<color style='color:#f29e38;'> 30% </color>，击破敌方目标弱点后，我方全体获得等同于生命上限<color style='color:#f29e38;'> 15% </color>的护盾，持续<color style='color:#f29e38;'> 2 </color>回合。",
    Effects: [],
    Need: {
      '125': 2,
      '129': 2,
    },
    Type: BuffType.Equation,
    rel: [GainType.Shield, GainType.MakeBreak],
    er: 4,
  },
  {
    _id: 2102017,
    Path: 126,
    Rarity: 4,
    Icon: '/RogueFormulaIcon_Main_7.png',
    Name: '水漫琴师',
    Desc: "我方目标发动追加攻击后，对攻击目标造成<color style='color:#f29e38;'> 70% </color>的【<u class='infou'>耀变</u>】伤害。",
    Effects: [61000051],
    Need: {
      '126': 2,
      '125': 2,
    },
    Type: BuffType.Equation,
    rel: [GainType.FollowUpAtk, GainType.Destruction],
    er: 4,
  },
  {
    _id: 2102018,
    Path: 126,
    Rarity: 4,
    Icon: '/RogueFormulaIcon_Main_7.png',
    Name: '逐浪海妖',
    Desc: "我方目标造成的追加攻击伤害提高<color style='color:#f29e38;'> 75% </color>，发动追加攻击后，有<color style='color:#f29e38;'> 30% </color>固定概率恢复1个战技点。",
    Effects: [GainType.FollowUpAtk, GainType.Aftertaste, GainType.Point],
    Need: {
      '126': 2,
      '127': 2,
    },
    Type: BuffType.Equation,
    rel: [GainType.FollowUpAtk, GainType.Aftertaste, GainType.Point],
    er: 4,
  },
  {
    _id: 2102019,
    Path: 126,
    Rarity: 4,
    Icon: '/RogueFormulaIcon_Main_7.png',
    Name: '诸神诡辩家',
    Desc: "我方目标施放终结技后，使下次施放攻击后，对攻击目标造成<color style='color:#f29e38;'> 1 </color>次等同于攻击力<color style='color:#f29e38;'> 240% </color>的【<u class='infou'>回味</u>】伤害。",
    Effects: [61000054],
    Need: {
      '126': 2,
      '128': 2,
    },
    Type: BuffType.Equation,
    rel: [GainType.UltimateAtk, GainType.Aftertaste],
    er: 4,
  },
  {
    _id: 2102020,
    Path: 126,
    Rarity: 4,
    Icon: '/RogueFormulaIcon_Main_7.png',
    Name: '沉醉之船',
    Desc: "我方目标造成的【<u class='infou'>回味</u>】伤害，可以无视弱点属性削减敌方目标<color style='color:#f29e38;'> 1 </color>点韧性值，单次攻击内对每名敌方目标最多触发<color style='color:#f29e38;'> 10 </color>次该效果。",
    Effects: [61000054],
    Need: {
      '126': 2,
      '129': 2,
    },
    Type: BuffType.Equation,
    rel: [GainType.Aftertaste, GainType.CutToughness],
    er: 4,
  },
  {
    _id: 2102021,
    Path: 124,
    Rarity: 4,
    Icon: '/RogueFormulaIcon_Main_5.png',
    Name: '巨兽猎手',
    Desc: "每层【<u class='infou'>会心</u>】额外使暴击伤害提高<color style='color:#f29e38;'> 8% </color>，我方目标施放终结技时继承并获得<color style='color:#f29e38;'> 2 </color>层【<u class='infou'>会心</u>】。",
    Effects: [61000055],
    Need: {
      '124': 2,
      '128': 2,
    },
    Type: BuffType.Equation,
    rel: [GainType.CriticalBoost, GainType.CRITDMG],
    er: 4,
  },
  {
    _id: 2102022,
    Path: 124,
    Rarity: 4,
    Icon: '/RogueFormulaIcon_Main_5.png',
    Name: '清洗者',
    Desc: "我方目标对处于弱点击破状态下的敌方目标造成伤害时，每层【<u class='infou'>会心</u>】额外使暴击率提高<color style='color:#f29e38;'> 4% </color>，暴击伤害提高<color style='color:#f29e38;'> 30% </color>。",
    Effects: [61000055],
    Need: {
      '124': 2,
      '129': 2,
    },
    Type: BuffType.Equation,
    rel: [
      GainType.HitWeak,
      GainType.CriticalBoost,
      GainType.CRIT,
      GainType.CRITDMG,
    ],
    er: 4,
  },
  {
    _id: 2102023,
    Path: 124,
    Rarity: 4,
    Icon: '/RogueFormulaIcon_Main_5.png',
    Name: '悬锋旅人',
    Desc: "我方目标获得护盾量提高<color style='color:#f29e38;'> 30% </color>。我方目标受到攻击后，若在该次攻击内未受到伤害，只会失去<color style='color:#f29e38;'> 1 </color>层【<u class='infou'>会心</u>】。",
    Effects: [61000055],
    Need: {
      '124': 2,
      '125': 2,
    },
    Type: BuffType.Equation,
    rel: [GainType.Shield, GainType.BeHit],
    er: 4,
  },
  {
    _id: 2102024,
    Path: 124,
    Rarity: 4,
    Icon: '/RogueFormulaIcon_Main_5.png',
    Name: '律法裁断官',
    Desc: "【<u class='infou'>呢喃</u>】的充能每有清除阈值的1%，敌方目标受到的暴击伤害提高<color style='color:#f29e38;'> 1% </color>，最多提高<color style='color:#f29e38;'> 150% </color>。",
    Effects: [61000050],
    Need: {
      '124': 2,
      '122': 2,
    },
    Type: BuffType.Equation,
    rel: [GainType.Nihility, GainType.CRITDMG],
    er: 4,
  },
  {
    _id: 2102025,
    Path: 128,
    Rarity: 4,
    Icon: '/RogueFormulaIcon_Main_9.png',
    Name: '仙女木',
    Desc: "我方目标每消耗1个战技点，造成的终结技伤害提高<color style='color:#f29e38;'> 65% </color>，最多提高<color style='color:#f29e38;'> 130% </color>，持续至施放终结技后。",
    Effects: [],
    Need: {
      '128': 2,
      '127': 2,
    },
    Type: BuffType.Equation,
    rel: [GainType.Point, GainType.UltimateAtk],
    er: 4,
  },
  {
    _id: 2102026,
    Path: 128,
    Rarity: 4,
    Icon: '/RogueFormulaIcon_Main_9.png',
    Name: '沙粒记述官',
    Desc: "角色施放终结技时，使自身与忆灵获得<color style='color:#f29e38;'> 2 </color>层【<u class='infou'>执念</u>】，并使速度提高<color style='color:#f29e38;'> 15% </color>，攻击力提高<color style='color:#f29e38;'> 70% </color>，持续<color style='color:#f29e38;'> 3 </color>回合。",
    Effects: [61000049],
    Need: {
      '128': 2,
      '121': 2,
    },
    Type: BuffType.Equation,
    rel: [
      GainType.UltimateAtk,
      GainType.Rememberance,
      GainType.SPD,
      GainType.ATK,
    ],
    er: 4,
  },
  {
    _id: 2102027,
    Path: 128,
    Rarity: 4,
    Icon: '/RogueFormulaIcon_Main_9.png',
    Name: '莲食学派',
    Desc: "我方目标施放终结技时，每消耗<color style='color:#f29e38;'> 50 </color>点能量，使攻击力提高<color style='color:#f29e38;'> 5% </color>，并使造成的【<u class='infou'>回味</u>】伤害倍率提高原倍率的<color style='color:#f29e38;'> 2% </color>，最多叠加<color style='color:#f29e38;'> 20 </color>层，持续<color style='color:#f29e38;'> 3 </color>回合，每次施放终结技时至少视为消耗了<color style='color:#f29e38;'> 80 </color>点能量。",
    Effects: [61000054],
    Need: {
      '128': 2,
      '126': 2,
    },
    Type: BuffType.Equation,
    rel: [
      GainType.UltimateAtk,
      GainType.ENERGY_Charge,
      GainType.ATK,
      GainType.Aftertaste,
    ],
    er: 4,
  },
  {
    _id: 2102028,
    Path: 128,
    Rarity: 4,
    Icon: '/RogueFormulaIcon_Main_9.png',
    Name: '螺旋之子',
    Desc: "我方目标【<u class='infou'>罐中脑</u>】达到 100% 时，攻击提高<color style='color:#f29e38;'> 80% </color>，施放攻击后，对攻击目标中生命值最高的敌方目标造成等同于攻击力<color style='color:#f29e38;'> 80% </color>的附加伤害，持续<color style='color:#f29e38;'> 3 </color>回合。",
    Effects: [61000044],
    Need: {
      '128': 2,
      '124': 2,
    },
    Type: BuffType.Equation,
    rel: [GainType.Brain_in_a_Vat, GainType.ATK],
    er: 4,
  },
  {
    _id: 2102029,
    Path: 127,
    Rarity: 4,
    Icon: '/RogueFormulaIcon_Main_8.png',
    Name: '金实秘仪',
    Desc: "我方目标造成的普攻/战技伤害提高<color style='color:#f29e38;'> 80% </color>，施放普攻时，若生命值百分比大于等于<color style='color:#f29e38;'> 50% </color>，则消耗等同于生命上限<color style='color:#f29e38;'> 10% </color>的生命值并额外恢复1点战技点。",
    Effects: [],
    Need: {
      '127': 2,
      '125': 2,
    },
    Type: BuffType.Equation,
    rel: [
      GainType.NomralAtk,
      GainType.SkillAtk,
      GainType.ConsumeHp,
      GainType.Point,
    ],
    er: 4,
  },
  {
    _id: 2102030,
    Path: 127,
    Rarity: 4,
    Icon: '/RogueFormulaIcon_Main_8.png',
    Name: '磐岩居庭',
    Desc: "【<u class='infou'>蝶魄</u>】的真实伤害提高原倍率的<color style='color:#f29e38;'> 35% </color>，敌方目标每有1个负面效果，额外提高原倍率的<color style='color:#f29e38;'> 1% </color>。",
    Effects: [61000052],
    Need: {
      '127': 2,
      '122': 2,
    },
    Type: BuffType.Equation,
    rel: [
      GainType.PropagationBless,
      GainType.AdditionalDmg,
      GainType.MON_in_NEG_EFFECT,
    ],
    er: 4,
  },
  {
    _id: 2102031,
    Path: 127,
    Rarity: 4,
    Icon: '/RogueFormulaIcon_Main_8.png',
    Name: '创生若虫',
    Desc: "忆灵施放攻击后，【<u class='infou'>魂茧</u>】充能<color style='color:#f29e38;'> 15% </color>，并有<color style='color:#f29e38;'> 40% </color>概率恢复<color style='color:#f29e38;'> 1 </color>点战技点。",
    Effects: [61000052],
    Need: {
      '127': 2,
      '121': 2,
    },
    Type: BuffType.Equation,
    rel: [
      GainType.MemElfAtk,
      GainType.PropagationBlessCharge,
      GainType.PropagationBless,
      GainType.Point,
    ],
    er: 4,
  },
  {
    _id: 2102032,
    Path: 127,
    Rarity: 4,
    Icon: '/RogueFormulaIcon_Main_8.png',
    Name: '贼乐师',
    Desc: "我方目标每消耗1个战技点，都可以使下一次攻击后，对攻击目标造成等同于攻击力<color style='color:#f29e38;'> 70% </color>的【<u class='infou'>回味</u>】伤害，最多叠加<color style='color:#f29e38;'> 3 </color>层。",
    Effects: [61000054],
    Need: {
      '127': 2,
      '126': 2,
    },
    Type: BuffType.Equation,
    rel: [GainType.Point, GainType.Aftertaste],
    er: 4,
  },
]

equations.forEach((e) => {
  const paths = Object.keys(e.Need).map((i) => Number(i))
  e.rel.push(e.Path as number as GainType, ...paths.filter((i) => i !== e.Path))
})

export { equations }
