import { BlessingExtra } from '@/libs/du/constants'
import { type Blessing, BuffType } from '@/libs/du/types'
import { sortAllBlessings } from '@/libs/search/sort'
import { GainType } from './gain_types'

const blessings: Array<Blessing> = [
  {
    _id: 615031,
    Type: BuffType.Blessing,
    Path: 120,
    Rarity: 3,
    Icon: '/IconRogueKnight01.webp',
    Name: '神性构筑 • 超静定场',
    Desc: [
      "角色施放攻击后，对受到攻击的敌方目标造成等同于角色当前护盾量<color style='color:#f29e38;'> 100% </color>的【<u class='infou'>反震</u>】伤害。",
      "角色施放攻击后，对受到攻击的敌方目标造成等同于角色当前护盾量<color style='color:#f29e38;'> 100% </color>+队友当前护盾总量<color style='color:#f29e38;'> 20% </color>的【<u class='infou'>反震</u>】伤害。",
    ],
    Effects: [BlessingExtra.Quake],
    rel: [GainType.BeHit, GainType.Shield, GainType.QuakeDmg],
  },
  {
    _id: 615032,
    Type: BuffType.Blessing,
    Path: 120,
    Rarity: 3,
    Icon: '/IconRogueKnight02.webp',
    Name: '神性构筑 • 宏观偏析',
    Desc: [
      "角色受到攻击后，对攻击者造成等同于受到攻击前护盾量<color style='color:#f29e38;'> 280% </color>的【<u class='infou'>反震</u>】伤害。该伤害无法消灭敌方目标。",
      "角色受到攻击后，对攻击者造成等同于受到攻击前护盾量<color style='color:#f29e38;'> 420% </color>的【<u class='infou'>反震</u>】伤害。该伤害无法消灭敌方目标。",
    ],
    Effects: [],
    rel: [GainType.Shield],
  },
  {
    _id: 615040,
    Type: BuffType.Blessing,
    Path: 120,
    Rarity: 2,
    Icon: '/IconRogueKnight01.webp',
    Name: '星间构筑 • 切变结构',
    Desc: [
      "角色获得特殊护盾，获得其他护盾时该护盾会增加获取护盾量<color style='color:#f29e38;'> 100% </color>的护盾量。超过角色生命上限<color style='color:#f29e38;'> 30% </color>的部分，会在角色回合开始时失去<color style='color:#f29e38;'> 90% </color>。",
      "角色获得特殊护盾，获得其他护盾时该护盾会增加获取护盾量<color style='color:#f29e38;'> 100% </color>的护盾量。超过角色生命上限<color style='color:#f29e38;'> 45% </color>的部分，会在角色回合开始时失去<color style='color:#f29e38;'> 85% </color>。",
    ],
    Effects: [BlessingExtra.Quake],
    rel: [GainType.QuakeDmg, GainType.DamageSpread],
  },
  {
    _id: 615041,
    Type: BuffType.Blessing,
    Path: 120,
    Rarity: 2,
    Icon: '/IconRogueKnight01.webp',
    Name: '星间构筑 • 固溶强化',
    Desc: [
      "角色对敌方目标造成的【<u class='infou'>反震</u>】伤害提高<color style='color:#f29e38;'> 10% </color>，且同时会对其相邻目标造成等同于主目标<color style='color:#f29e38;'> 25% </color>的【<u class='infou'>反震</u>】伤害。",
      "角色对敌方目标造成的【<u class='infou'>反震</u>】伤害提高<color style='color:#f29e38;'> 15% </color>，且同时会对其他敌方目标造成等同于主目标<color style='color:#f29e38;'> 30% </color>的【<u class='infou'>反震</u>】伤害。",
    ],
    Effects: [BlessingExtra.Quake],
    rel: [GainType.QuakeDmg, GainType.DEF],
  },
  {
    _id: 615042,
    Type: BuffType.Blessing,
    Path: 120,
    Rarity: 2,
    Icon: '/IconRogueKnight01.webp',
    Name: '星间构筑 • 安全载荷',
    Desc: [
      "角色对敌方目标造成【<u class='infou'>反震</u>】时的伤害提高，提高数值等同于角色当前防御力的<color style='color:#f29e38;'> 80% </color>。",
      "角色对敌方目标造成【<u class='infou'>反震</u>】时的伤害提高，提高数值等同于角色当前防御力的<color style='color:#f29e38;'> 120% </color>。",
    ],
    Effects: [],
    rel: [GainType.ATK, GainType.Shield],
  },
  {
    _id: 615043,
    Type: BuffType.Blessing,
    Path: 120,
    Rarity: 2,
    Icon: '/IconRogueKnight02.webp',
    Name: '星间构筑 • 回馈庇护',
    Desc: [
      "持有护盾的角色提高等同于自身护盾量<color style='color:#f29e38;'> 40% </color>的攻击力，但不超过基础攻击力的<color style='color:#f29e38;'> 120% </color>。",
      "持有护盾的角色提高等同于自身护盾量<color style='color:#f29e38;'> 60% </color>的攻击力，但不超过基础攻击力的<color style='color:#f29e38;'> 160% </color>。",
    ],
    Effects: [],
    rel: [GainType.Shield],
  },
  {
    _id: 615044,
    Type: BuffType.Blessing,
    Path: 120,
    Rarity: 2,
    Icon: '/IconRogueKnight02.webp',
    Name: '星间构筑 • 四棱锥体',
    Desc: [
      "回合结束时，角色获得能够抵消等同于自身生命上限<color style='color:#f29e38;'> 10% </color>伤害的护盾，持续<color style='color:#f29e38;'> 1 </color>回合。",
      "回合结束时，角色获得能够抵消等同于自身生命上限<color style='color:#f29e38;'> 15% </color>伤害的护盾，持续<color style='color:#f29e38;'> 1 </color>回合。",
    ],
    Effects: [],
    rel: [GainType.Shield],
  },
  {
    _id: 615045,
    Type: BuffType.Blessing,
    Path: 120,
    Rarity: 2,
    Icon: '/IconRogueKnight01.webp',
    Name: '星间构筑 • 过共晶体',
    Desc: [
      "角色提供的护盾量提高<color style='color:#f29e38;'> 30% </color>。",
      "获得护盾时，角色获得的护盾量提高<color style='color:#f29e38;'> 35% </color>。",
    ],
    Effects: [],
    rel: [GainType.Shield, GainType.DMG_Gain],
  },
  {
    _id: 615050,
    Type: BuffType.Blessing,
    Path: 120,
    Rarity: 1,
    Icon: '/IconRogueKnight02.webp',
    Name: '构筑 • 聚塑',
    Desc: [
      "角色为我方目标提供护盾时，使双方造成的伤害提高<color style='color:#f29e38;'> 20% </color>，最多叠加<color style='color:#f29e38;'> 5 </color>次，持续<color style='color:#f29e38;'> 1 </color>回合。",
      "角色为我方目标提供护盾时，使双方造成的伤害提高<color style='color:#f29e38;'> 30% </color>，最多叠加<color style='color:#f29e38;'> 5 </color>次，持续<color style='color:#f29e38;'> 1 </color>回合。",
    ],
    Effects: [],
    rel: [GainType.DEF],
  },
  {
    _id: 615051,
    Type: BuffType.Blessing,
    Path: 120,
    Rarity: 1,
    Icon: '/IconRogueKnight02.webp',
    Name: '构筑 • 哨戒',
    Desc: [
      "角色防御力提高<color style='color:#f29e38;'> 20% </color>。",
      "角色防御力提高<color style='color:#f29e38;'> 30% </color>。",
    ],
    Effects: [],
    rel: [GainType.Shield],
  },
  {
    _id: 615052,
    Type: BuffType.Blessing,
    Path: 120,
    Rarity: 1,
    Icon: '/IconRogueKnight02.webp',
    Name: '构筑 • 弥合',
    Desc: [
      "进入战斗时，角色获得能够抵消等同于自身生命上限<color style='color:#f29e38;'> 16% </color>伤害的护盾，持续<color style='color:#f29e38;'> 2 </color>回合。",
      "进入战斗时，角色获得能够抵消等同于自身生命上限<color style='color:#f29e38;'> 24% </color>伤害的护盾，持续<color style='color:#f29e38;'> 2 </color>回合。",
    ],
    Effects: [],
    rel: [GainType.BeHit, GainType.Shield],
  },
  {
    _id: 615053,
    Type: BuffType.Blessing,
    Path: 120,
    Rarity: 1,
    Icon: '/IconRogueKnight02.webp',
    Name: '构筑 • 补偿',
    Desc: [
      "角色受到攻击后，获得等同于本次攻击内损失的生命值<color style='color:#f29e38;'> 18% </color>的护盾，持续<color style='color:#f29e38;'> 1 </color>回合。",
      "角色受到攻击后，获得等同于本次攻击内损失的生命值<color style='color:#f29e38;'> 18% </color>的护盾，持续<color style='color:#f29e38;'> 2 </color>回合。",
    ],
    Effects: [],
    rel: [GainType.Break, GainType.Shield],
  },
  {
    _id: 615054,
    Type: BuffType.Blessing,
    Path: 120,
    Rarity: 1,
    Icon: '/IconRogueKnight02.webp',
    Name: '构筑 • 坚定',
    Desc: [
      "角色击破敌方目标弱点后，获得能够抵消等同于自身生命上限<color style='color:#f29e38;'> 14% </color>伤害的护盾，持续<color style='color:#f29e38;'> 2 </color>回合。",
      "角色击破敌方目标弱点后，获得能够抵消等同于自身生命上限<color style='color:#f29e38;'> 18% </color>伤害的护盾，持续<color style='color:#f29e38;'> 3 </color>回合。",
    ],
    Effects: [],
    rel: [GainType.Shield, GainType.DMG_RESIST],
  },
  {
    _id: 615055,
    Type: BuffType.Blessing,
    Path: 120,
    Rarity: 1,
    Icon: '/IconRogueKnight02.webp',
    Name: '构筑 • 回转',
    Desc: [
      "持有护盾的角色受到的伤害降低<color style='color:#f29e38;'> 16% </color>。",
      "持有护盾的角色受到的伤害降低<color style='color:#f29e38;'> 24% </color>。",
    ],
    Effects: [],
    rel: [GainType.Shield, GainType.DebuffRemove],
  },
  {
    _id: 615056,
    Type: BuffType.Blessing,
    Path: 120,
    Rarity: 1,
    Icon: '/IconRogueKnight01.webp',
    Name: '构筑 • 迸发',
    Desc: [
      "角色获得护盾时，有<color style='color:#f29e38;'> 20% </color>固定概率解除1个自身的负面效果。",
      "角色获得护盾时，有<color style='color:#f29e38;'> 30% </color>固定概率解除1个自身的负面效果。",
    ],
    Effects: [],
    rel: [GainType.Shield, GainType.CRITDMG],
  },
  {
    _id: 615057,
    Type: BuffType.Blessing,
    Path: 120,
    Rarity: 1,
    Icon: '/IconRogueKnight01.webp',
    Name: '构筑 • 专注',
    Desc: [
      "持有护盾的角色暴击伤害提高<color style='color:#f29e38;'> 30% </color>。",
      "持有护盾的角色暴击伤害提高<color style='color:#f29e38;'> 45% </color>。",
    ],
    Effects: [],
    rel: [GainType.Shield, GainType.CRIT],
  },
  {
    _id: 615130,
    Type: BuffType.Blessing,
    Path: 121,
    Rarity: 3,
    Icon: '/IconRogueMemory04.webp',
    Name: '完美体验：浮黎',
    Desc: [
      "持有护盾的角色暴击率提高<color style='color:#f29e38;'> 16% </color>。",
      "持有护盾的角色暴击率提高<color style='color:#f29e38;'> 24% </color>。",
    ],
    Effects: [60000002],
    rel: [GainType.Freeze, GainType.DissociationDmg, GainType.HitFrozenUnit],
  },
  {
    _id: 615131,
    Type: BuffType.Blessing,
    Path: 121,
    Rarity: 3,
    Icon: '/IconRogueMemory04.webp',
    Name: '完美体验：纯真',
    Desc: [
      "角色对陷入冻结状态下的敌方目标施放攻击后，有<color style='color:#f29e38;'> 100% </color>的基础概率使其陷入【<u class='infou'>离神</u>】状态，持续<color style='color:#f29e38;'> 1 </color>回合。",
      "角色对陷入冻结状态下的敌方目标施放攻击后，有<color style='color:#f29e38;'> 100% </color>的基础概率使其陷入【<u class='infou'>离神</u>】状态，持续<color style='color:#f29e38;'> 1 </color>回合，并额外造成<color style='color:#f29e38;'> 20% </color>【<u class='infou'>离神</u>】解除时的伤害。",
    ],
    Effects: [60000002],
    rel: [GainType.Break, GainType.DissociationDmg, GainType.Freeze],
  },
  {
    _id: 615132,
    Type: BuffType.Blessing,
    Path: 121,
    Rarity: 3,
    Icon: '/IconRogueMemory04.webp',
    Name: '完美体验：缄默',
    Desc: [
      "角色击破敌方目标弱点后，有<color style='color:#f29e38;'> 100% </color>的基础概率使其陷入【<u class='infou'>离神</u>】状态，持续<color style='color:#f29e38;'> 1 </color>回合。",
      "角色击破敌方目标弱点后，有<color style='color:#f29e38;'> 100% </color>的基础概率使其陷入【<u class='infou'>离神</u>】状态，持续<color style='color:#f29e38;'> 1 </color>回合，该次效果无视敌方目标抵抗冻结状态的概率。",
    ],
    Effects: [],
    rel: [GainType.SuccessiveAction, GainType.Freeze],
  },
  {
    _id: 615140,
    Type: BuffType.Blessing,
    Path: 121,
    Rarity: 2,
    Icon: '/IconRogueMemory04.webp',
    Name: '极端体验：头晕目眩',
    Desc: [
      "敌方目标受到<color style='color:#f29e38;'> 6 </color>次攻击后，有<color style='color:#f29e38;'> 120% </color>基础概率陷入冻结状态，持续<color style='color:#f29e38;'> 1 </color>回合。",
      "敌方目标受到<color style='color:#f29e38;'> 5 </color>次攻击后，有<color style='color:#f29e38;'> 150% </color>基础概率陷入冻结状态，持续<color style='color:#f29e38;'> 1 </color>回合。",
    ],
    Effects: [60000002],
    rel: [GainType.MON_VUL_INC, GainType.DissociationDmg],
  },
  {
    _id: 615141,
    Type: BuffType.Blessing,
    Path: 121,
    Rarity: 2,
    Icon: '/IconRogueMemory04.webp',
    Name: '极端体验：麻木不仁',
    Desc: [
      "陷入【<u class='infou'>离神</u>】状态的敌方目标受到的伤害提高<color style='color:#f29e38;'> 36% </color>。该效果在【<u class='infou'>离神</u>】状态被解除后仍会持续1回合。",
      "陷入【<u class='infou'>离神</u>】状态的敌方目标受到的伤害提高<color style='color:#f29e38;'> 54% </color>。该效果在【<u class='infou'>离神</u>】状态被解除后仍会持续1回合。",
    ],
    Effects: [60000002],
    rel: [GainType.DissociationDmg, GainType.Freeze],
  },
  {
    _id: 615142,
    Type: BuffType.Blessing,
    Path: 121,
    Rarity: 2,
    Icon: '/IconRogueMemory04.webp',
    Name: '极端体验：瞻前顾后',
    Desc: [
      "敌方目标的【<u class='infou'>离神</u>】状态被解除后，有<color style='color:#f29e38;'> 50% </color>的基础概率陷入冻结状态，持续<color style='color:#f29e38;'> 1 </color>回合。",
      "敌方目标的【<u class='infou'>离神</u>】状态被解除后，有<color style='color:#f29e38;'> 75% </color>的基础概率陷入冻结状态，持续<color style='color:#f29e38;'> 1 </color>回合。",
    ],
    Effects: [],
    rel: [GainType.MON_DMG_DEC, GainType.Freeze],
  },
  {
    _id: 615143,
    Type: BuffType.Blessing,
    Path: 121,
    Rarity: 2,
    Icon: '/IconRogueMemory03.webp',
    Name: '极端体验：洞若观火',
    Desc: [
      "冻结状态解除时，敌方目标造成的伤害降低<color style='color:#f29e38;'> 20% </color>，持续<color style='color:#f29e38;'> 1 </color>回合。",
      "冻结状态解除时，敌方目标造成的伤害降低<color style='color:#f29e38;'> 24% </color>，持续<color style='color:#f29e38;'> 2 </color>回合。",
    ],
    Effects: [],
    rel: [
      GainType.Freeze,
      GainType.HitFrozenUnit,
      GainType.EFFECT_HIT_RATE,
      GainType.DMG_Gain,
    ],
  },
  {
    _id: 615144,
    Type: BuffType.Blessing,
    Path: 121,
    Rarity: 2,
    Icon: '/IconRogueMemory05.webp',
    Name: '极端体验：不寒而栗',
    Desc: [
      "角色对敌方目标施加冻结状态时，效果命中提高<color style='color:#f29e38;'> 30% </color>，使敌方目标陷入冻结状态后，造成的伤害提高<color style='color:#f29e38;'> 40% </color>，持续<color style='color:#f29e38;'> 2 </color>回合。",
      "角色对敌方目标施加冻结状态时，效果命中提高<color style='color:#f29e38;'> 45% </color>，使敌方目标陷入冻结状态后，造成的伤害提高<color style='color:#f29e38;'> 60% </color>，持续<color style='color:#f29e38;'> 2 </color>回合。",
    ],
    Effects: [],
    rel: [GainType.UltimateAtk, GainType.AddWeakness],
  },
  {
    _id: 615145,
    Type: BuffType.Blessing,
    Path: 121,
    Rarity: 2,
    Icon: '/IconRogueMemory04.webp',
    Name: '极端体验：特立独行',
    Desc: [
      "角色施放终结技后，有<color style='color:#f29e38;'> 70% </color>的基础概率使随机敌方单体获得冰属性弱点，持续<color style='color:#f29e38;'> 2 </color>回合。",
      "角色施放终结技后，有<color style='color:#f29e38;'> 70% </color>的基础概率使不具有冰属性弱点的随机敌方单体获得冰属性弱点，持续<color style='color:#f29e38;'> 2 </color>回合。",
    ],
    Effects: [],
    rel: [GainType.Freeze],
  },
  {
    _id: 615150,
    Type: BuffType.Blessing,
    Path: 121,
    Rarity: 1,
    Icon: '/IconRogueMemory04.webp',
    Name: '体验：痼疾的摧残',
    Desc: [
      "进入战斗时，每个敌方单体均有<color style='color:#f29e38;'> 150% </color>基础概率陷入冻结状态，持续<color style='color:#f29e38;'> 1 </color>回合。",
      "进入战斗时，每个敌方单体均有<color style='color:#f29e38;'> 150% </color>基础概率陷入冻结状态，并使其速度降低<color style='color:#f29e38;'> 30% </color>，持续<color style='color:#f29e38;'> 1 </color>回合。",
    ],
    Effects: [],
    rel: [GainType.MON_RESISTANCE_DEC],
  },
  {
    _id: 615151,
    Type: BuffType.Blessing,
    Path: 121,
    Rarity: 1,
    Icon: '/IconRogueMemory03.webp',
    Name: '体验：疏离的煎熬',
    Desc: [
      "敌方目标抵抗冻结状态的概率降低<color style='color:#f29e38;'> 30% </color>。",
      "敌方目标抵抗冻结状态的概率降低<color style='color:#f29e38;'> 45% </color>。",
    ],
    Effects: [],
    rel: [GainType.EFFECT_HIT_RATE],
  },
  {
    _id: 615152,
    Type: BuffType.Blessing,
    Path: 121,
    Rarity: 1,
    Icon: '/IconRogueMemory04.webp',
    Name: '体验：丢失的记忆',
    Desc: [
      "角色的效果命中提高<color style='color:#f29e38;'> 16% </color>。",
      "角色的效果命中提高<color style='color:#f29e38;'> 24% </color>。",
    ],
    Effects: [],
    rel: [GainType.Freeze],
  },
  {
    _id: 615153,
    Type: BuffType.Blessing,
    Path: 121,
    Rarity: 1,
    Icon: '/IconRogueMemory01.webp',
    Name: '体验：决绝的痛恨',
    Desc: [
      "角色施放攻击后，若受到攻击的敌方目标当前生命值百分比首次小于<color style='color:#f29e38;'> 50% </color>，则有<color style='color:#f29e38;'> 70% </color>的基础概率使其陷入冻结状态，持续<color style='color:#f29e38;'> 1 </color>回合。",
      "角色施放攻击后，若受到攻击的敌方目标当前生命值百分比首次小于<color style='color:#f29e38;'> 50% </color>，则有<color style='color:#f29e38;'> 100% </color>的基础概率使其陷入冻结状态，持续<color style='color:#f29e38;'> 1 </color>回合。",
    ],
    Effects: [],
    rel: [GainType.HitFrozenUnit, GainType.SkillAtk, GainType.UltimateAtk],
  },
  {
    _id: 615154,
    Type: BuffType.Blessing,
    Path: 121,
    Rarity: 1,
    Icon: '/IconRogueMemory01.webp',
    Name: '体验：病痛的折磨',
    Desc: [
      "角色对陷入冻结状态的敌方目标施放战技或终结技时，造成的伤害提高<color style='color:#f29e38;'> 36% </color>。",
      "角色对陷入冻结状态的敌方目标施放战技或终结技时，造成的伤害提高<color style='color:#f29e38;'> 54% </color>。",
    ],
    Effects: [],
    rel: [GainType.HitFrozenUnit, GainType.AdditionalDmg],
  },
  {
    _id: 615155,
    Type: BuffType.Blessing,
    Path: 121,
    Rarity: 1,
    Icon: '/IconRogueMemory04.webp',
    Name: '体验：原初的苦衷',
    Desc: [
      "角色攻击冻结状态下的敌方目标后，造成等同于<color style='color:#f29e38;'> 40% </color>攻击力的附加伤害。",
      "角色攻击冻结状态下的敌方目标后，造成等同于<color style='color:#f29e38;'> 60% </color>攻击力的附加伤害。",
    ],
    Effects: [],
    rel: [GainType.Freeze, GainType.HitFrozenUnit, GainType.MON_VUL_INC],
  },
  {
    _id: 615156,
    Type: BuffType.Blessing,
    Path: 121,
    Rarity: 1,
    Icon: '/IconRogueMemory03.webp',
    Name: '体验：攀升的刺激',
    Desc: [
      "陷入冻结状态的敌方目标受到的伤害提高<color style='color:#f29e38;'> 16% </color>。",
      "陷入冻结状态的敌方目标受到的伤害提高<color style='color:#f29e38;'> 24% </color>。",
    ],
    Effects: [],
    rel: [GainType.Freeze, GainType.ENERGY_Charge],
  },
  {
    _id: 615157,
    Type: BuffType.Blessing,
    Path: 121,
    Rarity: 1,
    Icon: '/IconRogueMemory02.webp',
    Name: '体验：回应的兴奋',
    Desc: [
      "角色对敌方目标施加冻结状态后，自身恢复<color style='color:#f29e38;'> 8 </color>点能量，该效果每次行动只能触发1次。",
      "角色对敌方目标施加冻结状态后，自身恢复<color style='color:#f29e38;'> 12 </color>点能量，该效果每次行动只能触发1次。",
    ],
    Effects: [],
    rel: [GainType.Freeze, GainType.Shield],
  },
  {
    _id: 615230,
    Type: BuffType.Blessing,
    Path: 122,
    Rarity: 3,
    Icon: '/IconRogueWarlock04.webp',
    Name: '感官追奉者的葬礼',
    Desc: [
      "敌方目标陷入的冻结状态解除后，护盾量最低的角色获得能够抵消等同于自身生命上限<color style='color:#f29e38;'> 30% </color>伤害的护盾，持续<color style='color:#f29e38;'> 2 </color>回合。",
      "敌方目标陷入的冻结状态解除后，护盾量最低的角色获得能够抵消等同于自身生命上限<color style='color:#f29e38;'> 45% </color>伤害的护盾，持续<color style='color:#f29e38;'> 2 </color>回合。",
    ],
    Effects: [60000012],
    rel: [GainType.DoT, GainType.Suspicion, GainType.MON_in_NEG_EFFECT],
  },
  {
    _id: 615231,
    Type: BuffType.Blessing,
    Path: 122,
    Rarity: 3,
    Icon: '/IconRogueWarlock04.webp',
    Name: '多余人的日记',
    Desc: [
      "敌方目标每受到1次持续伤害，陷入<color style='color:#f29e38;'> 2 </color>层【<u class='infou'>怀疑</u>】效果。",
      "敌方目标每受到1次持续伤害，陷入<color style='color:#f29e38;'> 2 </color>层【<u class='infou'>怀疑</u>】效果。【<u class='infou'>怀疑</u>】首次达到 99 层后，提供的持续伤害易伤不再受层数影响，固定为<color style='color:#f29e38;'> 120% </color>。",
    ],
    Effects: [60000012],
    rel: [
      GainType.Break,
      GainType.HitWeak,
      GainType.Suspicion,
      GainType.MON_in_NEG_EFFECT,
    ],
  },
  {
    _id: 615232,
    Type: BuffType.Blessing,
    Path: 122,
    Rarity: 3,
    Icon: '/IconRogueWarlock04.webp',
    Name: '为何一切尚未消失',
    Desc: [
      "角色击破敌方目标弱点，或攻击处于弱点击破状态下的敌方目标后，分别使其陷入<color style='color:#f29e38;'> 15 </color>或<color style='color:#f29e38;'> 3 </color>层【<u class='infou'>怀疑</u>】效果。",
      "角色击破敌方目标弱点，或攻击处于弱点击破状态下的敌方目标后，分别使其陷入<color style='color:#f29e38;'> 24 </color>或<color style='color:#f29e38;'> 4 </color>层【<u class='infou'>怀疑</u>】效果。",
    ],
    Effects: [],
    rel: [GainType.DoT, GainType.DotDetonate],
  },
  {
    _id: 615240,
    Type: BuffType.Blessing,
    Path: 122,
    Rarity: 2,
    Icon: '/IconRogueWarlock05.webp',
    Name: '开端与终结',
    Desc: [
      "敌方目标回合开始时额外触发<color style='color:#f29e38;'> 1 </color>次持续伤害结算，使其当前承受的持续伤害状态立即产生相当于原伤害<color style='color:#f29e38;'> 90% </color>的伤害。",
      "敌方目标回合开始时额外触发<color style='color:#f29e38;'> 1 </color>次持续伤害结算，使其当前承受的持续伤害状态立即产生相当于原伤害<color style='color:#f29e38;'> 135% </color>的伤害。",
    ],
    Effects: [60000012],
    rel: [GainType.Suspicion, GainType.Kill],
  },
  {
    _id: 615241,
    Type: BuffType.Blessing,
    Path: 122,
    Rarity: 2,
    Icon: '/IconRogueWarlock05.webp',
    Name: '自欺咖啡馆',
    Desc: [
      "陷入【<u class='infou'>怀疑</u>】效果下的敌方目标被消灭时，使<color style='color:#f29e38;'> 1 </color>名随机其他敌方目标陷入等同于被消灭目标【<u class='infou'>怀疑</u>】层数的【<u class='infou'>怀疑</u>】效果。",
      "陷入【<u class='infou'>怀疑</u>】效果下的敌方目标被消灭时，使<color style='color:#f29e38;'> 2 </color>名随机其他敌方目标陷入等同于被消灭目标【<u class='infou'>怀疑</u>】层数的【<u class='infou'>怀疑</u>】效果。",
    ],
    Effects: [60000012],
    rel: [GainType.Suspicion, GainType.MON_in_NEG_EFFECT],
  },
  {
    _id: 615242,
    Type: BuffType.Blessing,
    Path: 122,
    Rarity: 2,
    Icon: '/IconRogueWarlock04.webp',
    Name: '致死的疾病',
    Desc: [
      "敌方目标陷入【<u class='infou'>怀疑</u>】效果时，额外陷入<color style='color:#f29e38;'> 1 </color>层【<u class='infou'>怀疑</u>】效果。",
      "敌方目标陷入【<u class='infou'>怀疑</u>】效果时，陷入层数翻倍。",
    ],
    Effects: [],
    rel: [GainType.DoT, GainType.MON_DMG_DEC, GainType.MON_in_NEG_EFFECT],
  },
  {
    _id: 615243,
    Type: BuffType.Blessing,
    Path: 122,
    Rarity: 2,
    Icon: '/IconRogueWarlock03.webp',
    Name: '火堆外的夜',
    Desc: [
      "敌方目标受到持续伤害后，造成的伤害降低<color style='color:#f29e38;'> 5% </color>，最多叠加<color style='color:#f29e38;'> 4 </color>次，持续至回合结束时。",
      "敌方目标受到持续伤害后，造成的伤害降低<color style='color:#f29e38;'> 7% </color>，最多叠加<color style='color:#f29e38;'> 4 </color>次，持续至回合结束时。",
    ],
    Effects: [],
    rel: [GainType.BreakEfficiency],
  },
  {
    _id: 615244,
    Type: BuffType.Blessing,
    Path: 122,
    Rarity: 2,
    Icon: '/IconRogueWarlock01.webp',
    Name: '他人即地狱',
    Desc: [
      "角色的弱点击破效率提高<color style='color:#f29e38;'> 30% </color>。",
      "角色的弱点击破效率提高<color style='color:#f29e38;'> 45% </color>。",
    ],
    Effects: [],
    rel: [GainType.Break, GainType.BreakDmg],
  },
  {
    _id: 615245,
    Type: BuffType.Blessing,
    Path: 122,
    Rarity: 2,
    Icon: '/IconRogueWarlock04.webp',
    Name: '无根据颂歌',
    Desc: [
      "角色击破敌方目标弱点时，对相邻目标造成一次等同于弱点击破伤害<color style='color:#f29e38;'> 140% </color>的击破伤害。",
      "角色击破敌方目标弱点时，对其他敌方目标造成一次等同于弱点击破伤害<color style='color:#f29e38;'> 210% </color>的击破伤害。",
    ],
    Effects: [],
    rel: [GainType.DoT, GainType.DotDetonate],
  },
  {
    _id: 615250,
    Type: BuffType.Blessing,
    Path: 122,
    Rarity: 1,
    Icon: '/IconRogueWarlock03.webp',
    Name: '漠视主义',
    Desc: [
      "敌方目标受到攻击后，若处于持续伤害状态，随机触发1个持续伤害，造成等同于原持续伤害<color style='color:#f29e38;'> 100% </color>的伤害。",
      "敌方目标受到攻击后，若处于持续伤害状态，随机触发1个持续伤害，造成等同于原持续伤害<color style='color:#f29e38;'> 150% </color>的伤害。",
    ],
    Effects: [],
    rel: [GainType.DoT_By_Char],
  },
  {
    _id: 615251,
    Type: BuffType.Blessing,
    Path: 122,
    Rarity: 1,
    Icon: '/IconRogueWarlock03.webp',
    Name: '拟像崩解',
    Desc: [
      "角色造成的持续伤害提高<color style='color:#f29e38;'> 24% </color>。",
      "角色造成的持续伤害提高<color style='color:#f29e38;'> 36% </color>。",
    ],
    Effects: [],
    rel: [GainType.ATK],
  },
  {
    _id: 615252,
    Type: BuffType.Blessing,
    Path: 122,
    Rarity: 1,
    Icon: '/IconRogueWarlock04.webp',
    Name: '盲目视界',
    Desc: [
      "角色攻击力提高<color style='color:#f29e38;'> 18% </color>。",
      "角色攻击力提高<color style='color:#f29e38;'> 27% </color>。",
    ],
    Effects: [],
    rel: [GainType.MON_RESISTANCE_DEC],
  },
  {
    _id: 615253,
    Type: BuffType.Blessing,
    Path: 122,
    Rarity: 1,
    Icon: '/IconRogueWarlock04.webp',
    Name: '悲剧讲座',
    Desc: [
      "敌方目标效果抵抗降低<color style='color:#f29e38;'> 12% </color>。",
      "敌方目标效果抵抗降低<color style='color:#f29e38;'> 18% </color>。",
    ],
    Effects: [],
    rel: [GainType.DoT, GainType.DoT_Vulnerability],
  },
  {
    _id: 615254,
    Type: BuffType.Blessing,
    Path: 122,
    Rarity: 1,
    Icon: '/IconRogueWarlock04.webp',
    Name: '自我呈现',
    Desc: [
      "敌方目标受到的持续伤害提高<color style='color:#f29e38;'> 10% </color>。",
      "敌方目标受到的持续伤害提高<color style='color:#f29e38;'> 15% </color>。",
    ],
    Effects: [],
    rel: [GainType.Break, GainType.MON_DEF_DEC],
  },
  {
    _id: 615255,
    Type: BuffType.Blessing,
    Path: 122,
    Rarity: 1,
    Icon: '/IconRogueWarlock04.webp',
    Name: '情绪舍离',
    Desc: [
      "处于弱点击破状态下的敌方目标，防御力降低<color style='color:#f29e38;'> 15% </color>。",
      "处于弱点击破状态下的敌方目标，防御力降低<color style='color:#f29e38;'> 20% </color>。",
    ],
    Effects: [],
    rel: [GainType.DoT, GainType.DoT_Vulnerability],
  },
  {
    _id: 615256,
    Type: BuffType.Blessing,
    Path: 122,
    Rarity: 1,
    Icon: '/IconRogueWarlock02.webp',
    Name: '虚妄供品',
    Desc: [
      "敌方目标每承受1个持续伤害状态，受到的伤害提高<color style='color:#f29e38;'> 3% </color>，该效果最多叠加<color style='color:#f29e38;'> 4 </color>层。",
      "敌方目标每承受1个持续伤害状态，受到的伤害提高<color style='color:#f29e38;'> 4% </color>，该效果最多叠加<color style='color:#f29e38;'> 5 </color>层。",
    ],
    Effects: [],
    rel: [GainType.DoT, GainType.Healing],
  },
  {
    _id: 615257,
    Type: BuffType.Blessing,
    Path: 122,
    Rarity: 1,
    Icon: '/IconRogueWarlock03.webp',
    Name: '日出之前',
    Desc: [
      "敌方目标每受到1次持续伤害，我方全体回复等同于各自<color style='color:#f29e38;'> 1% </color>生命上限的生命值。",
      "敌方目标每受到1次持续伤害，我方全体回复等同于各自<color style='color:#f29e38;'> 1.5% </color>生命上限的生命值。",
    ],
    Effects: [],
    rel: [GainType.DoT, GainType.ENERGY_Charge],
  },
  {
    _id: 615330,
    Type: BuffType.Blessing,
    Path: 123,
    Rarity: 3,
    Icon: '/IconRoguePirest01.webp',
    Name: '葳蕤繁祉，延彼遐龄',
    Desc: [
      "敌方目标每受到1次持续伤害，我方随机目标恢复<color style='color:#f29e38;'> 2 </color>点能量，敌方目标每回合最多触发<color style='color:#f29e38;'> 20 </color>次该效果。",
      "敌方目标每受到1次持续伤害，我方随机目标恢复<color style='color:#f29e38;'> 3 </color>点能量，敌方目标每回合最多触发<color style='color:#f29e38;'> 20 </color>次该效果。",
    ],
    Effects: [60000013],
    rel: [GainType.DewDropDmg, GainType.Healing],
  },
  {
    _id: 615331,
    Type: BuffType.Blessing,
    Path: 123,
    Rarity: 3,
    Icon: '/IconRoguePirest01.webp',
    Name: '若罪若福，施诸愿印',
    Desc: [
      "角色接受治疗时，对【<u class='infou'>珠露</u>】进行充能，充能值为回复量的<color style='color:#f29e38;'> 100% </color>。",
      "角色接受治疗时，对【<u class='infou'>珠露</u>】进行充能，充能值为回复量的<color style='color:#f29e38;'> 100% </color>。并使【<u class='infou'>珠露</u>】的伤害倍率提高原倍率的<color style='color:#f29e38;'> 40% </color>。",
    ],
    Effects: [60000013],
    rel: [GainType.DewDropDmg, GainType.HEAL],
  },
  {
    _id: 615332,
    Type: BuffType.Blessing,
    Path: 123,
    Rarity: 3,
    Icon: '/IconRoguePirest02.webp',
    Name: '丰饶众生，一法界心',
    Desc: [
      "角色回合开始时，对【<u class='infou'>珠露</u>】进行充能，充能值为当前生命值的<color style='color:#f29e38;'> 60% </color>。",
      "角色回合开始时，对【<u class='infou'>珠露</u>】进行充能，充能值为自身生命上限的<color style='color:#f29e38;'> 70% </color>。",
    ],
    Effects: [],
    rel: [GainType.Healing, GainType.HEAL],
  },
  {
    _id: 615340,
    Type: BuffType.Blessing,
    Path: 123,
    Rarity: 2,
    Icon: '/IconRoguePirest02.webp',
    Name: '灭罪累生善',
    Desc: [
      "角色提供治疗时，接受治疗目标以外的我方目标会回复等同于回复量<color style='color:#f29e38;'> 30% </color>的生命值。",
      "角色生命上限提高<color style='color:#f29e38;'> 20% </color>，提供治疗时，接受治疗目标以外的我方目标会回复等同于回复量<color style='color:#f29e38;'> 35% </color>的生命值。",
    ],
    Effects: [60000013],
    rel: [GainType.DewDropDmg, GainType.Healing],
  },
  {
    _id: 615341,
    Type: BuffType.Blessing,
    Path: 123,
    Rarity: 2,
    Icon: '/IconRoguePirest05.webp',
    Name: '天人不动众',
    Desc: [
      "【<u class='infou'>珠露</u>】破裂时，会为角色回复等同于充能值<color style='color:#f29e38;'> 20% </color>的生命值，不超过角色生命上限的<color style='color:#f29e38;'> 18% </color>。",
      "【<u class='infou'>珠露</u>】破裂时，会为角色回复等同于充能值<color style='color:#f29e38;'> 20% </color>的生命值，不超过角色生命上限的<color style='color:#f29e38;'> 24% </color>，不低于角色生命上限的<color style='color:#f29e38;'> 12% </color>。",
    ],
    Effects: [60000013],
    rel: [GainType.HEAL, GainType.DewDropCharge],
  },
  {
    _id: 615342,
    Type: BuffType.Blessing,
    Path: 123,
    Rarity: 2,
    Icon: '/IconRoguePirest01.webp',
    Name: '宝光烛日月',
    Desc: [
      "角色当前生命值等于自身生命上限时，对【<u class='infou'>珠露</u>】的充能效率提高<color style='color:#f29e38;'> 80% </color>。",
      "角色当前生命值等于自身生命上限时，对【<u class='infou'>珠露</u>】的充能效率提高<color style='color:#f29e38;'> 120% </color>。",
    ],
    Effects: [],
    rel: [GainType.ATK],
  },
  {
    _id: 615343,
    Type: BuffType.Blessing,
    Path: 123,
    Rarity: 2,
    Icon: '/IconRoguePirest01.webp',
    Name: '厌离邪秽苦',
    Desc: [
      "角色为我方目标提供治疗时，使双方攻击力提高<color style='color:#f29e38;'> 50% </color>，持续<color style='color:#f29e38;'> 1 </color>回合。",
      "角色为我方目标提供治疗时，使我方全体攻击力提高<color style='color:#f29e38;'> 50% </color>，持续<color style='color:#f29e38;'> 1 </color>回合。",
    ],
    Effects: [],
    rel: [GainType.HEAL, GainType.AdditionalDmg],
  },
  {
    _id: 615344,
    Type: BuffType.Blessing,
    Path: 123,
    Rarity: 2,
    Icon: '/IconRoguePirest02.webp',
    Name: '明澈琉璃身',
    Desc: [
      "角色施放攻击后，对受到攻击的敌方目标造成等同于当前生命值<color style='color:#f29e38;'> 36% </color>的附加伤害。",
      "角色施放攻击后，对受到攻击的敌方目标造成等同于自身生命上限<color style='color:#f29e38;'> 42% </color>的附加伤害。",
    ],
    Effects: [],
    rel: [GainType.DMG_RESIST, GainType.RESIST],
  },
  {
    _id: 615345,
    Type: BuffType.Blessing,
    Path: 123,
    Rarity: 2,
    Icon: '/IconRoguePirest02.webp',
    Name: '大愿般若船',
    Desc: [
      "当角色生命值回复至自身生命上限时，受到的伤害降低<color style='color:#f29e38;'> 25% </color>，效果抵抗提高<color style='color:#f29e38;'> 15% </color>，持续至受到攻击后。",
      "当角色生命值回复至自身生命上限时，受到的伤害降低<color style='color:#f29e38;'> 30% </color>，效果抵抗提高<color style='color:#f29e38;'> 30% </color>，持续至受到攻击后。",
    ],
    Effects: [],
    rel: [GainType.Healing],
  },
  {
    _id: 615350,
    Type: BuffType.Blessing,
    Path: 123,
    Rarity: 1,
    Icon: '/IconRoguePirest02.webp',
    Name: '法雨',
    Desc: [
      "角色接受我方目标提供的治疗后，会额外回复等同于回复量<color style='color:#f29e38;'> 30% </color>的生命值。",
      "角色接受我方目标提供的治疗后，会额外回复等同于回复量<color style='color:#f29e38;'> 45% </color>的生命值。",
    ],
    Effects: [],
    rel: [GainType.Healing, GainType.HEAL],
  },
  {
    _id: 615351,
    Type: BuffType.Blessing,
    Path: 123,
    Rarity: 1,
    Icon: '/IconRoguePirest02.webp',
    Name: '甘露',
    Desc: [
      "角色回复的生命值溢出时，生命上限提高<color style='color:#f29e38;'> 24% </color>，持续<color style='color:#f29e38;'> 1 </color>回合。",
      "角色回复的生命值溢出时，生命上限提高<color style='color:#f29e38;'> 36% </color>，持续<color style='color:#f29e38;'> 1 </color>回合。",
    ],
    Effects: [],
    rel: [GainType.Healing],
  },
  {
    _id: 615352,
    Type: BuffType.Blessing,
    Path: 123,
    Rarity: 1,
    Icon: '/IconRoguePirest02.webp',
    Name: '延寿',
    Desc: [
      "角色的生命值回复量提高<color style='color:#f29e38;'> 12% </color>。",
      "角色的生命值回复量提高<color style='color:#f29e38;'> 18% </color>。",
    ],
    Effects: [],
    rel: [GainType.Healing],
  },
  {
    _id: 615353,
    Type: BuffType.Blessing,
    Path: 123,
    Rarity: 1,
    Icon: '/IconRoguePirest02.webp',
    Name: '愿印',
    Desc: [
      "角色在战斗中生命值百分比首次小于<color style='color:#f29e38;'> 50% </color>时，回复等同于生命上限<color style='color:#f29e38;'> 30% </color>的生命值。",
      "角色在战斗中生命值百分比首次小于<color style='color:#f29e38;'> 50% </color>时，回复等同于生命上限<color style='color:#f29e38;'> 45% </color>的生命值。",
    ],
    Effects: [],
    rel: [GainType.Break, GainType.Healing],
  },
  {
    _id: 615354,
    Type: BuffType.Blessing,
    Path: 123,
    Rarity: 1,
    Icon: '/IconRoguePirest02.webp',
    Name: '禳灾',
    Desc: [
      "角色击破敌方目标弱点后，回复等同于生命上限<color style='color:#f29e38;'> 16% </color>的生命值。",
      "角色击破敌方目标弱点后，回复等同于生命上限<color style='color:#f29e38;'> 24% </color>的生命值。",
    ],
    Effects: [],
    rel: [GainType.DEF],
  },
  {
    _id: 615355,
    Type: BuffType.Blessing,
    Path: 123,
    Rarity: 1,
    Icon: '/IconRoguePirest02.webp',
    Name: '回生',
    Desc: [
      "角色接受治疗后，防御力提高<color style='color:#f29e38;'> 24% </color>，持续<color style='color:#f29e38;'> 1 </color>回合。",
      "角色接受治疗后，防御力提高<color style='color:#f29e38;'> 36% </color>，持续<color style='color:#f29e38;'> 1 </color>回合。",
    ],
    Effects: [],
    rel: [GainType.Healing],
  },
  {
    _id: 615356,
    Type: BuffType.Blessing,
    Path: 123,
    Rarity: 1,
    Icon: '/IconRoguePirest03.webp',
    Name: '胜军',
    Desc: [
      "角色提供治疗后，回复等同于自身生命上限<color style='color:#f29e38;'> 12% </color>的生命值，该效果每次行动只可触发1次。",
      "角色提供治疗后，回复等同于自身生命上限<color style='color:#f29e38;'> 18% </color>的生命值，该效果每次行动只可触发1次。",
    ],
    Effects: [],
    rel: [GainType.SPD],
  },
  {
    _id: 615357,
    Type: BuffType.Blessing,
    Path: 123,
    Rarity: 1,
    Icon: '/IconRoguePirest02.webp',
    Name: '灌顶',
    Desc: [
      "角色接受治疗后，速度提高<color style='color:#f29e38;'> 10% </color>，持续<color style='color:#f29e38;'> 1 </color>回合。",
      "角色接受治疗后，速度提高<color style='color:#f29e38;'> 15% </color>，持续<color style='color:#f29e38;'> 1 </color>回合。",
    ],
    Effects: [],
    rel: [GainType.Healing, GainType.DebuffRemove],
  },
  {
    _id: 615430,
    Type: BuffType.Blessing,
    Path: 124,
    Rarity: 3,
    Icon: '/IconRogueRogue03.webp',
    Name: '帝星君临制穹桑',
    Desc: [
      "角色回复的生命值溢出时，有<color style='color:#f29e38;'> 25% </color>的固定概率解除1个自身的负面效果，该效果每回合最多触发<color style='color:#f29e38;'> 1 </color>次。",
      "角色回复的生命值溢出时，有<color style='color:#f29e38;'> 25% </color>的固定概率解除1个自身的负面效果，该效果每回合最多触发<color style='color:#f29e38;'> 2 </color>次。",
    ],
    Effects: [60000004],
    rel: [GainType.CriticalBoost, GainType.CRIT, GainType.CRITDMG],
  },
  {
    _id: 615431,
    Type: BuffType.Blessing,
    Path: 124,
    Rarity: 3,
    Icon: '/IconRogueRogue03.webp',
    Name: '帝车超光所向捷',
    Desc: [
      "角色回合开始时，获得<color style='color:#f29e38;'> 1 </color>层【<u class='infou'>会心</u>】效果。",
      "角色回合开始时，获得<color style='color:#f29e38;'> 1 </color>层【<u class='infou'>会心</u>】效果，并使【<u class='infou'>会心</u>】最高可叠加至<color style='color:#f29e38;'> 12 </color>层。",
    ],
    Effects: [60000004],
    rel: [
      GainType.SuccessiveAction,
      GainType.CriticalBoost,
      GainType.CRIT,
      GainType.CRITDMG,
    ],
  },
  {
    _id: 615432,
    Type: BuffType.Blessing,
    Path: 124,
    Rarity: 3,
    Icon: '/IconRogueRogue03.webp',
    Name: '帝弓断空彻太清',
    Desc: [
      "角色消灭敌方目标后，自身行动提前 100% ，在下个回合开始时，获得<color style='color:#f29e38;'> 4 </color>层【<u class='infou'>会心</u>】效果。",
      "角色消灭敌方目标后，自身行动提前 100% ，在下个回合开始时，获得<color style='color:#f29e38;'> 7 </color>层【<u class='infou'>会心</u>】效果。",
    ],
    Effects: [],
    rel: [GainType.SuccessiveAction, GainType.DMG_Gain],
  },
  {
    _id: 615440,
    Type: BuffType.Blessing,
    Path: 124,
    Rarity: 2,
    Icon: '/IconRogueRogue03.webp',
    Name: '天舟缴夙敌',
    Desc: [
      "角色击破敌方目标弱点后，自身行动提前 100% ，并使下次攻击造成的伤害提高<color style='color:#f29e38;'> 50% </color>。",
      "角色击破敌方目标弱点后，自身行动提前 100% ，并使造成的伤害提高<color style='color:#f29e38;'> 75% </color>，伤害提高效果最多叠加<color style='color:#f29e38;'> 2 </color>层，持续至受到攻击后。",
    ],
    Effects: [60000004],
    rel: [GainType.CRIT, GainType.CRITDMG],
  },
  {
    _id: 615441,
    Type: BuffType.Blessing,
    Path: 124,
    Rarity: 2,
    Icon: '/IconRogueRogue05.webp',
    Name: '序师执迟彝',
    Desc: [
      "当角色的暴击率大于 100% 时，若具有【<u class='infou'>会心</u>】效果，每溢出1%暴击率提高<color style='color:#f29e38;'> 3% </color>暴击伤害，暴击伤害最多提高<color style='color:#f29e38;'> 150% </color>。",
      "当角色的暴击率大于 100% 时，若具有【<u class='infou'>会心</u>】效果，每溢出1%暴击率提高<color style='color:#f29e38;'> 3% </color>暴击伤害，暴击伤害最多提高<color style='color:#f29e38;'> 240% </color>。",
    ],
    Effects: [60000004],
    rel: [GainType.SuccessiveAction, GainType.CriticalBoost],
  },
  {
    _id: 615442,
    Type: BuffType.Blessing,
    Path: 124,
    Rarity: 2,
    Icon: '/IconRogueRogue01.webp',
    Name: '流岚追孽物',
    Desc: [
      "当任意我方目标施放终结技时，可以继承【<u class='infou'>会心</u>】效果，并使【<u class='infou'>会心</u>】层数提高<color style='color:#f29e38;'> 1 </color>层。",
      "当任意我方目标施放追加攻击或终结技时，可以继承【<u class='infou'>会心</u>】效果，并使【<u class='infou'>会心</u>】层数提高<color style='color:#f29e38;'> 1 </color>层。",
    ],
    Effects: [],
    rel: [GainType.SuccessiveAction, GainType.ATK, GainType.Point],
  },
  {
    _id: 615443,
    Type: BuffType.Blessing,
    Path: 124,
    Rarity: 2,
    Icon: '/IconRogueRogue02.webp',
    Name: '参连讨妖星',
    Desc: [
      "相同角色连续行动时，攻击力提高<color style='color:#f29e38;'> 40% </color>，该效果最多叠加<color style='color:#f29e38;'> 2 </color>层。",
      "相同角色连续行动时，攻击力提高<color style='color:#f29e38;'> 40% </color>，该效果最多叠加<color style='color:#f29e38;'> 2 </color>层，同时有<color style='color:#f29e38;'> 50% </color>的固定概率恢复1点战技点，该效果无法重复触发。",
    ],
    Effects: [],
    rel: [GainType.DMG_RESIST],
  },
  {
    _id: 615444,
    Type: BuffType.Blessing,
    Path: 124,
    Rarity: 2,
    Icon: '/IconRogueRogue03.webp',
    Name: '云镝逐步离',
    Desc: [
      "角色施放攻击后，受到伤害降低<color style='color:#f29e38;'> 12% </color>，该效果最多叠加<color style='color:#f29e38;'> 2 </color>层，持续至受到攻击后。",
      "角色施放攻击后，受到伤害降低<color style='color:#f29e38;'> 12% </color>，该效果最多叠加<color style='color:#f29e38;'> 3 </color>层，持续至受到攻击后。",
    ],
    Effects: [],
    rel: [GainType.SuccessiveAction],
  },
  {
    _id: 615445,
    Type: BuffType.Blessing,
    Path: 124,
    Rarity: 2,
    Icon: '/IconRogueRogue02.webp',
    Name: '飞虹诛凿齿',
    Desc: [
      "我方全体每经过<color style='color:#f29e38;'> 6 </color>个回合后，当前角色行动提前 100% ，该效果无法被相同角色连续触发。",
      "我方全体每经过<color style='color:#f29e38;'> 6 </color>个回合后，当前角色行动提前 100% ，该效果无法被相同角色连续触发。进入战斗时，视作已经过<color style='color:#f29e38;'> 5 </color>个回合。",
    ],
    Effects: [],
    rel: [GainType.Kill, GainType.Healing, GainType.ATK],
  },
  {
    _id: 615450,
    Type: BuffType.Blessing,
    Path: 124,
    Rarity: 1,
    Icon: '/IconRogueRogue03.webp',
    Name: '彤弓素矰',
    Desc: [
      "角色消灭敌方目标后，我方全体回复等同于自身生命上限<color style='color:#f29e38;'> 30% </color>的生命值，并使攻击力提高<color style='color:#f29e38;'> 25% </color>，持续<color style='color:#f29e38;'> 2 </color>回合。",
      "角色消灭敌方目标后，我方全体回复等同于自身生命上限<color style='color:#f29e38;'> 45% </color>的生命值，并使攻击力提高<color style='color:#f29e38;'> 45% </color>，持续<color style='color:#f29e38;'> 2 </color>回合。",
    ],
    Effects: [],
    rel: [GainType.SPD],
  },
  {
    _id: 615451,
    Type: BuffType.Blessing,
    Path: 124,
    Rarity: 1,
    Icon: '/IconRogueRogue01.webp',
    Name: '背生击死',
    Desc: [
      "角色速度提高<color style='color:#f29e38;'> 8% </color>。",
      "角色速度提高<color style='color:#f29e38;'> 12% </color>。",
    ],
    Effects: [],
    rel: [GainType.CRIT],
  },
  {
    _id: 615452,
    Type: BuffType.Blessing,
    Path: 124,
    Rarity: 1,
    Icon: '/IconRogueRogue01.webp',
    Name: '背孤击虚',
    Desc: [
      "角色暴击率提高<color style='color:#f29e38;'> 11% </color>。",
      "角色暴击率提高<color style='color:#f29e38;'> 16% </color>。",
    ],
    Effects: [],
    rel: [GainType.CRITDMG],
  },
  {
    _id: 615453,
    Type: BuffType.Blessing,
    Path: 124,
    Rarity: 1,
    Icon: '/IconRogueRogue04.webp',
    Name: '雷车动地',
    Desc: [
      "角色暴击伤害提高<color style='color:#f29e38;'> 20% </color>。",
      "角色暴击伤害提高<color style='color:#f29e38;'> 30% </color>。",
    ],
    Effects: [],
    rel: [GainType.Break, GainType.MON_act_delay],
  },
  {
    _id: 615454,
    Type: BuffType.Blessing,
    Path: 124,
    Rarity: 1,
    Icon: '/IconRogueRogue03.webp',
    Name: '电射牛斗',
    Desc: [
      "角色击破敌方目标弱点后，使其行动延后<color style='color:#f29e38;'> 20% </color>。",
      "角色击破敌方目标弱点后，使其行动延后<color style='color:#f29e38;'> 30% </color>。",
    ],
    Effects: [],
    rel: [GainType.Break, GainType.SPD],
  },
  {
    _id: 615455,
    Type: BuffType.Blessing,
    Path: 124,
    Rarity: 1,
    Icon: '/IconRogueRogue03.webp',
    Name: '天棓步危',
    Desc: [
      "角色击破敌方目标弱点后，速度提高<color style='color:#f29e38;'> 30% </color>，持续至受到攻击后。",
      "角色击破敌方目标弱点后，速度提高<color style='color:#f29e38;'> 45% </color>，持续至受到攻击后。",
    ],
    Effects: [],
    rel: [GainType.SuccessiveAction],
  },
  {
    _id: 615456,
    Type: BuffType.Blessing,
    Path: 124,
    Rarity: 1,
    Icon: '/IconRogueRogue03.webp',
    Name: '桑弧蓬矢',
    Desc: [
      "角色回合结束时，行动提前<color style='color:#f29e38;'> 8% </color>。",
      "角色回合结束时，行动提前<color style='color:#f29e38;'> 12% </color>。",
    ],
    Effects: [],
    rel: [GainType.ENERGY_Charge],
  },
  {
    _id: 615457,
    Type: BuffType.Blessing,
    Path: 124,
    Rarity: 1,
    Icon: '/IconRogueRogue01.webp',
    Name: '乌号綦箭',
    Desc: [
      "角色回合开始时，恢复<color style='color:#f29e38;'> 4 </color>点能量。",
      "角色回合开始时，恢复<color style='color:#f29e38;'> 6 </color>点能量。",
    ],
    Effects: [],
    rel: [GainType.ATK],
  },
  {
    _id: 615530,
    Type: BuffType.Blessing,
    Path: 125,
    Rarity: 3,
    Icon: '/IconRogueWarrior03.webp',
    Name: '类星体熔毁常数',
    Desc: [
      "角色回合开始时，提高等同于上一个行动的我方目标<color style='color:#f29e38;'> 10% </color>当前攻击力的攻击力，持续至下个回合开始时。",
      "角色回合开始时，提高等同于上一个行动的我方目标<color style='color:#f29e38;'> 15% </color>当前攻击力的攻击力，持续至下个回合开始时。",
    ],
    Effects: [60000005],
    rel: [GainType.Healing, GainType.ConsumeHp, GainType.Grit, GainType.BREAK],
  },
  {
    _id: 615531,
    Type: BuffType.Blessing,
    Path: 125,
    Rarity: 3,
    Icon: '/IconRogueWarrior03.webp',
    Name: '临界密度扩张群',
    Desc: [
      "角色每损失或治疗自身生命值<color style='color:#f29e38;'> 20% </color>，获得<color style='color:#f29e38;'> 1 </color>层【<u class='infou'>战意</u>】效果，每回合最多获得<color style='color:#f29e38;'> 8 </color>层。累计损失或治疗自身<color style='color:#f29e38;'> 100% </color>的生命值后，使角色击破特攻提高<color style='color:#f29e38;'> 30% </color>。",
      "角色每损失或治疗自身生命值<color style='color:#f29e38;'> 16% </color>，获得<color style='color:#f29e38;'> 1 </color>层【<u class='infou'>战意</u>】效果，每回合最多获得<color style='color:#f29e38;'> 12 </color>层。累计损失或治疗自身<color style='color:#f29e38;'> 100% </color>的生命值后，使角色击破特攻提高<color style='color:#f29e38;'> 45% </color>。",
    ],
    Effects: [60000005],
    rel: [GainType.Healing, GainType.ConsumeHp, GainType.Grit],
  },
  {
    _id: 615532,
    Type: BuffType.Blessing,
    Path: 125,
    Rarity: 3,
    Icon: '/IconRogueWarrior02.webp',
    Name: '湮灭回归不等式',
    Desc: [
      "角色每次损失或治疗自身生命值，获得<color style='color:#f29e38;'> 2 </color>层【<u class='infou'>战意</u>】效果，该效果每次受到攻击最多触发1次。",
      "角色每次损失或治疗自身生命值，获得<color style='color:#f29e38;'> 2 </color>层【<u class='infou'>战意</u>】效果，并使随机<color style='color:#f29e38;'> 1 </color>名队友获得<color style='color:#f29e38;'> 1 </color>层【<u class='infou'>战意</u>】效果，该效果每次受到攻击最多触发1次。",
    ],
    Effects: [],
    rel: [GainType.DMG_RESIST],
  },
  {
    _id: 615540,
    Type: BuffType.Blessing,
    Path: 125,
    Rarity: 2,
    Icon: '/IconRogueWarrior04.webp',
    Name: '灾难性共振',
    Desc: [
      '受到攻击时，角色所受伤害将由我方全体分摊。',
      "角色受到的伤害降低<color style='color:#f29e38;'> 15% </color>，受到攻击时，角色所受伤害由我方全体分摊。",
    ],
    Effects: [60000005],
    rel: [GainType.Grit, GainType.DMG_Gain, GainType.BreakDmg],
  },
  {
    _id: 615541,
    Type: BuffType.Blessing,
    Path: 125,
    Rarity: 2,
    Icon: '/IconRogueWarrior02.webp',
    Name: '预兆性景深',
    Desc: [
      "持有【<u class='infou'>战意</u>】的角色，施放普攻/战技/终结技造成伤害时，敌方目标受到的伤害提高<color style='color:#f29e38;'> 10% </color>，【<u class='infou'>战意</u>】层数大于<color style='color:#f29e38;'> 10 </color>层时，额外使敌方目标受到的击破伤害提高<color style='color:#f29e38;'> 30% </color>。",
      "持有【<u class='infou'>战意</u>】的角色，施放普攻/战技/终结技造成伤害时，敌方目标受到的伤害提高<color style='color:#f29e38;'> 15% </color>，【<u class='infou'>战意</u>】层数大于<color style='color:#f29e38;'> 10 </color>层时，额外使敌方目标受到的击破伤害提高<color style='color:#f29e38;'> 45% </color>。",
    ],
    Effects: [60000005],
    rel: [GainType.Grit, GainType.DMG_RESIST],
  },
  {
    _id: 615542,
    Type: BuffType.Blessing,
    Path: 125,
    Rarity: 2,
    Icon: '/IconRogueWarrior01.webp',
    Name: '灭绝性潮汐',
    Desc: [
      "持有【<u class='infou'>战意</u>】的角色，受到的伤害降低<color style='color:#f29e38;'> 16% </color>。生命值百分比小于<color style='color:#f29e38;'> 50% </color>时，额外降低<color style='color:#f29e38;'> 8% </color>。",
      "持有【<u class='infou'>战意</u>】的角色，受到的伤害降低<color style='color:#f29e38;'> 20% </color>。生命值百分比小于<color style='color:#f29e38;'> 50% </color>时，额外降低<color style='color:#f29e38;'> 12% </color>。",
    ],
    Effects: [10000015],
    rel: [
      GainType.Healing,
      GainType.ConsumeHp,
      GainType.HitWeak,
      GainType.SuperBreakDmg,
    ],
  },
  {
    _id: 615543,
    Type: BuffType.Blessing,
    Path: 125,
    Rarity: 2,
    Icon: '/IconRogueWarrior03.webp',
    Name: '衰亡性爆缩',
    Desc: [
      "角色累计损失或治疗自身<color style='color:#f29e38;'> 40% </color>生命值后，攻击处于弱点击破状态下的敌方目标后，会将本次攻击的削韧值转化为1次<color style='color:#f29e38;'> 70% </color>的<u class='infou'>超击破伤害</u>。",
      "角色累计损失或治疗自身<color style='color:#f29e38;'> 40% </color>生命值后，攻击处于弱点击破状态下的敌方目标后，会将本次攻击的削韧值转化为1次<color style='color:#f29e38;'> 105% </color>的<u class='infou'>超击破伤害</u>。",
    ],
    Effects: [],
    rel: [
      GainType.Healing,
      GainType.ConsumeHp,
      GainType.BreakDmg,
      GainType.ResistStrike,
    ],
  },
  {
    _id: 615544,
    Type: BuffType.Blessing,
    Path: 125,
    Rarity: 2,
    Icon: '/IconRogueWarrior02.webp',
    Name: '戒律性闪变',
    Desc: [
      "角色累计损失或治疗自身<color style='color:#f29e38;'> 40% </color>生命值后，全属性抗性穿透提高<color style='color:#f29e38;'> 10% </color>，造成击破伤害时额外提高<color style='color:#f29e38;'> 20% </color>。",
      "角色累计损失或治疗自身<color style='color:#f29e38;'> 40% </color>生命值后，全属性抗性穿透提高<color style='color:#f29e38;'> 15% </color>，造成击破伤害时额外提高<color style='color:#f29e38;'> 30% </color>。",
    ],
    Effects: [],
    rel: [GainType.Healing, GainType.ConsumeHp],
  },
  {
    _id: 615545,
    Type: BuffType.Blessing,
    Path: 125,
    Rarity: 2,
    Icon: '/IconRogueWarrior03.webp',
    Name: '扰乱性脉冲',
    Desc: [
      "角色受到攻击或消耗生命值后，若当前生命值百分比小于<color style='color:#f29e38;'> 35% </color>，回复等同于生命上限<color style='color:#f29e38;'> 12% </color>的生命值。",
      "角色受到攻击或消耗生命值后，若当前生命值百分比小于<color style='color:#f29e38;'> 35% </color>，则回复等同于生命上限<color style='color:#f29e38;'> 12% </color>的生命值。当前生命值百分比越低回复量越高，最多不超过<color style='color:#f29e38;'> 20% </color>。",
    ],
    Effects: [],
    rel: [GainType.HEAL, GainType.ENERGY_Charge],
  },
  {
    _id: 615550,
    Type: BuffType.Blessing,
    Path: 125,
    Rarity: 1,
    Icon: '/IconRogueWarrior01.webp',
    Name: '突裂奇点',
    Desc: [
      "角色生命值百分比降低至<color style='color:#f29e38;'> 50% </color>时，固定恢复等同于自身能量上限<color style='color:#f29e38;'> 50% </color>的能量，该效果在<color style='color:#f29e38;'> 4 </color>回合后可以再次触发。",
      "角色生命值百分比降低至<color style='color:#f29e38;'> 60% </color>时，固定恢复等同于自身能量上限<color style='color:#f29e38;'> 50% </color>的能量与<color style='color:#f29e38;'> 1 </color>个战技点，该效果在<color style='color:#f29e38;'> 4 </color>回合后可以再次触发。",
    ],
    Effects: [],
    rel: [GainType.BREAK],
  },
  {
    _id: 615551,
    Type: BuffType.Blessing,
    Path: 125,
    Rarity: 1,
    Icon: '/IconRogueWarrior02.webp',
    Name: '回光效应',
    Desc: [
      "角色击破特攻提高<color style='color:#f29e38;'> 50% </color>。",
      "角色击破特攻提高<color style='color:#f29e38;'> 75% </color>。",
    ],
    Effects: [],
    rel: [GainType.Healing],
  },
  {
    _id: 615552,
    Type: BuffType.Blessing,
    Path: 125,
    Rarity: 1,
    Icon: '/IconRogueWarrior02.webp',
    Name: '轨道红移',
    Desc: [
      "角色受到致命攻击时不会陷入无法战斗状态，并使当前生命值立即回复至自身生命上限的<color style='color:#f29e38;'> 1% </color>。该效果我方全体单场战斗中只能触发<color style='color:#f29e38;'> 1 </color>次。",
      "角色受到致命攻击时不会陷入无法战斗状态，并使当前生命值立即回复至自身生命上限的<color style='color:#f29e38;'> 30% </color>。该效果我方全体单场战斗中只能触发<color style='color:#f29e38;'> 1 </color>次。",
    ],
    Effects: [],
    rel: [GainType.HEAL],
  },
  {
    _id: 615553,
    Type: BuffType.Blessing,
    Path: 125,
    Rarity: 1,
    Icon: '/IconRogueWarrior04.webp',
    Name: '类星喷流',
    Desc: [
      "角色生命上限提高<color style='color:#f29e38;'> 16% </color>。",
      "角色生命上限提高<color style='color:#f29e38;'> 24% </color>。",
    ],
    Effects: [],
    rel: [GainType.BreakDmg, GainType.SuperBreakDmg, GainType.MON_BREAK_VUL],
  },
  {
    _id: 615554,
    Type: BuffType.Blessing,
    Path: 125,
    Rarity: 1,
    Icon: '/IconRogueWarrior02.webp',
    Name: '储备度规',
    Desc: [
      "敌方目标受到的击破伤害提高<color style='color:#f29e38;'> 24% </color>。",
      "敌方目标受到的击破伤害提高<color style='color:#f29e38;'> 36% </color>。",
    ],
    Effects: [],
    rel: [GainType.ConsumeHp, GainType.Shield],
  },
  {
    _id: 615555,
    Type: BuffType.Blessing,
    Path: 125,
    Rarity: 1,
    Icon: '/IconRogueWarrior02.webp',
    Name: '哨戒卫星',
    Desc: [
      "进入战斗时，角色消耗自身生命值至生命上限的<color style='color:#f29e38;'> 50% </color>，并获得能够抵消等同于已损失生命值<color style='color:#f29e38;'> 100% </color>伤害的护盾，持续<color style='color:#f29e38;'> 3 </color>回合。",
      "进入战斗时，角色消耗自身生命值至生命上限的<color style='color:#f29e38;'> 50% </color>，并获得能够抵消等同于已损失生命值<color style='color:#f29e38;'> 150% </color>伤害的护盾，持续<color style='color:#f29e38;'> 3 </color>回合。",
    ],
    Effects: [],
    rel: [GainType.ConsumeHp, GainType.Shield],
  },
  {
    _id: 615556,
    Type: BuffType.Blessing,
    Path: 125,
    Rarity: 1,
    Icon: '/IconRogueWarrior02.webp',
    Name: '偏振受体',
    Desc: [
      "当角色当前生命值百分比小于<color style='color:#f29e38;'> 50% </color>时，获得能够抵消等同于自身生命上限<color style='color:#f29e38;'> 20% </color>伤害的护盾，持续<color style='color:#f29e38;'> 2 </color>回合，该效果每名角色单场战斗中只能触发<color style='color:#f29e38;'> 1 </color>次。",
      "当角色当前生命值百分比小于<color style='color:#f29e38;'> 50% </color>时，获得能够抵消等同于自身生命上限<color style='color:#f29e38;'> 30% </color>伤害的护盾，持续<color style='color:#f29e38;'> 2 </color>回合，该效果每名角色单场战斗中只能触发<color style='color:#f29e38;'> 1 </color>次。",
    ],
    Effects: [],
    rel: [GainType.Healing, GainType.ConsumeHp, GainType.DEF],
  },
  {
    _id: 615557,
    Type: BuffType.Blessing,
    Path: 125,
    Rarity: 1,
    Icon: '/IconRogueWarrior02.webp',
    Name: '永坍缩体',
    Desc: [
      "角色损失或治疗自身生命值后，防御力提高<color style='color:#f29e38;'> 30% </color>，持续至下回合开始时。",
      "角色损失或治疗自身生命值后，防御力提高<color style='color:#f29e38;'> 45% </color>，持续至下回合开始时。",
    ],
    Effects: [],
    rel: [GainType.Healing, GainType.ConsumeHp, GainType.RESIST],
  },
  {
    _id: 615630,
    Type: BuffType.Blessing,
    Path: 126,
    Rarity: 3,
    Icon: '/IconRogueJoy01.webp',
    Name: '《葡萄庄园 • 抵抗黑夜》',
    Desc: [
      "角色损失或治疗自身生命值后，效果抵抗提高<color style='color:#f29e38;'> 16% </color>，持续至下回合开始时。",
      "角色损失或治疗自身生命值后，效果抵抗提高<color style='color:#f29e38;'> 24% </color>，持续至下回合开始时。",
    ],
    Effects: [60000003],
    rel: [GainType.FollowUpAtk, GainType.Aftertaste],
  },
  {
    _id: 615631,
    Type: BuffType.Blessing,
    Path: 126,
    Rarity: 3,
    Icon: '/IconRogueJoy01.webp',
    Name: '《四号屠场 • 众生安眠》',
    Desc: [
      "角色每次施放普攻/战技/终结技后，都会使下次发动追加攻击后，额外造成1次等同于角色攻击力<color style='color:#f29e38;'> 80% </color>的【<u class='infou'>回味</u>】伤害，通过该方式最多造成<color style='color:#f29e38;'> 5 </color>次。",
      "角色每次施放普攻/战技/终结技后，都会使下次发动追加攻击后，额外造成1次等同于角色攻击力<color style='color:#f29e38;'> 120% </color>的【<u class='infou'>回味</u>】伤害，通过该方式最多造成<color style='color:#f29e38;'> 5 </color>次。",
    ],
    Effects: [60000003],
    rel: [GainType.FollowUpAtk, GainType.AdditionalDmg, GainType.Aftertaste],
  },
  {
    _id: 615632,
    Type: BuffType.Blessing,
    Path: 126,
    Rarity: 3,
    Icon: '/IconRogueJoy04.webp',
    Name: '《斩首之邀 • 暗箱哭泣》',
    Desc: [
      "角色发动追加攻击后，对受到攻击的敌方目标造成1次等同于角色攻击力<color style='color:#f29e38;'> 80% </color>的【<u class='infou'>回味</u>】伤害。若敌方目标处于弱点击破状态，则额外造成<color style='color:#f29e38;'> 1 </color>次伤害。",
      "角色发动追加攻击后，对受到攻击的敌方目标造成1次等同于角色攻击力<color style='color:#f29e38;'> 80% </color>的【<u class='infou'>回味</u>】伤害。若敌方目标处于弱点击破状态，则额外造成<color style='color:#f29e38;'> 2 </color>次伤害。",
    ],
    Effects: [],
    rel: [GainType.FollowUpAtk, GainType.MON_act_delay],
  },
  {
    _id: 615640,
    Type: BuffType.Blessing,
    Path: 126,
    Rarity: 2,
    Icon: '/IconRogueJoy01.webp',
    Name: '《燃烧男子的肖像》',
    Desc: [
      "角色对敌方目标发动追加攻击后，使其行动延后<color style='color:#f29e38;'> 25% </color>，敌方目标每回合最多触发<color style='color:#f29e38;'> 2 </color>次。",
      "角色对敌方目标发动追加攻击后，使其行动延后<color style='color:#f29e38;'> 25% </color>，敌方目标每回合最多触发<color style='color:#f29e38;'> 3 </color>次。",
    ],
    Effects: [60000003],
    rel: [GainType.FollowUpAtk, GainType.AdditionalDmg, GainType.Aftertaste],
  },
  {
    _id: 615641,
    Type: BuffType.Blessing,
    Path: 126,
    Rarity: 2,
    Icon: '/IconRogueJoy04.webp',
    Name: '《砂时镜下的幼园》',
    Desc: [
      "角色对敌方目标造成【<u class='infou'>回味</u>】伤害时，额外造成<color style='color:#f29e38;'> 1 </color>次不同属性，且等同于原伤害<color style='color:#f29e38;'> 60% </color>的【<u class='infou'>回味</u>】伤害。",
      "角色对敌方目标造成【<u class='infou'>回味</u>】伤害时，额外造成<color style='color:#f29e38;'> 1 </color>次不同属性，且等同于原伤害<color style='color:#f29e38;'> 90% </color>的【<u class='infou'>回味</u>】伤害。",
    ],
    Effects: [60000003],
    rel: [GainType.FollowUpAtk, GainType.MON_ATK_DEC, GainType.Aftertaste],
  },
  {
    _id: 615642,
    Type: BuffType.Blessing,
    Path: 126,
    Rarity: 2,
    Icon: '/IconRogueJoy01.webp',
    Name: '《被涂污的信天翁》',
    Desc: [
      "敌方目标每受到1种属性的【<u class='infou'>回味</u>】伤害，攻击力降低<color style='color:#f29e38;'> 4% </color>，持续至下次行动后。",
      "敌方目标每受到1种属性的【<u class='infou'>回味</u>】伤害，攻击力降低<color style='color:#f29e38;'> 6% </color>，持续至下次行动后。",
    ],
    Effects: [],
    rel: [GainType.FollowUpAtk, GainType.AdditionalDmg],
  },
  {
    _id: 615643,
    Type: BuffType.Blessing,
    Path: 126,
    Rarity: 2,
    Icon: '/IconRogueJoy03.webp',
    Name: '《十二猴子与怒汉》',
    Desc: [
      "角色发动追加攻击后，每击中1个敌方目标，则对每个被击中的目标额外造成1次等同于角色攻击力<color style='color:#f29e38;'> 24% </color>的附加伤害。",
      "角色发动追加攻击后，每击中1个敌方目标，则对每个被击中的目标额外造成1次等同于角色攻击力<color style='color:#f29e38;'> 36% </color>的附加伤害。",
    ],
    Effects: [],
    rel: [GainType.FollowUpAtk],
  },
  {
    _id: 615644,
    Type: BuffType.Blessing,
    Path: 126,
    Rarity: 2,
    Icon: '/IconRogueJoy04.webp',
    Name: '《像弗莱明一样好》',
    Desc: [
      "角色对敌方目标造成追加攻击伤害时，使追加攻击伤害提高<color style='color:#f29e38;'> 4% </color>，最多叠加<color style='color:#f29e38;'> 24 </color>层，持续至下回合开始时。",
      "角色对敌方目标造成追加攻击伤害时，使追加攻击伤害提高<color style='color:#f29e38;'> 5% </color>，最多叠加<color style='color:#f29e38;'> 30 </color>层，持续至下回合开始时。",
    ],
    Effects: [],
    rel: [GainType.FollowUpAtk, GainType.MON_VUL_INC],
  },
  {
    _id: 615645,
    Type: BuffType.Blessing,
    Path: 126,
    Rarity: 2,
    Icon: '/IconRogueJoy03.webp',
    Name: '《鱼发现了火》',
    Desc: [
      "角色对敌方目标发动追加攻击后，使其受到的伤害提高<color style='color:#f29e38;'> 8% </color>，最多叠加<color style='color:#f29e38;'> 3 </color>次，持续<color style='color:#f29e38;'> 1 </color>回合。",
      "角色对敌方目标发动追加攻击后，使其受到的伤害提高<color style='color:#f29e38;'> 12% </color>，最多叠加<color style='color:#f29e38;'> 3 </color>次，持续<color style='color:#f29e38;'> 1 </color>回合。",
    ],
    Effects: [],
    rel: [GainType.FollowUpAtk, GainType.MON_DEF_DEC],
  },
  {
    _id: 615650,
    Type: BuffType.Blessing,
    Path: 126,
    Rarity: 1,
    Icon: '/IconRogueJoy01.webp',
    Name: '《看那些愚者》',
    Desc: [
      "角色造成的追加攻击伤害无视敌方目标<color style='color:#f29e38;'> 20% </color>的防御力。",
      "角色造成的追加攻击伤害无视敌方目标<color style='color:#f29e38;'> 27% </color>的防御力。",
    ],
    Effects: [],
    rel: [GainType.FollowUpAtk],
  },
  {
    _id: 615651,
    Type: BuffType.Blessing,
    Path: 126,
    Rarity: 1,
    Icon: '/IconRogueJoy03.webp',
    Name: '《基本有害》',
    Desc: [
      "角色造成的追加攻击暴击伤害提高<color style='color:#f29e38;'> 44% </color>。",
      "角色造成的追加攻击暴击伤害提高<color style='color:#f29e38;'> 66% </color>。",
    ],
    Effects: [],
    rel: [GainType.FollowUpAtk, GainType.BreakEfficiency],
  },
  {
    _id: 615652,
    Type: BuffType.Blessing,
    Path: 126,
    Rarity: 1,
    Icon: '/IconRogueJoy01.webp',
    Name: '《阴风阵阵》',
    Desc: [
      "角色造成追加攻击伤害时的弱点击破效率提高<color style='color:#f29e38;'> 35% </color>。",
      "角色造成追加攻击伤害时的弱点击破效率提高<color style='color:#f29e38;'> 50% </color>。",
    ],
    Effects: [],
    rel: [GainType.FollowUpAtk],
  },
  {
    _id: 615653,
    Type: BuffType.Blessing,
    Path: 126,
    Rarity: 1,
    Icon: '/IconRogueJoy01.webp',
    Name: '《灰暗的火》',
    Desc: [
      "角色造成的追加攻击伤害提高<color style='color:#f29e38;'> 26% </color>。",
      "角色造成的追加攻击伤害提高<color style='color:#f29e38;'> 39% </color>。",
    ],
    Effects: [],
    rel: [GainType.FollowUpAtk],
  },
  {
    _id: 615654,
    Type: BuffType.Blessing,
    Path: 126,
    Rarity: 1,
    Icon: '/IconRogueJoy03.webp',
    Name: '《回灯塔去》',
    Desc: [
      "角色造成的追加攻击伤害暴击率提高<color style='color:#f29e38;'> 26% </color>。",
      "角色造成的追加攻击伤害暴击率提高<color style='color:#f29e38;'> 39% </color>。",
    ],
    Effects: [],
    rel: [GainType.FollowUpAtk, GainType.ENERGY_Charge],
  },
  {
    _id: 615655,
    Type: BuffType.Blessing,
    Path: 126,
    Rarity: 1,
    Icon: '/IconRogueJoy02.webp',
    Name: '《奇爱医生》',
    Desc: [
      "角色发动追加攻击时，恢复<color style='color:#f29e38;'> 6 </color>点能量，该效果每回合最多触发<color style='color:#f29e38;'> 1 </color>次。",
      "角色发动追加攻击时，恢复<color style='color:#f29e38;'> 8 </color>点能量，该效果每回合最多触发<color style='color:#f29e38;'> 1 </color>次。",
    ],
    Effects: [],
    rel: [GainType.FollowUpAtk, GainType.Healing],
  },
  {
    _id: 615656,
    Type: BuffType.Blessing,
    Path: 126,
    Rarity: 1,
    Icon: '/IconRogueJoy02.webp',
    Name: '《铂金时代》',
    Desc: [
      "角色发动追加攻击后，回复等同于自身生命上限<color style='color:#f29e38;'> 10% </color>的生命值。",
      "角色发动追加攻击后，回复等同于自身生命上限<color style='color:#f29e38;'> 15% </color>的生命值。",
    ],
    Effects: [],
    rel: [GainType.FollowUpAtk, GainType.DEF],
  },
  {
    _id: 615657,
    Type: BuffType.Blessing,
    Path: 126,
    Rarity: 1,
    Icon: '/IconRogueJoy03.webp',
    Name: '《发条苹果》',
    Desc: [
      "角色发动追加攻击后，防御力提高<color style='color:#f29e38;'> 40% </color>，持续<color style='color:#f29e38;'> 1 </color>回合。",
      "角色发动追加攻击后，防御力提高<color style='color:#f29e38;'> 40% </color>，持续<color style='color:#f29e38;'> 2 </color>回合。",
    ],
    Effects: [],
    rel: [GainType.FollowUpAtk, GainType.SPD],
  },
  {
    _id: 615730,
    Type: BuffType.Blessing,
    Path: 127,
    Rarity: 3,
    Icon: '/IconRoguePropagation05.webp',
    Name: '子囊释放',
    Desc: [
      "角色发动追加攻击后，速度提高<color style='color:#f29e38;'> 16% </color>，持续<color style='color:#f29e38;'> 1 </color>回合。",
      "角色发动追加攻击后，速度提高<color style='color:#f29e38;'> 16% </color>，持续<color style='color:#f29e38;'> 2 </color>回合。",
    ],
    Effects: [60000017],
    rel: [GainType.Point, GainType.SporeCnt],
  },
  {
    _id: 615731,
    Type: BuffType.Blessing,
    Path: 127,
    Rarity: 3,
    Icon: '/IconRoguePropagation05.webp',
    Name: '菌种脓疱',
    Desc: [
      "角色每消耗1个战技点，使敌方全体获得<color style='color:#f29e38;'> 1 </color>个【<u class='infou'>孢子</u>】。",
      "角色每消耗1个战技点，使敌方全体获得<color style='color:#f29e38;'> 1 </color>个【<u class='infou'>孢子</u>】。若将战技点消耗至0，则使消耗最后一个战技点的角色速度提高<color style='color:#f29e38;'> 20% </color>，持续<color style='color:#f29e38;'> 2 </color>回合。",
    ],
    Effects: [60000017],
    rel: [GainType.Point, GainType.SporeCnt],
  },
  {
    _id: 615732,
    Type: BuffType.Blessing,
    Path: 127,
    Rarity: 3,
    Icon: '/IconRoguePropagation01.webp',
    Name: '镰刀肢足',
    Desc: [
      "角色每恢复1个战技点，使随机<color style='color:#f29e38;'> 2 </color>名敌方目标获得1个【<u class='infou'>孢子</u>】。",
      "角色每恢复1个战技点，使随机<color style='color:#f29e38;'> 2 </color>名敌方目标获得1个【<u class='infou'>孢子</u>】，【<u class='infou'>孢子</u>】上限提高<color style='color:#f29e38;'> 3 </color>个。",
    ],
    Effects: [],
    rel: [GainType.UltimateAtk, GainType.Point, GainType.CRITDMG],
  },
  {
    _id: 615746,
    Type: BuffType.Blessing,
    Path: 127,
    Rarity: 2,
    Icon: '/IconRoguePropagation04.webp',
    Name: '阻滞胺',
    Desc: [
      "角色施放终结技后，下一次消耗战技点时会被视为额外消耗1个战技点。每消耗1个战技点，角色暴击伤害提高<color style='color:#f29e38;'> 40% </color>，该效果最多叠加<color style='color:#f29e38;'> 2 </color>层，持续至该角色施放攻击后。",
      "角色施放终结技后，下一次消耗或恢复战技点时会被视为额外消耗或恢复1个战技点。每消耗或恢复1个战技点，角色暴击伤害提高<color style='color:#f29e38;'> 45% </color>，该效果最多叠加<color style='color:#f29e38;'> 2 </color>层，持续至该角色施放攻击后。",
    ],
    Effects: [60000017],
    rel: [GainType.SporeDmg, GainType.MON_DEF_DEC],
  },
  {
    _id: 615740,
    Type: BuffType.Blessing,
    Path: 127,
    Rarity: 2,
    Icon: '/IconRoguePropagation05.webp',
    Name: '腐殖疮',
    Desc: [
      "【<u class='infou'>孢子</u>】爆裂后的传播次数变为<color style='color:#f29e38;'> 2 </color>次，并且可以传播给持有【<u class='infou'>孢子</u>】的敌方目标自身。",
      "【<u class='infou'>孢子</u>】爆裂后的传播次数变为<color style='color:#f29e38;'> 3 </color>次，并且可以传播给持有【<u class='infou'>孢子</u>】的敌方目标自身。",
    ],
    Effects: [60000017],
    rel: [GainType.SporeCnt],
  },
  {
    _id: 615741,
    Type: BuffType.Blessing,
    Path: 127,
    Rarity: 2,
    Icon: '/IconRoguePropagation01.webp',
    Name: '裂解酶',
    Desc: [
      "【<u class='infou'>孢子</u>】爆裂造成的伤害提高，提高数值等同于原伤害的<color style='color:#f29e38;'> 35% </color>，敌方目标被消灭后，将受到攻击前持有的【<u class='infou'>孢子</u>】传播给相邻目标。",
      "【<u class='infou'>孢子</u>】爆裂造成的伤害提高，提高数值等同于原伤害的<color style='color:#f29e38;'> 50% </color>，敌方目标被消灭后，将受到攻击前持有的【<u class='infou'>孢子</u>】传播给其他敌方目标。",
    ],
    Effects: [60000017],
    rel: [GainType.SporeDmg, GainType.SporeCnt],
  },
  {
    _id: 615742,
    Type: BuffType.Blessing,
    Path: 127,
    Rarity: 2,
    Icon: '/IconRoguePropagation05.webp',
    Name: '兴奋腺',
    Desc: [
      "角色造成的普攻伤害提高<color style='color:#f29e38;'> 30% </color>。消耗战技点时，有<color style='color:#f29e38;'> 15% </color>固定概率恢复1个战技点。",
      "角色造成的普攻伤害提高<color style='color:#f29e38;'> 50% </color>。消耗战技点时，有<color style='color:#f29e38;'> 20% </color>固定概率恢复1个战技点。",
    ],
    Effects: [],
    rel: [GainType.NomralAtk, GainType.Point],
  },
  {
    _id: 615743,
    Type: BuffType.Blessing,
    Path: 127,
    Rarity: 2,
    Icon: '/IconRoguePropagation05.webp',
    Name: '裸脑质',
    Desc: [
      "角色造成的普攻伤害会对随机相邻单体，造成等同于原伤害<color style='color:#f29e38;'> 30% </color>的伤害。",
      "角色造成的普攻伤害会对相邻目标，造成等同于原伤害<color style='color:#f29e38;'> 35% </color>的伤害。",
    ],
    Effects: [],
    rel: [GainType.DamageSpread, GainType.NomralAtk],
  },
  {
    _id: 615744,
    Type: BuffType.Blessing,
    Path: 127,
    Rarity: 2,
    Icon: '/IconRoguePropagation02.webp',
    Name: '节间膜',
    Desc: [
      "角色每消耗1个战技点，受到的伤害降低<color style='color:#f29e38;'> 8% </color>，持续<color style='color:#f29e38;'> 1 </color>回合，该效果最多叠加<color style='color:#f29e38;'> 2 </color>层。",
      "角色每消耗1个战技点，受到的伤害降低<color style='color:#f29e38;'> 8% </color>，持续<color style='color:#f29e38;'> 1 </color>回合，该效果最多叠加<color style='color:#f29e38;'> 3 </color>层。",
    ],
    Effects: [],
    rel: [GainType.Point, GainType.DMG_RESIST],
  },
  {
    _id: 615745,
    Type: BuffType.Blessing,
    Path: 127,
    Rarity: 2,
    Icon: '/IconRoguePropagation01.webp',
    Name: '催化剂',
    Desc: [
      "角色施放战技后，若该次战技未施放攻击，则使我方全体造成的伤害提高<color style='color:#f29e38;'> 20% </color>，持续<color style='color:#f29e38;'> 1 </color>回合，该效果最多叠加<color style='color:#f29e38;'> 3 </color>次。",
      "角色施放战技后，若该次战技未施放攻击，则使我方全体造成的伤害提高<color style='color:#f29e38;'> 30% </color>，持续<color style='color:#f29e38;'> 1 </color>回合，该效果最多叠加<color style='color:#f29e38;'> 3 </color>次。",
    ],
    Effects: [],
    rel: [GainType.Point, GainType.DMG_Gain],
  },
  {
    _id: 615750,
    Type: BuffType.Blessing,
    Path: 127,
    Rarity: 1,
    Icon: '/IconRoguePropagation01.webp',
    Name: '骨刃',
    Desc: [
      "角色造成的普攻伤害提高<color style='color:#f29e38;'> 24% </color>。",
      "角色造成的普攻伤害提高<color style='color:#f29e38;'> 36% </color>。",
    ],
    Effects: [],
    rel: [GainType.NomralAtk],
  },
  {
    _id: 615751,
    Type: BuffType.Blessing,
    Path: 127,
    Rarity: 1,
    Icon: '/IconRoguePropagation01.webp',
    Name: '脊刺',
    Desc: [
      "角色造成的普攻伤害暴击率提高<color style='color:#f29e38;'> 24% </color>。",
      "角色造成的普攻伤害暴击率提高<color style='color:#f29e38;'> 36% </color>。",
    ],
    Effects: [],
    rel: [GainType.NomralAtk],
  },
  {
    _id: 615752,
    Type: BuffType.Blessing,
    Path: 127,
    Rarity: 1,
    Icon: '/IconRoguePropagation01.webp',
    Name: '槽针',
    Desc: [
      "角色造成的普攻伤害暴击伤害提高<color style='color:#f29e38;'> 40% </color>。",
      "角色造成的普攻伤害暴击伤害提高<color style='color:#f29e38;'> 60% </color>。",
    ],
    Effects: [],
    rel: [GainType.NomralAtk],
  },
  {
    _id: 615753,
    Type: BuffType.Blessing,
    Path: 127,
    Rarity: 1,
    Icon: '/IconRoguePropagation02.webp',
    Name: '结膜',
    Desc: [
      "角色施放普攻后，防御力提高<color style='color:#f29e38;'> 40% </color>，持续<color style='color:#f29e38;'> 1 </color>回合。",
      "角色施放普攻后，防御力提高<color style='color:#f29e38;'> 40% </color>，持续<color style='color:#f29e38;'> 2 </color>回合。",
    ],
    Effects: [],
    rel: [GainType.NomralAtk, GainType.DEF],
  },
  {
    _id: 615754,
    Type: BuffType.Blessing,
    Path: 127,
    Rarity: 1,
    Icon: '/IconRoguePropagation03.webp',
    Name: '鳞翅',
    Desc: [
      "角色施放普攻后，速度提高<color style='color:#f29e38;'> 16% </color>，持续<color style='color:#f29e38;'> 1 </color>回合。",
      "角色施放普攻后，速度提高<color style='color:#f29e38;'> 16% </color>，持续<color style='color:#f29e38;'> 2 </color>回合。",
    ],
    Effects: [],
    rel: [GainType.NomralAtk, GainType.SPD],
  },
  {
    _id: 615755,
    Type: BuffType.Blessing,
    Path: 127,
    Rarity: 1,
    Icon: '/IconRoguePropagation05.webp',
    Name: '复眼',
    Desc: [
      "进入战斗后，我方单体行动后恢复1个战技点，该效果我方全体最多触发<color style='color:#f29e38;'> 3 </color>次。",
      "进入战斗后，我方单体行动后恢复1个战技点，该效果我方全体最多触发<color style='color:#f29e38;'> 5 </color>次。",
    ],
    Effects: [],
    rel: [GainType.Point],
  },
  {
    _id: 615756,
    Type: BuffType.Blessing,
    Path: 127,
    Rarity: 1,
    Icon: '/IconRoguePropagation05.webp',
    Name: '孢夹',
    Desc: [
      "角色每消耗1个战技点，该角色额外恢复<color style='color:#f29e38;'> 3 </color>点能量。",
      "角色每消耗1个战技点，该角色额外恢复<color style='color:#f29e38;'> 4 </color>点能量。",
    ],
    Effects: [],
    rel: [GainType.Point, GainType.ENERGY_Charge],
  },
  {
    _id: 615757,
    Type: BuffType.Blessing,
    Path: 127,
    Rarity: 1,
    Icon: '/IconRoguePropagation05.webp',
    Name: '液囊',
    Desc: [
      "角色每消耗1个战技点，回复等同于其生命上限<color style='color:#f29e38;'> 10% </color>的生命值。",
      "角色每消耗1个战技点，回复等同于其生命上限<color style='color:#f29e38;'> 15% </color>的生命值。",
    ],
    Effects: [],
    rel: [GainType.Point, GainType.Healing],
  },
  {
    _id: 615830,
    Type: BuffType.Blessing,
    Path: 128,
    Rarity: 3,
    Icon: '/IconRogueMage03.webp',
    Name: 'BCI -34 型灰质',
    Desc: [
      "进入战斗时，为【<u class='infou'>罐中脑</u>】充能<color style='color:#f29e38;'> 65% </color>。角色击破敌方目标弱点后，为【<u class='infou'>罐中脑</u>】充能<color style='color:#f29e38;'> 35% </color>。",
      "进入战斗时，为【<u class='infou'>罐中脑</u>】充能<color style='color:#f29e38;'> 100% </color>。角色击破敌方目标弱点，或攻击处于弱点击破状态下的敌方目标时，分别为【<u class='infou'>罐中脑</u>】充能<color style='color:#f29e38;'> 40% </color>或<color style='color:#f29e38;'> 5% </color>，该效果每次攻击对每个敌方单体最多触发1次。",
    ],
    Effects: [61000044],
    rel: [GainType.Brain_in_a_Vat_Charge, GainType.HitWeak],
  },
  {
    _id: 615831,
    Type: BuffType.Blessing,
    Path: 128,
    Rarity: 3,
    Icon: '/IconRogueMage03.webp',
    Name: 'SMR-2型杏仁核',
    Desc: [
      "角色使敌方目标受到致命伤害时，为【<u class='infou'>罐中脑</u>】充能<color style='color:#f29e38;'> 50% </color>。",
      "角色使敌方目标受到致命伤害时，为【<u class='infou'>罐中脑</u>】充能<color style='color:#f29e38;'> 50% </color>，每次充满【<u class='infou'>罐中脑</u>】后，使角色速度提高<color style='color:#f29e38;'> 20% </color>，持续<color style='color:#f29e38;'> 2 </color>回合。",
    ],
    Effects: [61000044],
    rel: [GainType.Kill, GainType.Brain_in_a_Vat_Charge],
  },
  {
    _id: 615832,
    Type: BuffType.Blessing,
    Path: 128,
    Rarity: 3,
    Icon: '/IconRogueMage01.webp',
    Name: 'VEP -18 型枕叶',
    Desc: [
      "角色造成的终结技伤害的全属性抗性穿透提高<color style='color:#f29e38;'> 20% </color>，施放终结技后，每有1个受到攻击的敌方目标，都会使造成的终结技伤害的全属性抗性穿透额外提高<color style='color:#f29e38;'> 3% </color>，持续至下一次施放终结技后。",
      "角色造成的终结技伤害的全属性抗性穿透提高<color style='color:#f29e38;'> 25% </color>。基于本场战斗中已施放的终结技单次攻击敌方目标的最大数量，每1名都会使造成的终结技伤害的全属性抗性穿透额外提高<color style='color:#f29e38;'> 3% </color>。",
    ],
    Effects: [],
    rel: [GainType.UltimateAtk, GainType.ResistStrike],
  },
  {
    _id: 615840,
    Type: BuffType.Blessing,
    Path: 128,
    Rarity: 2,
    Icon: '/IconRogueMage01.webp',
    Name: '附加：前庭系统',
    Desc: [
      "角色利用【<u class='infou'>罐中脑</u>】施放终结技时，使暴击伤害提高<color style='color:#f29e38;'> 80% </color>，持续至本次技能结束。",
      "角色利用【<u class='infou'>罐中脑</u>】施放终结技时，使暴击伤害提高<color style='color:#f29e38;'> 90% </color>，暴击伤害提高效果会持续至下一次攻击结束。",
    ],
    Effects: [61000044],
    rel: [GainType.UltimateAtk, GainType.Brain_in_a_Vat],
  },
  {
    _id: 615841,
    Type: BuffType.Blessing,
    Path: 128,
    Rarity: 2,
    Icon: '/IconRogueMage02.webp',
    Name: '植入：外显记忆',
    Desc: [
      "角色利用【<u class='infou'>罐中脑</u>】施放终结技后，获得等同于生命上限<color style='color:#f29e38;'> 36% </color>的护盾，持续<color style='color:#f29e38;'> 2 </color>回合。",
      "角色利用【<u class='infou'>罐中脑</u>】施放终结技后，获得等同于生命上限<color style='color:#f29e38;'> 45% </color>的护盾，持续<color style='color:#f29e38;'> 3 </color>回合。",
    ],
    Effects: [61000044],
    rel: [GainType.Brain_in_a_Vat, GainType.UltimateAtk, GainType.Shield],
  },
  {
    _id: 615842,
    Type: BuffType.Blessing,
    Path: 128,
    Rarity: 2,
    Icon: '/IconRogueMage01.webp',
    Name: '拟态：触觉通路',
    Desc: [
      "角色施放攻击后，对受到攻击的敌方目标造成附加伤害，每有一个受到攻击的敌方目标，附加伤害数值提高等同于角色攻击力的<color style='color:#f29e38;'> 15% </color>。",
      "角色施放攻击后，对受到攻击的敌方目标造成附加伤害，每有一个受到攻击的敌方目标，附加伤害数值提高等同于角色攻击力的<color style='color:#f29e38;'> 20% </color>。本场战斗中被消灭过的敌方目标也会被视为受到攻击，最多不超过5个。",
    ],
    Effects: [],
    rel: [GainType.AdditionalDmg],
  },
  {
    _id: 615843,
    Type: BuffType.Blessing,
    Path: 128,
    Rarity: 2,
    Icon: '/IconRogueMage01.webp',
    Name: '分析：阈下知觉',
    Desc: [
      "角色造成的终结技伤害提高<color style='color:#f29e38;'> 50% </color>，持续至首次施放终结技后。进入战斗时，回复等同于能量上限<color style='color:#f29e38;'> 60% </color>的能量。",
      "角色造成的终结技伤害提高<color style='color:#f29e38;'> 50% </color>，进入战斗时，回复等同于能量上限<color style='color:#f29e38;'> 100% </color>的能量。",
    ],
    Effects: [],
    rel: [GainType.UltimateAtk, GainType.ENERGY_Charge],
  },
  {
    _id: 615030,
    Type: BuffType.Blessing,
    Path: 120,
    Rarity: 3,
    Icon: '/IconRogueKnight01.webp',
    Name: '神性构筑 • 谐振传递',
    Desc: [
      "若角色的<u class='infou'>群攻</u>技能只攻击了1个敌方目标，则本次攻击对受到攻击的敌方目标额外造成等同于原伤害<color style='color:#f29e38;'> 40% </color>的固定数值的伤害。",
      "若角色的<u class='infou'>群攻</u>技能只攻击了1个敌方目标，则本次攻击对受到攻击的敌方目标额外造成等同于原伤害<color style='color:#f29e38;'> 60% </color>的固定数值的伤害。",
    ],
    Effects: [BlessingExtra.Quake],
    rel: [GainType.Shield, GainType.QuakeDmg],
  },
  {
    _id: 615844,
    Type: BuffType.Blessing,
    Path: 128,
    Rarity: 2,
    Icon: '/IconRogueMage01.webp',
    Name: '装载：纹状皮层',
    Desc: [
      "角色施放终结技攻击处于弱点击破状态下的敌方目标后，使其行动延后<color style='color:#f29e38;'> 16% </color>，敌方目标每次陷入弱点击破状态后最多触发<color style='color:#f29e38;'> 3 </color>次该效果。",
      "角色施放终结技攻击处于弱点击破状态下的敌方目标后，使其行动延后<color style='color:#f29e38;'> 24% </color>，敌方目标每次陷入弱点击破状态后最多触发<color style='color:#f29e38;'> 3 </color>次该效果。",
    ],
    Effects: [],
    rel: [GainType.AdditionalDmg],
  },
  {
    _id: 615845,
    Type: BuffType.Blessing,
    Path: 128,
    Rarity: 2,
    Icon: '/IconRogueMage04.webp',
    Name: '激发：跳跃传导',
    Desc: [
      "角色造成的终结技伤害提高<color style='color:#f29e38;'> 18% </color>。",
      "角色造成的终结技伤害提高<color style='color:#f29e38;'> 27% </color>。",
    ],
    Effects: [],
    rel: [GainType.HitWeak, GainType.MON_act_delay],
  },
  {
    _id: 615850,
    Type: BuffType.Blessing,
    Path: 128,
    Rarity: 1,
    Icon: '/IconRogueMage01.webp',
    Name: '齿轮啮合的王座',
    Desc: [
      "角色造成的终结技伤害暴击率提高<color style='color:#f29e38;'> 18% </color>。",
      "角色造成的终结技伤害暴击率提高<color style='color:#f29e38;'> 27% </color>。",
    ],
    Effects: [],
    rel: [GainType.UltimateAtk],
  },
  {
    _id: 615851,
    Type: BuffType.Blessing,
    Path: 128,
    Rarity: 1,
    Icon: '/IconRogueMage01.webp',
    Name: '导线弯绕的指环',
    Desc: [
      "角色造成的终结技伤害暴击伤害提高<color style='color:#f29e38;'> 30% </color>。",
      "角色造成的终结技伤害暴击伤害提高<color style='color:#f29e38;'> 45% </color>。",
    ],
    Effects: [],
    rel: [GainType.UltimateAtk],
  },
  {
    _id: 615852,
    Type: BuffType.Blessing,
    Path: 128,
    Rarity: 1,
    Icon: '/IconRogueMage01.webp',
    Name: '能量变矩的权杖',
    Desc: [
      "角色施放终结技后的下一次攻击造成的伤害提高<color style='color:#f29e38;'> 50% </color>。",
      "角色施放终结技后的下一次攻击造成的伤害提高<color style='color:#f29e38;'> 75% </color>。",
    ],
    Effects: [],
    rel: [GainType.UltimateAtk],
  },
  {
    _id: 615853,
    Type: BuffType.Blessing,
    Path: 128,
    Rarity: 1,
    Icon: '/IconRogueMage01.webp',
    Name: '偏时引燃的炬火',
    Desc: [
      "角色施放终结技时，使攻击力提高<color style='color:#f29e38;'> 24% </color>，持续<color style='color:#f29e38;'> 2 </color>回合。",
      "角色施放终结技时，使攻击力提高<color style='color:#f29e38;'> 36% </color>，持续<color style='color:#f29e38;'> 2 </color>回合。",
    ],
    Effects: [],
    rel: [GainType.UltimateAtk],
  },
  {
    _id: 615854,
    Type: BuffType.Blessing,
    Path: 128,
    Rarity: 1,
    Icon: '/IconRogueMage03.webp',
    Name: '离子推进的宝剑',
    Desc: [
      "角色施放攻击后，每攻击一名敌方目标，使生命上限提高<color style='color:#f29e38;'> 5% </color>，最多叠加<color style='color:#f29e38;'> 5 </color>次，持续至下回合开始时。",
      "角色施放攻击后，每攻击一名敌方目标，使生命上限提高<color style='color:#f29e38;'> 7.5% </color>，最多叠加<color style='color:#f29e38;'> 5 </color>次，持续至下回合开始时。",
    ],
    Effects: [],
    rel: [GainType.UltimateAtk, GainType.ATK],
  },
  {
    _id: 615855,
    Type: BuffType.Blessing,
    Path: 128,
    Rarity: 1,
    Icon: '/IconRogueMage02.webp',
    Name: '钢铁熔铸的绶带',
    Desc: [
      "角色施放终结技后，回复等同于生命上限<color style='color:#f29e38;'> 16% </color>的生命值。",
      "角色施放终结技后，回复等同于生命上限<color style='color:#f29e38;'> 24% </color>的生命值。",
    ],
    Effects: [],
    rel: [GainType.HEAL],
  },
  {
    _id: 615856,
    Type: BuffType.Blessing,
    Path: 128,
    Rarity: 1,
    Icon: '/IconRogueMage02.webp',
    Name: '线圈编织的罗绮',
    Desc: [
      "角色受到致命攻击时，不会陷入无法战斗状态，消耗自身所有能量，回复等同于消耗能量值百分比的<color style='color:#f29e38;'> 50% </color>的生命值，全队每场战斗只能触发1次。",
      "角色受到致命攻击时，不会陷入无法战斗状态，消耗自身所有能量，回复等同于消耗能量值百分比的<color style='color:#f29e38;'> 100% </color>的生命值，全队每场战斗只能触发1次。",
    ],
    Effects: [],
    rel: [GainType.UltimateAtk, GainType.Healing],
  },
  {
    _id: 615857,
    Type: BuffType.Blessing,
    Path: 128,
    Rarity: 1,
    Icon: '/IconRogueMage02.webp',
    Name: '管道交错的桂冠',
    Desc: [
      "角色造成的【<u class='infou'>反震</u>】伤害，暴击率提高<color style='color:#f29e38;'> 20% </color>，暴击伤害提高<color style='color:#f29e38;'> 50% </color>。",
      "角色造成的【<u class='infou'>反震</u>】伤害，暴击率提高<color style='color:#f29e38;'> 30% </color>，暴击伤害提高<color style='color:#f29e38;'> 75% </color>。",
    ],
    Effects: [],
    rel: [GainType.Healing],
  },
  {
    _id: 615046,
    Type: BuffType.Blessing,
    Path: 120,
    Rarity: 2,
    Icon: '/IconRogueKnight01.webp',
    Name: '星间构筑 • 倒易立方',
    Desc: [
      "我方目标施放攻击后，有<color style='color:#f29e38;'> 40% </color>的基础概率使攻击目标陷入【<u class='infou'>离神</u>】状态，该效果对每个敌方目标单场战斗最多触发<color style='color:#f29e38;'> 1 </color>次。",
      "我方目标施放攻击后，有<color style='color:#f29e38;'> 60% </color>的基础概率使攻击目标陷入【<u class='infou'>离神</u>】状态，该效果对每个敌方目标单场战斗最多触发<color style='color:#f29e38;'> 1 </color>次。",
    ],
    Effects: [BlessingExtra.Quake],
    rel: [GainType.QuakeDmg],
  },
  {
    _id: 615146,
    Type: BuffType.Blessing,
    Path: 121,
    Rarity: 2,
    Icon: '/IconRogueMemory04.webp',
    Name: '极端体验：愤世嫉俗',
    Desc: [
      "敌方目标进入战斗时，获得<color style='color:#f29e38;'> 30 </color>层【<u class='infou'>怀疑</u>】。",
      "敌方目标进入战斗时，获得<color style='color:#f29e38;'> 45 </color>层【<u class='infou'>怀疑</u>】。",
    ],
    Effects: [60000002],
    rel: [GainType.DissociationDmg, GainType.Freeze],
  },
  {
    _id: 615246,
    Type: BuffType.Blessing,
    Path: 122,
    Rarity: 2,
    Icon: '/IconRogueWarlock04.webp',
    Name: '林中的通径',
    Desc: [
      "角色造成的【<u class='infou'>珠露</u>】伤害，暴击率提高<color style='color:#f29e38;'> 20% </color>，暴击伤害提高<color style='color:#f29e38;'> 50% </color>。",
      "角色造成的【<u class='infou'>珠露</u>】伤害，暴击率提高<color style='color:#f29e38;'> 30% </color>，暴击伤害提高<color style='color:#f29e38;'> 75% </color>。",
    ],
    Effects: [60000012],
    rel: [GainType.Suspicion, GainType.MON_in_NEG_EFFECT],
  },
  {
    _id: 615346,
    Type: BuffType.Blessing,
    Path: 123,
    Rarity: 2,
    Icon: '/IconRoguePirest01.webp',
    Name: '燃臂供万生',
    Desc: [
      "角色回合开始时，若持有大于等于<color style='color:#f29e38;'> 4 </color>层【<u class='infou'>会心</u>】，速度提高<color style='color:#f29e38;'> 24% </color>，持续<color style='color:#f29e38;'> 2 </color>回合。",
      "角色回合开始时，若持有大于等于<color style='color:#f29e38;'> 4 </color>层【<u class='infou'>会心</u>】，速度提高<color style='color:#f29e38;'> 36% </color>，持续<color style='color:#f29e38;'> 2 </color>回合。",
    ],
    Effects: [60000013],
    rel: [GainType.DewDropCharge],
  },
  {
    _id: 615446,
    Type: BuffType.Blessing,
    Path: 124,
    Rarity: 2,
    Icon: '/IconRogueRogue03.webp',
    Name: '金戈平寿瘟',
    Desc: [
      "角色进入战斗时，获得<color style='color:#f29e38;'> 12 </color>层【<u class='infou'>战意</u>】。",
      "角色进入战斗时，获得<color style='color:#f29e38;'> 18 </color>层【<u class='infou'>战意</u>】。",
    ],
    Effects: [60000004],
    rel: [GainType.CriticalBoost, GainType.SPD],
  },
  {
    _id: 615546,
    Type: BuffType.Blessing,
    Path: 125,
    Rarity: 2,
    Icon: '/IconRogueWarrior03.webp',
    Name: '回归性暴涨',
    Desc: [
      "角色造成的【<u class='infou'>回味</u>】伤害提高<color style='color:#f29e38;'> 70% </color>。",
      "角色造成的【<u class='infou'>回味</u>】伤害提高<color style='color:#f29e38;'> 105% </color>。",
    ],
    Effects: [60000005],
    rel: [GainType.Grit],
  },
  {
    _id: 615646,
    Type: BuffType.Blessing,
    Path: 126,
    Rarity: 2,
    Icon: '/IconRogueJoy01.webp',
    Name: '《最后的塔拉克人》',
    Desc: [
      "敌方目标受到【<u class='infou'>孢子</u>】伤害后，防御力降低<color style='color:#f29e38;'> 1% </color>，该效果最多叠加<color style='color:#f29e38;'> 15 </color>层。",
      "敌方目标受到【<u class='infou'>孢子</u>】伤害后，防御力降低<color style='color:#f29e38;'> 1% </color>，该效果最多叠加<color style='color:#f29e38;'> 20 </color>层。",
    ],
    Effects: [60000003],
    rel: [GainType.FollowUpAtk, GainType.Aftertaste],
  },
  {
    _id: 615846,
    Type: BuffType.Blessing,
    Path: 128,
    Rarity: 2,
    Icon: '/IconRogueMage01.webp',
    Name: '协调：共振核团',
    Desc: [
      "角色使用【<u class='infou'>罐中脑</u>】施放终结技后，攻击力提高<color style='color:#f29e38;'> 60% </color>，持续<color style='color:#f29e38;'> 2 </color>回合。",
      "角色使用【<u class='infou'>罐中脑</u>】施放终结技后，攻击力提高<color style='color:#f29e38;'> 90% </color>，持续<color style='color:#f29e38;'> 2 </color>回合。",
    ],
    Effects: [61000044],
    rel: [GainType.Brain_in_a_Vat, GainType.ATK],
  },
]

const sortedBlessings = sortAllBlessings(blessings)

export { blessings as BLESSINGS, sortedBlessings as SORTED_BLESSINGS }
